// Generato automaticamente il 2026-06-16 17:09 UTC da scripts/fetch_news.py
// NON modificare manualmente: viene sovrascritto ogni ora dalla GitHub Action.
var NEWS_TIMESTAMP = 1781629759;

const RSS_SOURCES = [
  {
    "name": "ANSA",
    "url": "https://www.ansa.it/sito/ansait_rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Corriere",
    "url": "https://xml2.corrieredellasera.it/rss/homepage.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Il Post",
    "url": "https://www.ilpost.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Sky TG24",
    "url": "https://tg24.sky.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "AGI",
    "url": "https://www.agi.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Pagella Politica",
    "url": "https://pagellapolitica.it/feed",
    "cat": "politica-italiana"
  },
  {
    "name": "Facta",
    "url": "https://facta.news/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Valigia Blu",
    "url": "https://www.valigiablu.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Limes",
    "url": "https://www.limesonline.com/feed",
    "cat": "geopolitica"
  },
  {
    "name": "Internazionale",
    "url": "https://www.internazionale.it/feed/tutto",
    "cat": "geopolitica"
  },
  {
    "name": "BBC World",
    "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "AP",
    "url": "https://apnews.com/hub/world-news?output=rss",
    "cat": "geopolitica"
  },
  {
    "name": "The Economist",
    "url": "https://www.economist.com/international/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "El Pais",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "cat": "geopolitica"
  },
  {
    "name": "Reuters",
    "url": "https://feeds.reuters.com/reuters/worldNews",
    "cat": "conflitti"
  },
  {
    "name": "Al Jazeera",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "cat": "conflitti"
  },
  {
    "name": "AP conflitti",
    "url": "https://apnews.com/hub/wars-and-conflicts?output=rss",
    "cat": "conflitti"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/rss/index.xml",
    "cat": "ai"
  },
  {
    "name": "Wired IT",
    "url": "https://www.wired.it/feed/rss",
    "cat": "ai"
  },
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Post Tech",
    "url": "https://www.ilpost.it/tecnologia/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Sole 24 Ore",
    "url": "https://www.ilsole24ore.com/rss/economia.xml",
    "cat": "economia-tech"
  },
  {
    "name": "Bloomberg Tech",
    "url": "https://feeds.bloomberg.com/technology/news.rss",
    "cat": "economia-tech"
  },
  {
    "name": "Financial Times",
    "url": "https://www.ft.com/rss/home",
    "cat": "economia-tech"
  },
  {
    "name": "The Economist Ec",
    "url": "https://www.economist.com/business/rss.xml",
    "cat": "economia-tech"
  }
];

const NEWS = [
  {
    id: 1,
    cat: "politica-italiana",
    title: "Siparietto Trump-Meloni al G7, la premier: \"Siamo sempre stati amici\"",
    summary: "Il presidente Usa replica: \"Sono stato abbandonato\" e Meloni: \"No, non è così\"",
    body: "Il presidente Usa replica: \"Sono stato abbandonato\" e Meloni: \"No, non è così\"",
    source: "ANSA",
    url: "https://www.ansa.it/sito/videogallery/mondo/2026/06/16/siparietto-trump-meloni-al-g7-la-premier-siamo-sempre-stati-amici_9d6178b4-ed8c-4326-962e-21817ecadb7b.html",
    time: "36 min fa",
    pub_ts: 1781627548,
    tags: [],
  },
  {
    id: 2,
    cat: "politica-italiana",
    title: "Summit del campo largo, programmate due riunioni dei leader l'8 e il 15 luglio",
    summary: "Il messaggio dei leader di Pd, M5s, Avs: 'Al lavoro. Per cambiare l'Italia'",
    body: "Il messaggio dei leader di Pd, M5s, Avs: 'Al lavoro. Per cambiare l'Italia'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/politica/2026/06/16/summit-del-campo-largo-programmate-due-riunioni-dei-leader-l8-e-il-15-luglio_6fb5b561-f96f-432a-b38c-3fb8e9f652af.html",
    time: "41 min fa",
    pub_ts: 1781627263,
    tags: [],
  },
  {
    id: 3,
    cat: "politica-italiana",
    title: "L'esame di maturità al via il 18 giugno. I candidati sono oltre 527 mila",
    summary: "Si inizia con la prova di italiano. 13.996 le commissioni che si sono insediate",
    body: "Si inizia con la prova di italiano. 13.996 le commissioni che si sono insediate",
    source: "ANSA",
    url: "https://www.ansa.it/canale_legalita_scuola/notizie/mim/2026/06/16/lesame-di-maturita-al-via-il-18-giugno.-i-candidati-sono-oltre-527-mila_02bc5a82-ecbc-43d5-9f9f-20546a244e79.html",
    time: "42 min fa",
    pub_ts: 1781627200,
    tags: [],
  },
  {
    id: 4,
    cat: "politica-italiana",
    title: "Medio Oriente, Teheran: 'Il blocco statunitense dei porti è stato revocato'",
    summary: "La firma dell'accordo Usa-Iran venerdì a Lucerna, riferisce il Governo svizzero. Araghchi: 'L'occupazione israeliana del Libano viola il memorandum Iran-Usa'",
    body: "La firma dell'accordo Usa-Iran venerdì a Lucerna, riferisce il Governo svizzero. Araghchi: 'L'occupazione israeliana del Libano viola il memorandum Iran-Usa'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/06/16/medio-oriente-la-firma-dellaccordo-usa-iran-venerdi-a-lucerna_bd76d99b-72bc-4b56-adb2-0bfa1cdad850.html",
    time: "56 min fa",
    pub_ts: 1781626374,
    tags: [],
  },
  {
    id: 5,
    cat: "politica-italiana",
    title: "Rapporto Reuters: l'ANSA prima in Italia per affidabilità",
    summary: "È il nono anno di fila. ANSA.it secondo sito di news con TgCom24 online",
    body: "È il nono anno di fila. ANSA.it secondo sito di news con TgCom24 online",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/politica/2026/06/16/rapporto-reuters-lansa-prima-in-italia-per-affidabilita_7cf1623a-40ba-4816-afbb-42b5369cda39.html",
    time: "1 ora fa",
    pub_ts: 1781624573,
    tags: [],
  },
  {
    id: 6,
    cat: "politica-italiana",
    title: "Picierno: \"Ucciso Skrepetsky, aveva protestato contro padiglione russo a Venezia\"",
    summary: "La vicepresidente del Parlamento europeo: 'Serve una Rete europea per la protezione dei dissidenti e degli oppositori politici'",
    body: "La vicepresidente del Parlamento europeo: 'Serve una Rete europea per la protezione dei dissidenti e degli oppositori politici'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/06/16/picierno-sp-ucciso-skrepetsky-aveva-protestato-contro-padiglione-russo-a-venezia_6b267831-b079-49e1-b54b-8f9ec7c1ee50.html",
    time: "2 ore fa",
    pub_ts: 1781620985,
    tags: [],
  },
  {
    id: 7,
    cat: "politica-italiana",
    title: "Chiarimento tra Meloni e Trump, \"importante l'unità dell'Occidente\"",
    summary: "Primo \"utile scambio\" tra i due presidenti a margine del G7. Ci saranno \"altre occasioni\"",
    body: "Primo \"utile scambio\" tra i due presidenti a margine del G7. Ci saranno \"altre occasioni\"",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/politica/2026/06/16/chiarimento-tra-meloni-e-trump-importante-lunita-delloccidente_2294fe7f-29e3-412f-88a8-44f1887dad7b.html",
    time: "2 ore fa",
    pub_ts: 1781619403,
    tags: [],
  },
  {
    id: 8,
    cat: "politica-italiana",
    title: "Energia per il futuro, persone, infrastrutture e innovazione",
    summary: "Un focus con Legambiente, Mase, Terna ed Enel",
    body: "Un focus con Legambiente, Mase, Terna ed Enel",
    source: "ANSA",
    url: "https://www.ansa.it/ansa2030/notizie/energia_energie/2026/06/15/energia-per-il-futuro-persone-infrastrutture-e-innovazione_1de21da2-dc8a-4ed0-ba33-a5254bb5427e.html",
    time: "2 ore fa",
    pub_ts: 1781619355,
    tags: [],
  },
  {
    id: 9,
    cat: "geopolitica",
    title: "El Reino Unido investiga posibles disparos de una fragata rusa contra un yate británico",
    summary: "El buque ‘Almirante Grigorovich’ lanzó ráfagas de advertencia a menos de 500 metros de la embarcación de recreo, que navegaba cerca de la isla de Wight",
    body: "El Ministerio de Defensa del Reino Unido ha confirmado que investiga las posibles ráfagas de advertencia disparadas por una fragata rusa, la Almirante Grigorovich , a menos de 500 metros de un yate británico. El incidente ha tenido lugar este martes, a unas 20 millas de la isla de Wight, al sur del país. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-16/el-reino-unido-investiga-posibles-disparos-de-una-fragata-rusa-contra-un-yate-britanico.html",
    time: "13 min fa",
    pub_ts: 1781628968,
    tags: [],
  },
  {
    id: 10,
    cat: "geopolitica",
    title: "El FBI asegura que frustró planes para atacar la celebración del cumpleaños de Trump",
    summary: "Al menos cinco personas están detenidas como sospechosos de un complot para atentar con drones y francotiradores contra los asistentes al espectáculo de lucha en la Casa Blanca",
    body: "Las fuerzas de seguridad frustraron un ataque con drones y francotiradores planeado para el espectáculo de lucha celebrado el pasado domingo en la Casa Blanca con motivo del cumpleaños del presidente Donald Trump. Así lo reveló este martes el director del FBI, Kash Patel, quien en su cuenta de X publicó que varias personas habían sido detenidas después de que tuvieran conocimiento del complot el jueves pasado.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/us/2026-06-16/el-fbi-asegura-que-frustro-planes-para-atacar-la-celebracion-del-cumpleanos-de-trump.html",
    time: "13 min fa",
    pub_ts: 1781628935,
    tags: [],
  },
  {
    id: 11,
    cat: "geopolitica",
    title: "UK investigating reports Russian warship fired warning shots near yacht in English Channel",
    summary: "BBC News understands the yacht had drifted towards the Admiral Grigorovich, a Russian frigate which has been operating in the Channel.",
    body: "BBC News understands the yacht had drifted towards the Admiral Grigorovich, a Russian frigate which has been operating in the Channel.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/c20yzm84r7lo?at_medium=RSS&at_campaign=rss",
    time: "30 min fa",
    pub_ts: 1781627935,
    tags: [],
  },
  {
    id: 12,
    cat: "geopolitica",
    title: "Fragile quiet in Lebanon as US-Iran truce leaves unanswered questions",
    summary: "Many Lebanese remain doubtful that the agreement could finally mean the end of the fighting between Israel and Hezbollah.",
    body: "Many Lebanese remain doubtful that the agreement could finally mean the end of the fighting between Israel and Hezbollah.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cvgepl5gdp1o?at_medium=RSS&at_campaign=rss",
    time: "48 min fa",
    pub_ts: 1781626833,
    tags: [],
  },
  {
    id: 13,
    cat: "geopolitica",
    title: "FBI thwarted plot targeting White House UFC event, Patel says",
    summary: "In newly unsealed court documents, the government alleges that the plan would have used drones. The FBI boss says multiple suspects are in custody.",
    body: "In newly unsealed court documents, the government alleges that the plan would have used drones. The FBI boss says multiple suspects are in custody.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cqx10xlje1lo?at_medium=RSS&at_campaign=rss",
    time: "58 min fa",
    pub_ts: 1781626277,
    tags: [],
  },
  {
    id: 14,
    cat: "geopolitica",
    title: "Kiko Rivera estalla contra su exmujer, Irene Rosales, por protagonizar una irónica campaña de publicidad: “La vida que tienes es gracias a haberte comido un Kiko”",
    summary: "El hijo de Isabel Pantoja y DJ critica en sus redes sociales que la madre de dos de sus hijas se haya prestado a un anuncio de Grefusa con alusiones veladas a él",
    body: "“Un mix con un mal kiko es un mal mix”, dice el claim de la nueva campaña publicitaria de Grefusa, expuesta en una enorme lona que ocupa la fachada de un edificio en pleno centro de Madrid y compartida en sus redes sociales . El eslogan de la compañía española de snacks y frutos secos no llamaría demasiado la atención si no fuera porque quien posa junto al texto sosteniendo un kiko (o maíz tostado) es Irene Rosales (Gines, 35 años), la exmujer de Kiko Rivera (Sevilla, 42 años).\n\n“Elige Grefusa mix, elige el mejor kiko”, remata la publicidad, que ha conseguido exactamente lo que se proponía: volverse viral y, de paso, molestar al aludido. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/gente/2026-06-16/kiko-rivera-estalla-contra-su-exmujer-irene-rosales-por-protagonizar-una-ironica-campana-de-publicidad-la-vida-que-tienes-es-gracias-a-haberte-comido-un-kiko.html",
    time: "1 ora fa",
    pub_ts: 1781625829,
    tags: [],
  },
  {
    id: 15,
    cat: "geopolitica",
    title: "Tehran selling deal with US as victory – but for Iranians it was necessity",
    summary: "For many Iranians, the question is not whether the deal means victory, but whether it lowers prices and reduces fear of another war.",
    body: "For many Iranians, the question is not whether the deal means victory, but whether it lowers prices and reduces fear of another war.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cn4rwzxvl8ko?at_medium=RSS&at_campaign=rss",
    time: "1 ora fa",
    pub_ts: 1781623884,
    tags: [],
  },
  {
    id: 16,
    cat: "geopolitica",
    title: "El juez Peinado ya rechazó en 2024 quitar el pasaporte a Begoña Gómez y el Gobierno dice que “no se entendería” que se lo retirase ahora",
    summary: "El magistrado tiene esta opción sobre la mesa tras solicitárselo la acusación popular, liderada por Hazte Oír",
    body: "Desde hace meses, el Gobierno intenta pasar de puntillas por la catarata de investigaciones judiciales y procesos que afectan tanto al PSOE como a la propia familia de Pedro Sánchez, pero suele hacer una excepción con todo lo que tiene que ver con el juez Juan Carlos Peinado y la imputación de Begoña Gómez. Sánchez se llegó a querellar contra el magistrado por prevaricación y su instrucción ha sido criticada con palabras muy gruesas por varias personas de su confianza.\n\nCuando los miembros del Gobierno dicen que “hay jueces que hacen política” están refiriéndose claramente a él, según fuentes de La Moncloa. Por eso, la portavoz del Ejecutivo, Elma Saiz, se ha pronunciado de forma directa este martes ante la posibilidad de que Peinado decida retirar el pasaporte a la esposa del presidente: “Es una medida que no se entendería”. El magistrado ya rechazó hacerlo en noviembre de 2024, pero ahora vuelve a tener la opción sobre la mesa.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-16/el-juez-peinado-ya-rechazo-en-2024-quitar-el-pasaporte-a-begona-gomez-y-el-gobierno-dice-que-no-se-entenderia-que-se-le-retirase-ahora.html",
    time: "1 ora fa",
    pub_ts: 1781623238,
    tags: [],
  },
  {
    id: 17,
    cat: "geopolitica",
    title: "Venezuela signs deal with US energy giant to rebuild power grid",
    summary: "The deal with General Electric is the latest sign of co-operation between US firms and Venezuela's interim government.",
    body: "The deal with General Electric is the latest sign of co-operation between US firms and Venezuela's interim government.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/c0jyzpv52yyo?at_medium=RSS&at_campaign=rss",
    time: "1 ora fa",
    pub_ts: 1781623192,
    tags: [],
  },
  {
    id: 18,
    cat: "geopolitica",
    title: "El juez ordena detener a Mouliaá por no comparecer por la querella que Errejón le interpuso por calumnias",
    summary: "La actriz alegó que no podía acudir a la citación del lunes porque estaba en el extranjero por trabajo",
    body: "El juez Arturo Zamarriego ha dado un paso adelante y ha ordenado detener a la actriz Elisa Mouliaá tras dejarle plantado por tercera vez este lunes y no acudir a declarar por la querella que Íñigo Errejón le interpuso a finales de 2025 por un presunto delito de difamación y calumnias. Este es un capítulo más del caso Errejón , que comenzó hace más de un año y medio, cuando Mouliaá denunció al exdiputado por agresión sexual durante una fiesta en 2021.\n\nDesde entonces, ambos se han entrecruzado acusaciones y querellas. Una de ellas, interpuesta por Errejón al considerar que la artista le había acusado públicamente de manipular a dos testigos de la fiesta donde presuntamente el expolítico la agredió, es la que instruye Zamarriego en el Juzgado de Instrucción número 9 de Madrid. Mouliaá se encuentra en Dubái (Emiratos Árabes) por motivos laborales, según anunció hace varios días en sus redes sociales.\n\nLa orden dictada por el juez contempla su detención una vez regrese a territorio español. Preguntada por este diario, la defensa de la actriz asegura que la noticia “ha salido en prensa antes que repartirla a los procuradores”. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-16/el-juez-decreta-la-detencion-de-mouliaa-por-no-comparecer-por-la-querella-de-errejon.html",
    time: "1 ora fa",
    pub_ts: 1781623176,
    tags: [],
  },
  {
    id: 19,
    cat: "geopolitica",
    title: "La princesa Leonor visita Teror, en Gran Canaria, durante su viaje de fin de curso como alférez",
    summary: "La heredera al trono, que estará en la isla hasta el próximo viernes, ha compartido junto a sus compañeros de la Academia General del Aire y del Espacio un recorrido por la localidad, incluida una tradicional visita a la basílica de la Virgen del Pino",
    body: "Tras el último año formativo como parte de la 78ª promoción de la Academia General del Aire y del Espacio (AGA) — el último de sus tres años de formación militar —, Leonor de Borbón disfruta ahora de cierto tiempo de ocio. Desde el pasado domingo 14 de junio y hasta el próximo viernes 19, la princesa se encuentra en la isla de Gran Canaria junto a sus compañeros de promoción. Este martes 16 de junio, la heredera de la Corona y el resto de alumnos han llegado al municipio de Teror, donde han sido recibidos por las autoridades, en lo que ya es parte de una tradición por la cual las distintas promociones de la academia militar visitan esta localidad canaria como viaje de fin de curso.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/gente/2026-06-16/la-princesa-leonor-visita-teror-en-gran-canaria-durante-su-viaje-de-fin-de-curso-como-alferez.html",
    time: "2 ore fa",
    pub_ts: 1781622385,
    tags: [],
  },
  {
    id: 20,
    cat: "geopolitica",
    title: "Sheinbaum espera reunirse con el rey Felipe VI por el partido del Mundial entre España y Uruguay",
    summary: "La Secretaría de Relaciones Exteriores de México trabaja con la Cancillería española para coordinar el encuentro a propósito del juego del próximo 26 de junio",
    body: "El esperado encuentro entre la presidenta Claudia Sheinbaum y el rey Felipe VI de España podría confirmarse en los próximos días. La mandataria ha asegurado este martes en rueda de prensa matutina que espera poder reunirse con el monarca en Ciudad de México a propósito del partido de fútbol que disputarán España y Uruguay el próximo 26 de junio en la fase de grupos y al que el rey está invitado. “Relaciones Exteriores está viendo con la Cancillería de España y con la representación del jefe del Estado español.\n\nYo creo que mañana o pasado les podemos informar”, ha apuntado Sheinbaum. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/mexico/2026-06-16/sheinbaum-espera-reunirse-con-el-rey-felipe-vi-en-el-partido-del-mundial-entre-espana-y-uruguay.html",
    time: "2 ore fa",
    pub_ts: 1781622227,
    tags: [],
  },
  {
    id: 21,
    cat: "geopolitica",
    title: "Muere Ece Irtem, actriz turca de series como ‘Pecado original’, un día después de su 35° cumpleaños",
    summary: "El abogado de la intérprete, Uğur Gökkoyun, ha explicado en un comunicado que sospechan que falleció de un ataque al corazón",
    body: "La actriz turca Ece Irtem ha muerto este lunes, un día después de cumplir los 35 años, en su casa de Estambul, ha explicado su abogado Uğur Gökkoyun en un comunicado. El fallecimiento de la intérprete, conocida por teleseries emitidas en España como Pecado original (Antena 3), Amor sin límite (Nova) y Me robó mi vida y Mundos opuestos (ambas en Divinity) , ha provocado la reacción de algunos compañeros de reparto, como el conocido Can Yaman .\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/television/series/2026-06-16/muere-ece-irtem-actriz-turca-de-series-como-pecado-original-un-dia-despues-de-su-35-cumpleanos.html",
    time: "2 ore fa",
    pub_ts: 1781622129,
    tags: [],
  },
  {
    id: 22,
    cat: "geopolitica",
    title: "Un hombre mata al logopeda de su hijo en Valencia y al entregarse a la policía dice que estaba abusando del niño",
    summary: "Varias madres de pacientes expresan su estupor y aseguran que nunca han tenido problemas con el terapeuta. La investigación no descarta ninguna hipótesis, pese a la versión del móvil dada por el detenido",
    body: "La Policía Nacional ha detenido el lunes por la tarde en Burjassot (Valencia) a un hombre de 24 años como presunto autor de un delito de homicidio tras haber matado a otro en una clínica privada de logopedia en Valencia. Junto al cadáver de la víctima, de 32 años, los agentes han hallado una navaja de 15 centímetros. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/comunidad-valenciana/2026-06-16/detenido-un-hombre-por-matar-al-logopeda-de-su-hijo-en-valencia-al-creer-que-estaba-abusando-del-nino.html",
    time: "2 ore fa",
    pub_ts: 1781621426,
    tags: [],
  },
  {
    id: 23,
    cat: "geopolitica",
    title: "Muere tiroteado en Polonia Semión Skrepetski, artista ruso crítico con Putin",
    summary: "Un pistolero mató de varios disparos al pintor disidente, horas después de que denunciara amenazas de los seguidores del presidente checheno",
    body: "Un pistolero mató al artista disidente ruso Semión Skrepetski a plena luz del día este lunes en un pueblo de Polonia. El pintor, de 44 años, era una figura conocida de la oposición rusa. Sus grotescos retratos ridiculizaban a la élite rusa, en especial a su presidente, Vladímir Putin , y a sus aliados, especialmente al jefe de Chechenia, Ramzán Kadírov , y al dirigente bielorruso, Aleksandr Lukashenko , aunque tampoco dejaba títere con cabeza entre la disidencia y las autoridades ucranias.\n\nSu asesino lo tiroteó en Biała Podlaska, a 40 kilómetros de la frontera con Bielorrusia. Los investigadores manejan como hipótesis principal “una ejecución política”, según ha revelado el diario Zet . Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-16/muere-tiroteado-en-polonia-el-artista-ruso-critico-con-putin-semion-skrepetski.html",
    time: "2 ore fa",
    pub_ts: 1781621116,
    tags: [],
  },
  {
    id: 24,
    cat: "geopolitica",
    title: "Submarinistas de la Guardia Civil buscan al menor desaparecido en la bahía de Roses",
    summary: "Las diferentes versiones y la falta de certeza en las declaraciones de los implicados dificultan la investigación",
    body: "Media docena de submarinistas del Grupo Especial de Actividades Subacuáticas (GEAS) de la Guardia Civil con base en l’Estartit (Girona) y Barcelona están efectuando inmersiones desde este lunes en varios puntos de la bahía de Roses (Alt Empordà) para intentar encontrar algún indicio que permita localizar a Adam H.B., el menor de 16 años desaparecido el miércoles pasado cuando conducía una moto de agua.\n\nSalvamento Marítimo y el resto de equipos de emergencias pasaron a hacer búsqueda pasiva el fin de semana ante la imposibilidad de encontrarlo con vida, en el caso de que estuviera en el agua. Los buzos concentran sus esfuerzos en diversas zonas donde testigos sitúan a los menores, sin embargo, el hecho de que ni desde la empresa ni la decena de menores que iban en las motos estén dando información veraz a los investigadores de Policía Judicial de la Comandancia de la Guardia Civil de Girona que investigan las “extrañas” circunstancias de la desaparición dificulta la resolución del caso.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/catalunya/2026-06-16/submarinistas-de-la-guardia-civil-buscan-al-menor-desaparecido-en-la-bahia-de-roses.html",
    time: "2 ore fa",
    pub_ts: 1781620981,
    tags: [],
  },
  {
    id: 25,
    cat: "geopolitica",
    title: "La muerte del fútbol en 2026",
    summary: "Las pausas de hidratación americanizan un juego cuya esencia y cultura se basa en fomentar la continuidad",
    body: "El fútbol se muere ante el silencio sepulcral de los jugadores, también de la mayoría de entrenadores, la complacencia de la prensa y el visto bueno de los aficionados que todavía pueden ir al campo, espectadores que a menudo poco tienen que ver con los seguidores de toda la vida, especialmente en Europa y Latinoamérica. No es que el fútbol vaya a desaparecer, sino que cada vez se juega de manera diferente, más americanizada que nunca , como si fuera un deporte susceptible de adaptación a las reglas del béisbol, la NBA o la NFL.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-06-16/la-muerte-del-futbol-en-2026.html",
    time: "2 ore fa",
    pub_ts: 1781620771,
    tags: [],
  },
  {
    id: 26,
    cat: "geopolitica",
    title: "Somaliland opens Jerusalem embassy after Israel's recognition of its independence",
    summary: "The move comes six months after Israel became the first country to recognise the breakaway East African state.",
    body: "The move comes six months after Israel became the first country to recognise the breakaway East African state.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cj4gn4d54y0o?at_medium=RSS&at_campaign=rss",
    time: "2 ore fa",
    pub_ts: 1781620479,
    tags: [],
  },
  {
    id: 27,
    cat: "geopolitica",
    title: "La CEOE sale en tromba contra el absentismo: pide que la Seguridad Social costee las bajas y las sustituciones desde el primer día",
    summary: "Una veintena de líderes patronales proponen medidas como la limitación de los complementos o la recuperación del despido por absentismo",
    body: "“Si un día en un bar o un restaurante te falta el jefe de cocina, solo te queda rezar o cerrar”. Así ha resumido este martes el problema del absentismo en las empresas el presidente de la patronal de la hostelería, José Luis Álvarez Almeida, durante una jornada organizada por la patronal CEOE en la que más de una veintena de máximos líderes empresariales de los principales sectores y territorios han lanzado una llamada de atención a la sociedad: “El crecimiento del absentismo por las bajas laborales es un problema de país y hay que hacer algo”.\n\nEsta ha sido la idea más repetida de esta jornada, en la que el presidente de la patronal, Antonio Garamendi, ha reclamado que, mientras no se tomen medidas para atajar las crecientes ausencias de los trabajadores a su puesto de trabajo, la Seguridad Social debería costear las cotizaciones y los salarios del trabajador los primeros 15 días de la baja, así como las cotizaciones de los contratos que se hagan para sustituir a un empleado de baja.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/economia/2026-06-16/la-ceoe-sale-en-tromba-contra-el-absentismo-pide-que-la-seguridad-social-costee-las-bajas-desde-el-primer-dia-y-las-sustituciones.html",
    time: "3 ore fa",
    pub_ts: 1781617830,
    tags: [],
  },
  {
    id: 28,
    cat: "geopolitica",
    title: "Trump eleva la presión sobre Netanyahu y Putin",
    summary: "Washington muestra disposición a reactivar las sanciones petroleras contra Rusia y plantea que Siria se ocupe de Hezbolá con una rotunda crítica a Israel",
    body: "El presidente de Estados Unidos, Donald Trump, ha enviado este martes desde la cumbre del G-7 en Évian-les-Bains dos mensajes de presión hacia Benjamín Netanyahu y Vladímir Putin. El mandatario estadounidense pidió al primer ministro israelí “ser más responsable con Líbano”, criticó sus ataques contra el sur de la capital del país vecino y envió una señal inusual y algo críptica sugiriendo que sea Siria quien se ocupe de Hezbolá, la milicia libanesa contra la cual lucha Israel.\n\nPoco después, de cara al Kremlin, avisó de que está dispuesto a reactivar las sanciones energéticas que había suspendido por la tensión en los mercados causadas por su ataque contra Irán. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-16/trump-eleva-la-presion-sobre-netanyahu-y-putin.html",
    time: "3 ore fa",
    pub_ts: 1781617323,
    tags: [],
  },
  {
    id: 29,
    cat: "conflitti",
    title: "Qatar renews mediation efforts for regional stability after US-Iran deal",
    summary: "Qatar says it is working to prevent a return to war, following the signing of the MoU between the US and Iran.",
    body: "Qatar says it is working to prevent a return to war, following the signing of the MoU between the US and Iran.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/16/aje-onl-nf_qatar-renews-mediation-efforts-after-us-iran-deal-160626?traffic_source=rss",
    time: "18 min fa",
    pub_ts: 1781628679,
    tags: [],
  },
  {
    id: 30,
    cat: "conflitti",
    title: "Post-apartheid South Africa: 50 years after Soweto riots, what has changed?",
    summary: "Black students braved bullets to protest the discriminatory apartheid-era education policies.",
    body: "Black students braved bullets to protest the discriminatory apartheid-era education policies.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/post-apartheid-south-africa-50-years-after-soweto-riots-what-has-changed?traffic_source=rss",
    time: "24 min fa",
    pub_ts: 1781628331,
    tags: [],
  },
  {
    id: 31,
    cat: "conflitti",
    title: "Israel went to war with Iran, but Netanyahu may be the loser",
    summary: "Critics say PM Benjamin Netanyahu&#039;s Iran war strengthened Tehran, strained US ties, and left Israel weaker.",
    body: "Critics say PM Benjamin Netanyahu&#039;s Iran war strengthened Tehran, strained US ties, and left Israel weaker.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/israel-went-to-war-with-iran-netanyahu-may-be-loser?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1781625423,
    tags: [],
  },
  {
    id: 32,
    cat: "conflitti",
    title: "Optics of peace first, details later: The US-Iran 60-day challenge",
    summary: "Negotiators have yet to hold talks on key issues that have plagued US-Iran diplomacy for decades, say analysts.",
    body: "Negotiators have yet to hold talks on key issues that have plagued US-Iran diplomacy for decades, say analysts.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/features/2026/6/16/optics-of-peace-first-details-later-the-us-iran-60-day-challenge?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1781624395,
    tags: [],
  },
  {
    id: 33,
    cat: "conflitti",
    title: "From JCPOA exit to the 2026 deal: How US-Iran ties soured under Trump",
    summary: "Ties between the US and Iran have been strained through both of Donald Trump&#039;s terms as US president.",
    body: "Ties between the US and Iran have been strained through both of Donald Trump&#039;s terms as US president.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/from-jcpoa-exit-to-the-2026-deal-how-us-iran-ties-soured-under-trump?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1781623292,
    tags: [],
  },
  {
    id: 34,
    cat: "conflitti",
    title: "With Israel unleashed, there can be no peace in the Middle East",
    summary: "The US has long extended unconditional support for Israeli aggression. Now, it struggles to rein it in.",
    body: "The US has long extended unconditional support for Israeli aggression. Now, it struggles to rein it in.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/opinions/2026/6/16/with-israel-unleashed-there-can-be-no-peace-in-the-middle-east?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1781623248,
    tags: [],
  },
  {
    id: 35,
    cat: "conflitti",
    title: "FBI says it foiled ‘planned attacks’ targeting White House UFC event",
    summary: "At least five people are in custody in an alleged plot that included 23 people, according to US media reports.",
    body: "At least five people are in custody in an alleged plot that included 23 people, according to US media reports.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/fbi-says-it-foiled-planned-attacks-targeting-white-house-ufc-event?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1781621835,
    tags: [],
  },
  {
    id: 36,
    cat: "conflitti",
    title: "Gaza’s football fans follow World Cup matches despite hardships",
    summary: "Gaza’s football fans follow World Cup matches despite hardships.",
    body: "Gaza’s football fans follow World Cup matches despite hardships.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/16/gazas-football-fans-follow-world-cup-matches-despite-hardships?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1781620263,
    tags: [],
  },
  {
    id: 37,
    cat: "conflitti",
    title: "Hardliners and moderates: What do Iran’s factions think of deal with US?",
    summary: "Factional divisions in Iran remain as leaders debate the implementation of deal with the US, amid fears of capitulation.",
    body: "Factional divisions in Iran remain as leaders debate the implementation of deal with the US, amid fears of capitulation.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/hardliners-and-moderates-what-do-irans-factions-think-of-deal-with-us?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1781619223,
    tags: [],
  },
  {
    id: 38,
    cat: "conflitti",
    title: "‘Justice prevailed’: Is the Netherlands shifting its stance on Israel?",
    summary: "A court case, a Eurovision boycott and Gaza polling prompt Dutch debate over Palestine and Israel ties.",
    body: "A court case, a Eurovision boycott and Gaza polling prompt Dutch debate over Palestine and Israel ties.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/justice-prevailed-is-the-netherlands-shifting-its-stance-on-israel?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1781619053,
    tags: [],
  },
  {
    id: 39,
    cat: "conflitti",
    title: "Lebanese rush back to their devastated homes in south after US-Iran deal",
    summary: "Thousands return to their homes following Iran-US deal despite Israel saying it won&#039;t end its occupation of Lebanon.",
    body: "Thousands return to their homes following Iran-US deal despite Israel saying it won&#039;t end its occupation of Lebanon.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/features/2026/6/16/lebanese-rush-back-to-their-devastated-homes-in-south-after-us-iran-deal?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1781618197,
    tags: [],
  },
  {
    id: 40,
    cat: "conflitti",
    title: "Iran coach says team ‘oppressed’ by travel chaos after World Cup NZ draw",
    summary: "Amir Ghalenoei made the comment after Iran were forced to leave the US for their Mexico base after their opening match.",
    body: "Amir Ghalenoei made the comment after Iran were forced to leave the US for their Mexico base after their opening match.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/sports/2026/6/16/iran-coach-says-team-oppressed-by-travel-chaos-after-world-cup-nz-draw?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1781617978,
    tags: [],
  },
  {
    id: 41,
    cat: "conflitti",
    title: "Israeli court rules to keep prominent Palestinian doctor in detention",
    summary: "The Palestinian doctor demanded his release last week after months of imprisonment and visible signs of torture.",
    body: "The Palestinian doctor demanded his release last week after months of imprisonment and visible signs of torture.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/israeli-court-rules-to-keep-prominent-palestinian-doctor-in-detention?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1781616260,
    tags: [],
  },
  {
    id: 42,
    cat: "conflitti",
    title: "‘There’s divergence between US and Israeli objectives in the region’",
    summary: "‘There’s divergence between US and Israeli objectives in the region’",
    body: "‘There’s divergence between US and Israeli objectives in the region’",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/16/theres-divergence-between-us-and-israeli-objectives-in-the?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1781615356,
    tags: [],
  },
  {
    id: 43,
    cat: "conflitti",
    title: "Geneva to host Iran-US deal event: What other pacts have been signed there?",
    summary: "Geneva is widely recognised as the &#039;Peace Capital&#039; of the world.",
    body: "Geneva is widely recognised as the &#039;Peace Capital&#039; of the world.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/geneva-to-host-iran-us-deal-event-what-other-pacts-have-been-signed-there?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1781615144,
    tags: [],
  },
  {
    id: 44,
    cat: "conflitti",
    title: "Red Cross warns Ebola outbreak in DRC not yet peaked, could last a year",
    summary: "The Red Cross says it is &#039;very difficult&#039; to know the extent at which the epidemic is spreading.",
    body: "The Red Cross says it is &#039;very difficult&#039; to know the extent at which the epidemic is spreading.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/16/red-cross-warns-ebola-outbreak-in-drc-not-yet-peaked-could-last-a-year?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1781613031,
    tags: [],
  },
  {
    id: 45,
    cat: "ai",
    title: "Self-driving tech supplier Mobileye wants to be part of the robotaxi revolution — again",
    summary: "The Israeli tech company and Intel subsidiary said it will launch its own robotaxi service in a U.S. city in 2027.",
    body: "The Israeli tech company and Intel subsidiary said it will launch its own robotaxi service in a U.S. city in 2027.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/self-driving-tech-supplier-mobileye-wants-to-be-part-of-the-robotaxi-revolution-again/",
    time: "2 min fa",
    pub_ts: 1781629612,
    tags: [],
  },
  {
    id: 46,
    cat: "ai",
    title: "Apple 2027 rumors: AirPods with cameras for AI and the second folding iPhone",
    summary: "Now that we're clear of WWDC and all of the AI-powered features coming to Apple's platforms, Bloomberg reporter Mark Gurman has more details about rumored new hardware like the camera-equipped AirPods he'd previously written about. He says they are currently on schedule for a late 2027 launch, and that while we're checking out beta releases [&#8230;]",
    body: "AirPods Pro 3 shown with an iPhone and live translation features | Photo by Amelia Holowaty Krales / The Verge Now that we're clear of WWDC and all of the AI-powered features coming to Apple's platforms, Bloomberg reporter Mark Gurman has more details about rumored new hardware like the camera-equipped AirPods he'd previously written about . He says they are currently on schedule for a late 2027 launch, and that while we're checking out beta releases for this fall's iOS 27 update, the new earbuds are internally being tested with next year's update, iOS 28.\n\nWith cameras mounted in their stems and lights to indicate when data is being uploaded to the cloud, they could give the upgraded version of Siri \"visual context\" about your surroundings, before …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/950826/apple-airpod-camera-ai-foldable-iphone-rumor",
    time: "5 min fa",
    pub_ts: 1781629445,
    tags: [],
  },
  {
    id: 47,
    cat: "ai",
    title: "Qualcomm’s latest chip hints that more powerful smart glasses could be on the way",
    summary: "Smart glasses are still a nascent category, but chipmaker Qualcomm is hard at work upgrading the silicon to power the next wave of XR devices: the Snapdragon Reality Elite. Although Qualcomm is announcing the chip today at Augmented World Expo, we've technically already gotten a hands-on with a device powered by the new chip at [&#8230;]",
    body: "Smart glasses are still a nascent category, but chipmaker Qualcomm is hard at work upgrading the silicon to power the next wave of XR devices: the Snapdragon Reality Elite. Although Qualcomm is announcing the chip today at Augmented World Expo, we've technically already gotten a hands-on with a device powered by the new chip at last month's Google I/O: the forthcoming Aura glasses for Android XR.\n\nAt the time, Xreal and Google were coy about the processor upgrades to the long-awaited spectacles. Turns out, it was the Reality Elite. Spec-wise, the new chip focuses on across-the-board performance upgrades. The GPU gets a 60 percent bump, the …",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/950229/qualcomm-snapdragon-reality-elite-xr-smart-glasses-wearables",
    time: "9 min fa",
    pub_ts: 1781629200,
    tags: [],
  },
  {
    id: 48,
    cat: "ai",
    title: "The Google / Xreal Aura XR glasses are now available to preorder",
    summary: "The Project Aura glasses collaboration between Xreal and Google is now one step closer to being something you can buy. Reservations for the second Android XR device, now dubbed the Xreal Aura, are available for $99 starting today, with a full launch in the US, UK, Japan, Canada, and South Korea expected sometime this Fall. [&#8230;]",
    body: "There’s still no word on the final launch price, however. | Image by Xreal The Project Aura glasses collaboration between Xreal and Google is now one step closer to being something you can buy. Reservations for the second Android XR device , now dubbed the Xreal Aura, are available for $99 starting today, with a full launch in the US, UK, Japan, Canada, and South Korea expected sometime this Fall.\n\nThe Xreal Aura follows Google's first Android-powered XR device, the Samsung Galaxy XR headset , which launched at $1,799 in October 2025. We still don't have a full price for the Aura - which Google has previously described as \"a headset masquerading as glasses\" - but Best Buy will be the first in-store retail partner whe …",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/950597/xreal-google-aura-xr-glasses-deposit-scheme",
    time: "9 min fa",
    pub_ts: 1781629200,
    tags: [],
  },
  {
    id: 49,
    cat: "ai",
    title: "Snap finally debuts its long awaited AR glasses, Specs, and, oof, they aren’t cheap",
    summary: "After many years, Snap is finally launching its next consumer-focused smart glasses line.",
    body: "After many years, Snap is finally launching its next consumer-focused smart glasses line.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/snap-finally-debuts-its-long-awaited-ar-glasses-specs-and-oof-they-arent-cheap/",
    time: "9 min fa",
    pub_ts: 1781629200,
    tags: [],
  },
  {
    id: 50,
    cat: "ai",
    title: "Snap&#8217;s first consumer AR glasses are coming this fall for $2,195",
    summary: "Snap is finally launching augmented glasses for the public. Specs, which Snap describes as \"a wearable computer built into see-through augmented reality glasses,\" will cost $2,195. You can preorder a pair of Specs now at specs.com with a $200 refundable deposit, and Snap says they're expected to ship \"this fall\" in the US, UK, and [&#8230;]",
    body: "Snap is finally launching augmented glasses for the public. Specs, which Snap describes as \"a wearable computer built into see-through augmented reality glasses,\" will cost $2,195. You can preorder a pair of Specs now at specs.com with a $200 refundable deposit, and Snap says they're expected to ship \"this fall\" in the US, UK, and France. This is a big moment for Snap: The company made a big entry into smart glasses with its original Spectacles in 2016 , and the company has been toiling away on nonpublic AR versions of Spectacles over the past few years.\n\nCEO Evan Spiegel promised the company would launch consumer AR glasses in 2026 and even …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/950492/snap-specs-ar-glasses-launch-date-preorder",
    time: "19 min fa",
    pub_ts: 1781628600,
    tags: [],
  },
  {
    id: 51,
    cat: "ai",
    title: "Sixty percent of U.S. consumers say ‘AI’ in brand messaging is a turnoff, survey finds",
    summary: "WordPress VIP’s latest survey suggests consumers are wary of AI-generated answers even as companies increasingly view AI search as an important referral channel.",
    body: "WordPress VIP’s latest survey suggests consumers are wary of AI-generated answers even as companies increasingly view AI search as an important referral channel.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/sixty-percent-of-u-s-consumers-say-ai-in-brand-messaging-is-a-turnoff-survey-finds/",
    time: "19 min fa",
    pub_ts: 1781628584,
    tags: [],
  },
  {
    id: 52,
    cat: "ai",
    title: "Everything you need to know about Prime Day 2026",
    summary: "Amazon Prime Day 2026 is getting closer, and it’s possible you might have some questions about the sale. When does it start? Why is it in June instead of July? And, most importantly, when will the deals go live? We have concrete answers to those questions, and we’ll have a lot more Prime Day coverage [&#8230;]",
    body: "Amazon Prime Day 2026 is getting closer, and it’s possible you might have some questions about the sale. When does it start? Why is it in June instead of July? And, most importantly, when will the deals go live? We have concrete answers to those questions, and we’ll have a lot more Prime Day coverage coming soon as Amazon rolls out more deals. When does Prime Day start? Amazon Prime Day 2026 officially starts on June 23rd, 2026 at 12:01AM PT, and ends on June 27, 2026 at 12:01AM PT.\n\nSome items will stay discounted for the entire period, or at least for as long as they remain in stock, while others will only run for a shorter chunk of the four day sale. In its article about Prime Day 2026 timing, Amazon noted that special deals will go live at 12AM, 8AM, and 1PM PT each day throughout the sale. Why is Prime Day in June this year? While there have been exceptions, Prime Day has historically occurred in July.\n\nSo, what’s up with the recent change? Amazon’s Jamil Ghani told Reuters that the decision came down to some big events overlapping with its usual July launch. &#8220;This year, we have the (FIFA) World Cup [&#8230;] We&#8217;ve got also the 250th anniversary of U.S. independence, and so we thought ​this week (beginning June 22) was the best week for us to hold Prime Day,&#8221; Ghani said. When do early Prime Day deals start? The rollout of early deals is already underway , and Amazon is highlighting deals on household essentials and Amazon devices like Kindle accessories and Ring cameras.\n\nIt’s safe to assume that there will be several dozen deals available ahead of Prime Day, and we’ll be bringing them to you, so stay tuned. Do I need to be a Prime member to save? While there are likely to be some deals available to all shoppers, Amazon Prime members will have exclusive access to many discounts. If you haven’t signed up for Prime before, you can claim a 30 day free trial. &nbsp; Young adults and students can claim six months of Prime membership for free, after which you’ll be charged $7.49 per month if you want to continue (or $69 per year if you want to pay annually) with some account sharing limitations.\n\nPeople receiving government assistance can use Amazon Access for discounts on specific products, including a Prime membership. Are other retailers offering similar deals? Other retailers are likely to drop prices through Prime Day to meet or at least come closer to Amazon. Walmart is hosting a competing sale from June 22nd, 2026 at 12:01AM ET until June 28th, 2026 at 11:59PM ET both online and in stores, with early access for Walmart Plus members.\n\nSimilarly, Target has Circle Deal Days starting on June 23rd and running until June 26th for anyone with a free Target Circle account. We’ll keep an eye out for deals wherever we can find them, and let you know if someone else beats Amazon’s price, or launches a similar sale. Do any retailers offer price matching for Prime Day? Currently, no major retailers offer price matching for Prime Day deals on Amazon.\n\nBest Buy typically offers price matching for Amazon, but most Prime Day deals won’t qualify because they’re either advertised as limited quantity, or require a Prime membership. Neither Target nor Walmart offer price matching for competitors. How can I know that Prime Day deals are actually good? There’s a deep trove of products that we’re hoping to see discounts on during Prime Day, and we use tools like CamelCamelCamel to track prices.\n\nWhen the markdowns match or exceed ones we’ve seen before on tech we like, we’ll tell you about it. Of course, you can track price history on items this way, too. Amazon makes that easy with its own “Alexa for Shopping” price tracker (accessible by clicking “Price history” next to the item’s price), which is great for quick checks, but in our experience it doesn’t show up on every product, and it seems to deliver just up to one year of price history.\n\nOn the other hand, CamelCamelCamel lets you see pricing data going back for the entire duration of the product’s availability, which is nice for researching slightly older products. Do prices stay the same through Prime Day? Generally, yes, though not always. Once a product is discounted for Prime Day, it usually sticks to that price for the duration of the sale. However, there will likely be some instances — Lightning Deals, for example — when deeper discounts might be available for a limited time.\n\nWhat are the best deals during Prime Day? Well, that’s something we’ll be able to tell you a lot more about in the coming weeks. But we always look forward to deals on Apple products, like AirPods, as well as other earbuds and headphones. Video games, TVs, monitors, and computer peripherals also typically see big discounts. Pretty much anything you’d likely want to buy during the Black Friday pre-holiday period should get some kind of discount during Amazon’s June event.",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/945942/prime-day-2026-frequently-asked-questions",
    time: "37 min fa",
    pub_ts: 1781627500,
    tags: [],
  },
  {
    id: 53,
    cat: "ai",
    title: "Nothing&#8217;s Ear (a), our favorite budget earbuds, are cheaper than ever ahead of Prime Day",
    summary: "If you&#8217;re looking for a cheap Father&#8217;s Day gift that delivers more than you&#8217;d expect for the price, Nothing’s Ear (a) are a good option. The wireless earbuds are currently on sale as part of a larger early Prime Day sales event, making them an even better value than usual. Right now, you can buy [&#8230;]",
    body: "The yellow pair are on sale too. | Photo by Chris Welch / The Verge If you&#8217;re looking for a cheap Father&#8217;s Day gift that delivers more than you&#8217;d expect for the price, Nothing’s Ear (a) are a good option. The wireless earbuds are currently on sale as part of a larger early Prime Day sales event, making them an even better value than usual. Right now, you can buy them at Amazon in black complete with Nothing’s slick translucent charging case for $53.20 ($47 off), which marks a new all-time low.\n\nYou can also buy them in yellow ( Amazon , Nothing ) and white ( Amazon , Nothing ) for just $3 more. Nothing Ear (a) Where to Buy: $99 $53.2 at Amazon (black) $99 $56 at Amazon (yellow) $99 $56 at Amazon (white) The Nothing Ear (a) are one of our favorite affordable pairs of wireless earbuds , and for good reason. They offer a surprising number of features for their price, including a low-latency gaming mode that helps reduce lag while playing games.\n\nNothing phone owners can also access ChatGPT with a quick pinch gesture, while support for multipoint Bluetooth pairing lets you stay connected to two devices at once. The earbuds also work with Android Fast Pair and Microsoft Swift Pair, making setup quick and painless. More importantly, they nail the essentials. The earbuds deliver expressive, enjoyable sound, while offering noise cancellation to cut down on distractions.\n\nNothing has also improved voice call performance with AI-powered voice isolation, which helps your voice come through more clearly in noisy environments. Three sizes of silicone ear tips are included to help you find a secure fit, while their IP54 rating provides protection against sweat and light rain. Battery life is solid, too, lasting up to eight hours before you need to recharge. Read our hands-on impressions of the Nothing Ear (a) More good deals from Nothing’s sale: Nothing CMF Buds 2A The CMF Buds 2A deliver decent sound and noise cancellation.\n\nThey also offer useful extras like customizable EQ settings, multipoint connectivity, and IP54 water and dust resistance. Where to Buy: $49 $29 at Amazon (black) $49 $29 at Amazon (white) $49 $29 at Amazon (orange) Nothing Headphone A Nothing’s second over-ear headphones may not offer everything found on the pricier Nothing Headphone 1, but you do get physical controls, good sound, and more than five days of battery life per charge.\n\nTheir design is also a bit more discreet, for better or worse. Read our review . Where to Buy: $199 $151.05 at Amazon (black) $199 $151.05 at Amazon (white) $199 $151.05 at Amazon (pink)",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/950756/nothing-ear-a-early-amazon-prime-day-deal-sale",
    time: "59 min fa",
    pub_ts: 1781626227,
    tags: [],
  },
  {
    id: 54,
    cat: "ai",
    title: "SpaceX is public: Everything you need to know post-IPO",
    summary: "TechCrunch has followed SpaceX's start, struggles, and successes from the early days. And we're here for what happens next too. This package of SpaceX IPO coverage includes who stands to win (and maybe some who won't), pre-IPO deals, and what's tucked inside its S-1 registration document.",
    body: "TechCrunch has followed SpaceX's start, struggles, and successes from the early days. And we're here for what happens next too. This package of SpaceX IPO coverage includes who stands to win (and maybe some who won't), pre-IPO deals, and what's tucked inside its S-1 registration document.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/spacex-is-public-everything-you-need-to-know-post-ipo/",
    time: "1 ora fa",
    pub_ts: 1781625192,
    tags: [],
  },
  {
    id: 55,
    cat: "ai",
    title: "India orders temporary ban on Telegram over exam fraud concerns",
    summary: "The restrictions include a nationwide ban on Telegram until June 22 and a requirement to disable the app's message editing feature.",
    body: "The restrictions include a nationwide ban on Telegram until June 22 and a requirement to disable the app's message editing feature.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/india-temporarily-blocks-access-to-telegram-over-exam-fraud-concerns/",
    time: "1 ora fa",
    pub_ts: 1781624940,
    tags: [],
  },
  {
    id: 56,
    cat: "ai",
    title: "Payments startup Flutterwave hits $3.2B valuation, backed by Ripple",
    summary: "African payments infrastructure company Flutterwave has hit a new valuation and landed blockchain company Ripple as investor and partner.",
    body: "African payments infrastructure company Flutterwave has hit a new valuation and landed blockchain company Ripple as investor and partner.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/payments-startup-flutterwave-hits-3-2b-valuation-backed-by-ripple/",
    time: "1 ora fa",
    pub_ts: 1781624139,
    tags: [],
  },
  {
    id: 57,
    cat: "ai",
    title: "We now know how DJI’s dual camera Osmo Pocket 4P compares to Insta360’s",
    summary: "After a brief debut at the Cannes film festival last month, DJI announced all the details of its Osmo Pocket 4P stabilized camera today as part of its initial launch in China. While it doesn't match the 8K capabilities of the Insta360 Luna Ultra, the Pocket 4P features a new 1-inch sensor with improved dynamic [&#8230;]",
    body: "After a brief debut at the Cannes film festival last month , DJI announced all the details of its Osmo Pocket 4P stabilized camera today as part of its initial launch in China. While it doesn't match the 8K capabilities of the Insta360 Luna Ultra, the Pocket 4P features a new 1-inch sensor with improved dynamic range and impressive 4K slow-mo capabilities. The Pocket 4P is now available for preorder from DJI's Chinese website for &yen;3799, or around $562.\n\nThat's cheaper than Insta360's $769.99 Luna Ultra, however, a simple currency conversion doesn't accurately reflect what the Pocket 4P will be priced at globally. Like the single camera Pocket …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/950591/dji-osmo-pocket-4p-dual-gimbal-camera-baby-steadicam-4k-tracking",
    time: "1 ora fa",
    pub_ts: 1781623526,
    tags: [],
  },
  {
    id: 58,
    cat: "ai",
    title: "DOJ claims xAI’s unpermitted gas turbines are a matter of ‘national, economic, and energy security’",
    summary: "The Justice department says the Pentagon needs xAI to keep using its unpermitted gas turbines.",
    body: "The Justice department says the Pentagon needs xAI to keep using its unpermitted gas turbines.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/doj-claims-xais-unpermitted-gas-turbines-are-a-matter-of-national-economic-and-energy-security/",
    time: "2 ore fa",
    pub_ts: 1781622303,
    tags: [],
  },
  {
    id: 59,
    cat: "ai",
    title: "The Cybercab is the lightest, most efficient Tesla ever made",
    summary: "Against all odds, the Tesla Cybercab is in production. And while Elon Musk's company may not have a very coherent plan for the tiny, autonomous two-seater, it's still taking the necessary steps to certify the EV's legitimacy. As such, Tesla recently filed paperwork with the Environmental Protection Agency that reveal many of the Cybercab's specs, [&#8230;]",
    body: "Against all odds, the Tesla Cybercab is in production . And while Elon Musk's company may not have a very coherent plan for the tiny, autonomous two-seater, it's still taking the necessary steps to certify the EV's legitimacy. As such, Tesla recently filed paperwork with the Environmental Protection Agency that reveal many of the Cybercab's specs, including its weight, battery size, and preliminary range estimates.\n\nWhat these documents reveal is the lightest, most range efficient vehicle Tesla has ever produced - and quite possibly one of the most efficient EVs ever produced. The EPA filings confirm the Cybercab runs on a single front-mou …",
    source: "The Verge",
    url: "https://www.theverge.com/transportation/950596/tesla-cybercab-efficient-weight-range-epa",
    time: "2 ore fa",
    pub_ts: 1781622159,
    tags: [],
  },
  {
    id: 60,
    cat: "ai",
    title: "Plaud says its software business topped $100M in ARR after shipping over 2M AI notetakers",
    summary: "Plaud is trying to make a mark in a crowded market full of AI-powered meeting notetakers.",
    body: "Plaud is trying to make a mark in a crowded market full of AI-powered meeting notetakers.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/plaud-says-its-software-business-topped-100m-in-arr-after-shipping-over-2m-ai-notetakers/",
    time: "2 ore fa",
    pub_ts: 1781622000,
    tags: [],
  },
  {
    id: 61,
    cat: "ai",
    title: "Pour one out for Roku City",
    summary: "By this time next year, Fox Corporation CEO Lachlan Murdoch intends to have added Roku to his already expansive media empire. Should the acquisition go through, Fox will gain control of Roku's modest library of original programming, and the newly combined company will become \"the third-largest player in U.S. television\" in terms of viewing share. [&#8230;]",
    body: "By this time next year, Fox Corporation CEO Lachlan Murdoch intends to have added Roku to his already expansive media empire. Should the acquisition go through, Fox will gain control of Roku's modest library of original programming , and the newly combined company will become \"the third-largest player in U.S. television\" in terms of viewing share. But the most significant thing that Murdoch buys with this deal is direct access to the 100 million households that make up Roku's user base.\n\nIt's precisely because Roku and Fox are very different kinds of companies that a merger between the two could have a major impact on our modern media landsca …",
    source: "The Verge",
    url: "https://www.theverge.com/streaming/950644/fox-roku-acquisition-lachlan-murdoch-fox-news-consolidation",
    time: "2 ore fa",
    pub_ts: 1781621720,
    tags: [],
  },
  {
    id: 62,
    cat: "ai",
    title: "Robinhood’s note on 10% layoffs shows blaming AI isn’t cutting it",
    summary: "Unlike many of his tech industry peers who have cut thousands of jobs citing the need to restructure to make the most of AI, Robinhood's CEO Vlad Tenev conspicuously made no mention of AI in his note about layoffs.",
    body: "Unlike many of his tech industry peers who have cut thousands of jobs citing the need to restructure to make the most of AI, Robinhood's CEO Vlad Tenev conspicuously made no mention of AI in his note about layoffs.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/16/robinhoods-note-on-10-layoffs-shows-blaming-ai-isnt-cutting-it/",
    time: "2 ore fa",
    pub_ts: 1781621409,
    tags: [],
  },
  {
    id: 63,
    cat: "ai",
    title: "Perché Apple è la prima società tech finita sotto la lente dell'Antitrust per via delle regole europee sulla concorrenza",
    summary: "Secondo l’Antitrust il colosso deve permettere gratuitamente di fare il backup completo dei dispositivi con qualsiasi servizio cloud. Su questo si concentra l’indagine partita il 9 giugno, la prima in Italia nell’ambito del Digital markets act",
    body: "Secondo l’Antitrust il colosso deve permettere gratuitamente di fare il backup completo dei dispositivi con qualsiasi servizio cloud. Su questo si concentra l’indagine partita il 9 giugno, la prima in Italia nell’ambito del Digital markets act",
    source: "Wired IT",
    url: "https://www.wired.it/article/indagine-antitrust-apple-icloud/",
    time: "2 ore fa",
    pub_ts: 1781620745,
    tags: [],
  },
  {
    id: 64,
    cat: "ai",
    title: "Chat sessista e immagini rubate delle passeggere, Atm apre un'indagine: “Il rispetto non è un valore negoziabile”",
    summary: "A far emergere il caso è stata una passeggera che ha fotografato una conversazione WhatsApp tra alcuni dipendenti Atm con immagini estratte dalle telecamere di bordo e commenti sessisti sulle donne. Atm ha aperto un’indagine interna e annunciato denuncia alle forze dell’ordine",
    body: "A far emergere il caso è stata una passeggera che ha fotografato una conversazione WhatsApp tra alcuni dipendenti Atm con immagini estratte dalle telecamere di bordo e commenti sessisti sulle donne. Atm ha aperto un’indagine interna e annunciato denuncia alle forze dell’ordine",
    source: "Wired IT",
    url: "https://www.wired.it/article/chat-sessista-contro-passeggere-atm-apre-indagine-rispetto-non-negoziabile/",
    time: "2 ore fa",
    pub_ts: 1781619065,
    tags: [],
  },
  {
    id: 65,
    cat: "economia-tech",
    title: "Calcio, i manager vincono il triangolare della solidarietà",
    summary: "La vittoria finale del “Triangolare Mondiale” è andata alla Nazionale Manager, ma in realtà hanno vinto tutti e soprattutto hanno vinto l’Associazione Boom e le sedi di Mantova e Brescia...",
    body: "La vittoria finale del “Triangolare Mondiale” è andata alla Nazionale Manager, ma in realtà hanno vinto tutti e soprattutto hanno vinto l’Associazione Boom e le sedi di Mantova e Brescia...",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/calcio-manager-vincono-triangolare-solidarieta-AIHDxYhD",
    time: "7 min fa",
    pub_ts: 1781629299,
    tags: [],
  },
  {
    id: 66,
    cat: "economia-tech",
    title: "Snap Launches $2,195 Specs, Declaring Glasses the Next Computer",
    summary: "Snap Inc. introduced Specs, a $2,195 pair of augmented reality glasses that co-founder Evan Spiegel described as a leapfrog advancement and the computer of the future.",
    body: "Snap Inc. introduced Specs, a $2,195 pair of augmented reality glasses that co-founder Evan Spiegel described as a leapfrog advancement and the computer of the future.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/snap-launches-2-195-specs-declaring-glasses-the-next-computer",
    time: "19 min fa",
    pub_ts: 1781628600,
    tags: [],
  },
  {
    id: 67,
    cat: "economia-tech",
    title: "SpaceX leapfrogs Amazon to become world’s fifth-most valuable company",
    summary: "Elon Musk’s AI, rocket and satellite group also announces $60bn deal for AI coding app Cursor",
    body: "Elon Musk’s AI, rocket and satellite group also announces $60bn deal for AI coding app Cursor",
    source: "Financial Times",
    url: "https://www.ft.com/content/17153f13-b0c8-4331-8f97-32a19a5e966e",
    time: "26 min fa",
    pub_ts: 1781628180,
    tags: [],
  },
  {
    id: 68,
    cat: "economia-tech",
    title: "HPE Boosts Networking Gear for AI Clients, Adds Siemens Energy",
    summary: "Hewlett Packard Enterprise Co. introduced new networking gear for artificial intelligence data centers, building on the products it acquired from Juniper Networks and striving to capture more of the demand for AI tools from corporate customers.",
    body: "Antonio Neri, chief executive officer of Hewlett Packard Enterprise Co. (HPE), left, and Jensen Huang, co-founder and chief executive officer of Nvidia Corp., during a keynote address at the HPE Discover event at the Sphere in Las Vegas, Nevada, US, on Tuesday, June 18, 2024. Hewlett Packard Enterprise and Nvidia announced Nvidia AI Computing by HPE, an integrated software portfolio for generative AI.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/hpe-boosts-networking-gear-for-ai-clients-adds-siemens-energy",
    time: "39 min fa",
    pub_ts: 1781627400,
    tags: [],
  },
  {
    id: 69,
    cat: "economia-tech",
    title: "Oil sinks below $80 a barrel as traders bet Strait of Hormuz flows will return",
    summary: "Brent crude has tumbled to three-month low following agreement to extend US-Iran ceasefire",
    body: "Brent crude has tumbled to three-month low following agreement to extend US-Iran ceasefire",
    source: "Financial Times",
    url: "https://www.ft.com/content/45340e55-aa6a-4302-a606-a869f5cb6189",
    time: "48 min fa",
    pub_ts: 1781626853,
    tags: [],
  },
  {
    id: 70,
    cat: "economia-tech",
    title: "Apollo-Backed Rackspace Loan Jumps on AMD Data Center Deal",
    summary: "Rackspace Technology Inc., a cloud-computing services company backed by Apollo Global Management Inc., saw its $1.6 billion loan jump after it signed a data center deal with Advanced Micro Devices Inc., extending a rally in debt that had traded at deeply distressed levels just two months ago.",
    body: "Rackspace Technology Inc., a cloud-computing services company backed by Apollo Global Management Inc., saw its $1.6 billion loan jump after it signed a data center deal with Advanced Micro Devices Inc., extending a rally in debt that had traded at deeply distressed levels just two months ago.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/apollo-backed-rackspace-loan-jumps-on-amd-data-center-deal",
    time: "55 min fa",
    pub_ts: 1781626435,
    tags: [],
  },
  {
    id: 71,
    cat: "economia-tech",
    title: "Russian warship accused of firing warning shots towards yacht in Channel",
    summary: "Ministry of Defence says it is ‘investigating reports of incident’",
    body: "Ministry of Defence says it is ‘investigating reports of incident’",
    source: "Financial Times",
    url: "https://www.ft.com/content/ddbc8071-3d83-4c44-8ab4-13ac39e46636",
    time: "57 min fa",
    pub_ts: 1781626355,
    tags: [],
  },
  {
    id: 72,
    cat: "economia-tech",
    title: "Apple Plans Camera AirPods Alongside Upgraded Foldable iPhone in 2027",
    summary: "Apple Inc.’s upcoming camera-equipped AirPods, a product meant to vault the company into the AI device market, is scheduled to launch in late 2027 as part of a flurry of new releases.",
    body: "Apple Inc.’s upcoming camera-equipped AirPods, a product meant to vault the company into the AI device market, is scheduled to launch in late 2027 as part of a flurry of new releases.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/apple-plans-camera-airpods-iphone-foldable-2-20th-anniversary-iphone-in-2027",
    time: "1 ora fa",
    pub_ts: 1781625701,
    tags: [],
  },
  {
    id: 73,
    cat: "economia-tech",
    title: "AI Is Training Staff Very Quickly, Says RBC's McKay",
    summary: "Royal Bank of Canada Chief Executive Officer Dave McKay says it's \"unbelievable\" how fast artificial intelligence is training staffers. He says the technology is also making workers more efficient. He spoke to Lisa Abramowicz on Tuesday at a Bloomberg Newsmakers event in Toronto. (Source: Bloomberg)",
    body: "Royal Bank of Canada Chief Executive Officer Dave McKay says it's \"unbelievable\" how fast artificial intelligence is training staffers. He says the technology is also making workers more efficient. He spoke to Lisa Abramowicz on Tuesday at a Bloomberg Newsmakers event in Toronto. (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-06-16/ai-is-training-staff-very-quickly-says-rbc-s-mckay-video",
    time: "1 ora fa",
    pub_ts: 1781623987,
    tags: [],
  },
  {
    id: 74,
    cat: "economia-tech",
    title: "Moody's: Private Credit Faces 2028 Test",
    summary: "Marc Pinto, the Global Head of Private Credit at Moody's Ratings, joins Bloomberg Open Interest to explain why private credit is entering a pivotal phase. While AI infrastructure spending is creating huge lending opportunities, cracks are beginning to emerge in software-focused portfolios. Pinto warns that the real test comes in 2028, when a wave of refinancing could expose which borrowers…",
    body: "Marc Pinto, the Global Head of Private Credit at Moody's Ratings, joins Bloomberg Open Interest to explain why private credit is entering a pivotal phase. While AI infrastructure spending is creating huge lending opportunities, cracks are beginning to emerge in software-focused portfolios. Pinto warns that the real test comes in 2028, when a wave of refinancing could expose which borrowers survive and which don't.\n\n(Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-06-16/moody-s-private-credit-faces-2028-test-video",
    time: "1 ora fa",
    pub_ts: 1781622816,
    tags: [],
  },
  {
    id: 75,
    cat: "economia-tech",
    title: "AI Driving 'Insatiable Appetite' for Capital, RBC's McKay Says",
    summary: "Royal Bank of Canada CEO David McKay says there is a risk-on attitude in the market right now, driven by the push for AI and computing capacity. He speaks with Lisa Abramowicz at a Bloomberg Newsmakers event. (Source: Bloomberg)",
    body: "Royal Bank of Canada CEO David McKay says there is a risk-on attitude in the market right now, driven by the push for AI and computing capacity. He speaks with Lisa Abramowicz at a Bloomberg Newsmakers event. (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-06-16/ai-driving-insatiable-appetite-for-capital-rbc-ceo-video",
    time: "2 ore fa",
    pub_ts: 1781622073,
    tags: [],
  },
  {
    id: 76,
    cat: "economia-tech",
    title: "Principal Mineral Buys Cerberus-Backed Critical Materials Firm",
    summary: "Principal Mineral is buying a Cerberus Capital Management LP-backed firm that produces components for printed circuit boards, a key electronic part used in products from cars to planes to AI servers.",
    body: "Principal Mineral is buying a Cerberus Capital Management LP-backed firm that produces components for printed circuit boards, a key electronic part used in products from cars to planes to AI servers.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/principal-mineral-buys-cerberus-backed-critical-materials-firm",
    time: "2 ore fa",
    pub_ts: 1781620721,
    tags: [],
  },
  {
    id: 77,
    cat: "economia-tech",
    title: "SpaceX Pounces on $60 Billion Cursor Takeover Days After IPO",
    summary: "Technically, SpaceX had 30 days following its record-shattering public debut to decide on a $60 billion takeover of the AI coding startup Cursor. In the end, all it took was two trading days.",
    body: "Technically, SpaceX had 30 days following its record-shattering public debut to decide on a $60 billion takeover of the AI coding startup Cursor. In the end, all it took was two trading days.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/spacex-pounces-on-60-billion-cursor-takeover-days-after-ipo",
    time: "3 ore fa",
    pub_ts: 1781617651,
    tags: [],
  },
  {
    id: 78,
    cat: "economia-tech",
    title: "The Executive Coach Showing Sam Altman How to Lead With ‘Emotional Fluidity’",
    summary: "Joe Hudson is sure the winners of the impending tech revolution will be human.",
    body: "Joe Hudson is sure the winners of the impending tech revolution will be human.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/features/2026-06-16/openai-s-executive-coach-says-emotional-clarity-will-matter-most-in-ai",
    time: "3 ore fa",
    pub_ts: 1781616615,
    tags: [],
  },
  {
    id: 79,
    cat: "economia-tech",
    title: "World Cup Exposes Growing Global Prediction Market Rift",
    summary: "This year’s World Cup is the first since prediction markets like Kalshi and Polymarket exploded to popularity as a new way to bet on sports.",
    body: "This year’s World Cup is the first since prediction markets like Kalshi and Polymarket exploded to popularity as a new way to bet on sports.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/world-cup-exposes-growing-global-rift-over-prediction-markets",
    time: "3 ore fa",
    pub_ts: 1781616358,
    tags: [],
  },
  {
    id: 80,
    cat: "economia-tech",
    title: "Trump says Syria should fight Hizbollah instead of Israel",
    summary: "US president says he is ‘not happy’ with Israeli military campaign against Lebanese militant group",
    body: "US president says he is ‘not happy’ with Israeli military campaign against Lebanese militant group",
    source: "Financial Times",
    url: "https://www.ft.com/content/12df7e82-1f5f-4202-8f42-fe224cbd87c0",
    time: "3 ore fa",
    pub_ts: 1781616162,
    tags: [],
  },
  {
    id: 81,
    cat: "economia-tech",
    title: "SpaceX Agrees to $60 Billion Cursor Takeover Post-IPO",
    summary: "SpaceX will take over Cursor in a deal that values the artificial intelligence coding startup at $60 billion, as Elon Musk aims to catch up with rivals on coding tools. The deal is expected to close in the third quarter. Ed Ludlow reports on Bloomberg Television. (Source: Bloomberg)",
    body: "SpaceX will take over Cursor in a deal that values the artificial intelligence coding startup at $60 billion, as Elon Musk aims to catch up with rivals on coding tools. The deal is expected to close in the third quarter. Ed Ludlow reports on Bloomberg Television. (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-06-16/spacex-agrees-to-60-billion-cursor-takeover-post-ipo-video",
    time: "3 ore fa",
    pub_ts: 1781616149,
    tags: [],
  },
  {
    id: 82,
    cat: "economia-tech",
    title: "Poland Pursues Taiwan Investments to End Role as Assembly Hub",
    summary: "Poland is betting on a flood of investments and technology transfers from Taiwanese companies to reengineer its $1 trillion economy.",
    body: "Poland is betting on a flood of investments and technology transfers from Taiwanese companies to reengineer its $1 trillion economy.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/poland-pursues-taiwan-investments-to-end-role-as-assembly-hub",
    time: "3 ore fa",
    pub_ts: 1781615739,
    tags: [],
  },
  {
    id: 83,
    cat: "economia-tech",
    title: "Microsoft’s Latest Surface PCs Offer Better Graphics, Faster AI",
    summary: "Microsoft Corp. introduced updated Surface Pro and Surface Laptop devices, refreshing both products with faster graphics and new chips from Qualcomm Inc. to more effectively court creative professionals and artificial intelligence super users.",
    body: "Microsoft Corp. introduced updated Surface Pro and Surface Laptop devices, refreshing both products with faster graphics and new chips from Qualcomm Inc. to more effectively court creative professionals and artificial intelligence super users.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/microsoft-2026-surface-pro-and-surface-laptop-offer-better-graphics-faster-ai",
    time: "4 ore fa",
    pub_ts: 1781614815,
    tags: [],
  },
  {
    id: 84,
    cat: "economia-tech",
    title: "Startup Backed by Ex-Google CEO Debuts Industrial Robot With LG",
    summary: "A startup backed by former Google Chief Executive Officer Eric Schmidt unveiled an industrial robot powered by artificial intelligence, as investors pile into the emerging field of humanoids.",
    body: "A startup backed by former Google Chief Executive Officer Eric Schmidt unveiled an industrial robot powered by artificial intelligence, as investors pile into the emerging field of humanoids.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-16/startup-backed-by-ex-google-ceo-debuts-industrial-robot-with-lg",
    time: "4 ore fa",
    pub_ts: 1781614800,
    tags: [],
  },
];
