// Generato automaticamente il 2026-06-15 05:08 UTC da scripts/fetch_news.py
// NON modificare manualmente: viene sovrascritto ogni ora dalla GitHub Action.
var NEWS_TIMESTAMP = 1781500068;

const RSS_SOURCES = [
  {
    "name": "ANSA",
    "url": "https://www.ansa.it/sito/ansait_rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Corriere",
    "url": "https://xml2.corrieredellasera.it/rss/homepage.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Il Post",
    "url": "https://www.ilpost.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Sky TG24",
    "url": "https://tg24.sky.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "AGI",
    "url": "https://www.agi.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Pagella Politica",
    "url": "https://pagellapolitica.it/feed",
    "cat": "politica-italiana"
  },
  {
    "name": "Facta",
    "url": "https://facta.news/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Valigia Blu",
    "url": "https://www.valigiablu.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Limes",
    "url": "https://www.limesonline.com/feed",
    "cat": "geopolitica"
  },
  {
    "name": "Internazionale",
    "url": "https://www.internazionale.it/feed/tutto",
    "cat": "geopolitica"
  },
  {
    "name": "BBC World",
    "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "AP",
    "url": "https://apnews.com/hub/world-news?output=rss",
    "cat": "geopolitica"
  },
  {
    "name": "The Economist",
    "url": "https://www.economist.com/international/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "El Pais",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "cat": "geopolitica"
  },
  {
    "name": "Reuters",
    "url": "https://feeds.reuters.com/reuters/worldNews",
    "cat": "conflitti"
  },
  {
    "name": "Al Jazeera",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "cat": "conflitti"
  },
  {
    "name": "AP conflitti",
    "url": "https://apnews.com/hub/wars-and-conflicts?output=rss",
    "cat": "conflitti"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/rss/index.xml",
    "cat": "ai"
  },
  {
    "name": "Wired IT",
    "url": "https://www.wired.it/feed/rss",
    "cat": "ai"
  },
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Post Tech",
    "url": "https://www.ilpost.it/tecnologia/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Sole 24 Ore",
    "url": "https://www.ilsole24ore.com/rss/economia.xml",
    "cat": "economia-tech"
  },
  {
    "name": "Bloomberg Tech",
    "url": "https://feeds.bloomberg.com/technology/news.rss",
    "cat": "economia-tech"
  },
  {
    "name": "Financial Times",
    "url": "https://www.ft.com/rss/home",
    "cat": "economia-tech"
  },
  {
    "name": "The Economist Ec",
    "url": "https://www.economist.com/business/rss.xml",
    "cat": "economia-tech"
  }
];

const NEWS = [
  {
    id: 1,
    cat: "politica-italiana",
    title: "Meloni: 'Il patentino antifascista è censura'. Polemica su Più libri più liberi",
    summary: "La Fiera rigetta le accuse ma annuncia \"approfondimento\". Opposizioni: 'La premier insegue Vannacci'",
    body: "La Fiera rigetta le accuse ma annuncia \"approfondimento\". Opposizioni: 'La premier insegue Vannacci'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/politica/2026/06/14/meloni-patentino-antifascista-per-gli-editori-e-censura_76f6a69c-4824-4dbb-a26f-d751a0bc51a5.html",
    time: "7 ore fa",
    pub_ts: 1781471647,
    tags: [],
  },
  {
    id: 2,
    cat: "politica-italiana",
    title: "Media, Abu Mazen annuncia le presidenziali palestinesi nel 2027",
    summary: "Nel decreto non è indicata una data precisa ma solo l'anno in cui terranno le elezioni",
    body: "Nel decreto non è indicata una data precisa ma solo l'anno in cui terranno le elezioni",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/06/14/media-abu-mazen-annuncia-le-presidenziali-palestinesi-nel-2027_3b185f8f-191a-463d-8583-1c6c5bce8be1.html",
    time: "9 ore fa",
    pub_ts: 1781467314,
    tags: [],
  },
  {
    id: 3,
    cat: "politica-italiana",
    title: "Vannacci senza freni: 'Il femminicidio non esiste, un omicidio come altri'",
    summary: "Il generale sceglie 'Futura' di Dalla come inno. E in sala il saluto ai 'camerati'",
    body: "Il generale sceglie 'Futura' di Dalla come inno. E in sala il saluto ai 'camerati'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/politica/2026/06/14/vannacci-senza-freni-il-femminicidio-non-esiste-un-omicidio-come-altri_5efaa8ed-226f-4a19-ad4c-2316203d2b4c.html",
    time: "10 ore fa",
    pub_ts: 1781462256,
    tags: [],
  },
  {
    id: 4,
    cat: "politica-italiana",
    title: "Scatta il collocamento del Btp Italia sì, ombrello per il caro-prezzi",
    summary: "Pagherà un tasso di interesse dell'1,6% più l'inflazione",
    body: "Pagherà un tasso di interesse dell'1,6% più l'inflazione",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/economia/2026/06/14/domani-via-al-collocamento-del-btp-italia-si-ombrello-per-il-caro-prezzi_c5f16cdd-9697-4e16-bf24-21000f3bd240.html",
    time: "14 ore fa",
    pub_ts: 1781446074,
    tags: [],
  },
  {
    id: 5,
    cat: "politica-italiana",
    title: "A Pitti Uomo l'eleganza che non costringe, il nuovo must è la 'shacket'",
    summary: "Con il soft tailoring della PE27, addio pantaloni skinny ma anche super oversize",
    body: "Con il soft tailoring della PE27, addio pantaloni skinny ma anche super oversize",
    source: "ANSA",
    url: "https://www.ansa.it/canale_lifestyle/notizie/moda/2026/06/13/a-pitti-uomo-leleganza-che-non-costringe-il-nuovo-must-e-la-shacket_bec87614-6869-4206-b0c1-5141806f4b11.html",
    time: "1 giorno fa",
    pub_ts: 1781386363,
    tags: [],
  },
  {
    id: 6,
    cat: "politica-italiana",
    title: "La fotografia è donna, a Roma la Collezione Donata Pizzi",
    summary: "La raccolta di immagini italiane dagli anni Sessanta a oggi ha uno spazio permanente",
    body: "La raccolta di immagini italiane dagli anni Sessanta a oggi ha uno spazio permanente",
    source: "ANSA",
    url: "https://www.ansa.it/canale_viaggi/regione/lazio/2026/06/13/la-fotografia-e-donna-a-roma-la-collezione-donata-pizzi_554fdced-4ce8-462b-99fe-fa7f7fd90b80.html",
    time: "1 giorno fa",
    pub_ts: 1781370944,
    tags: [],
  },
  {
    id: 7,
    cat: "politica-italiana",
    title: "Quando lo Stato spegne l’intelligenza: il caso Claude Fable 5 e la deriva autoritaria dell’era Trump",
    summary: "Il 12 giugno 2026 il governo statunitense ha spento con una lettera il modello più avanzato di Anthropic, Claude Fable 5. Un'azione d'imperio che, dietro la maschera della sicurezza nazionale, nasconde logiche di pressione politica e competitiva. Un test preoccupante per lo stato della democrazia e dell'innovazione nell'era Trump.",
    body: "C'è un gesto che racconta un'epoca meglio di mille dichiarazioni: un governo che, con una lettera, spegne da un giorno all'altro la tecnologia più avanzata prodotta da una delle proprie aziende. È successo il 12 giugno 2026, e dovrebbe farci riflettere molto più di quanto la cronaca distratta abbia fatto. I fatti, prima di tutto Il 9 giugno Anthropic — laboratorio di intelligenza artificiale nato nel 2021 dalla scissione di un gruppo di ricercatori usciti da OpenAI proprio per ragioni di responsabilità e sicurezza — rilascia Claude Fable 5 , il suo modello più avanzato, dotato di guardrail tra i più robusti del settore.\n\nTre giorni dopo, alle 17:21 di un venerdì, arriva la mannaia. Il Dipartimento del Commercio, guidato dal segretario Howard Lutnick, invia una lettera all'amministratore delegato Dario Amodei: export control directive. Tradotto: accesso vietato al modello per qualsiasi cittadino non statunitense, anche dentro i confini americani, persino ai dipendenti stranieri della stessa Anthropic. Impossibile applicare un filtro simile in tempo reale, l'azienda è costretta a spegnere tutto, per tutti, in tutto il mondo.\n\nUna decisione che, secondo quanto riportato, non era nemmeno accompagnata da una spiegazione tecnica della presunta minaccia alla sicurezza nazionale. Un ordine, e basta. La giustificazione che non sta in piedi L'amministrazione parla di rischio per la sicurezza nazionale, evocando un jailbreak del modello. Ma i fatti tecnici ridimensionano drasticamente l'allarme: si tratterebbe di una falla stretta e tutt'altro che universale — la possibilità di far analizzare al modello un codice per individuare vulnerabilità software — una capacità peraltro già presente in altri modelli concorrenti, incluso il GPT-5.5 di OpenAI.\n\nAnthropic, dal canto suo, dichiara di aver condotto migliaia di ore di red-teaming, anche in collaborazione con enti governativi, senza individuare alcun rischio sistemico. L'azienda parla apertamente di un \"fraintendimento\". E qui sta il punto: quando uno Stato esercita un potere così sproporzionato senza fornire prove, non siamo più nel campo della prudenza, ma in quello dell'arbitrio. Il contesto che pesa Perché proprio ora? La domanda è legittima, e le coincidenze sono di quelle che fanno alzare più di un sopracciglio.\n\nIl provvedimento cade nella stessa settimana del debutto in borsa di SpaceX , l'azienda di Elon Musk, con una valutazione obiettivo attorno ai 2 trilioni di dollari. E colpisce Anthropic nel momento più delicato: l'azienda ha depositato il 1° giugno il draft riservato del proprio S-1 alla SEC , in piena fase pre-IPO, con una valutazione vicina ai mille miliardi. Non servono teoremi complottisti per notare il quadro: un'amministrazione che ha fatto della fedeltà personale e della pressione sulle imprese una cifra di governo, e che si trova ora a maneggiare leve regolatorie capaci di decidere, di fatto, chi corre e chi viene rallentato sul mercato più strategico del decennio.\n\nIn un'epoca in cui la prossimità al potere conta più della concorrenza leale, la tentazione di usare lo strumento \"sicurezza nazionale\" come arma competitiva o di pressione non è uno scenario remoto. È un rischio concreto, e la storia di questa amministrazione non invita all'ottimismo. Il problema più grande Al netto delle dietrologie, resta un fatto che dovrebbe preoccupare chiunque abbia a cuore la libertà e l'innovazione: il principio per cui un governo può spegnere globalmente, in poche ore e senza motivazioni verificabili, una tecnologia legalmente sviluppata sul proprio territorio.\n\nÈ il paradosso perfetto dell'autoritarismo che si traveste da prudenza. Si colpisce proprio l'azienda che più di tutte ha fatto della sicurezza la propria ragion d'essere, mentre le capacità incriminate restano tranquillamente disponibili altrove. Il messaggio implicito è chiaro: non conta cosa fai bene, conta quanto sei allineato. Una democrazia matura non spegne l'intelligenza con una lettera del venerdì sera.\n\nLa sottopone a regole trasparenti, a evidenze condivise, a un controllo che sia pubblico e contestabile. Tutto il contrario di quello che abbiamo visto. In conclusione Il caso Fable 5 non è una notizia di nicchia per addetti ai lavori. È un test sullo stato di salute delle istituzioni democratiche americane nell'era Trump. E il risultato, per ora, è preoccupante: il potere esecutivo che agisce d'imperio , senza trasparenza, in un campo dove la posta in gioco sono il progresso tecnologico, la concorrenza leale e — non da ultimo — la fiducia nelle regole.\n\nDifendere chi innova in modo responsabile, pretendere che lo Stato giustifichi le proprie decisioni con prove e non con timori generici, vigilare perché la \"sicurezza nazionale\" non diventi un grimaldello politico: ecco la battaglia. Una battaglia che è, prima di tutto, democratica. &nbsp;",
    source: "Valigia Blu",
    url: "https://www.valigiablu.it/caso-anthropic-claude-fable-5-blocco-usa-trump/",
    time: "1 giorno fa",
    pub_ts: 1781352660,
    tags: [],
  },
  {
    id: 8,
    cat: "geopolitica",
    title: "Bubista, de jugar en el Badajoz a llevar a Cabo Verde al Mundial como seleccionador",
    summary: "El técnico del país africano, que jugó unos meses en Segunda en los noventa, ha llevado a su punto más alto a un equipo construido con jugadores nacidos fuera",
    body: "De niño, Pedro Leitão Brito, Bubista, comenzó a soñar con verse en un Mundial en el verano de 1982. Apareció el primer televisor en la isla caboverdiana de Boa Vista, donde nació hace 56 años. El propietario cobraba entrada a su casa para ver los partidos de la Copa del Mundo disputada en España y él y sus amigos inventaban maneras de colarse sin pagar. Hasta que los localizaba y los echaba. “En esa época empecé a entender lo que quería para mi vida”, ha contado.\n\n“Quería llegar a los grandes escenarios del fútbol”. Y ha llegado: 44 años más tarde se estrena en un Mundial como seleccionador de Cabo Verde . Precisamente contra España, el país donde también llegó más alto en su carrera como futbolista. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-06-15/bubista-de-jugar-en-el-badajoz-a-llevar-a-cabo-verde-al-mundial-como-seleccionador.html",
    time: "7 min fa",
    pub_ts: 1781499625,
    tags: [],
  },
  {
    id: 9,
    cat: "geopolitica",
    title: "La Casa Blanca, vestuario de una pelea de artes marciales mixtas: Trump celebra sus 80 años con un ‘show’ sin precedentes",
    summary: "El presidente pone un símbolo de la democracia estadounidense al servicio de un violento y multitudinario combate de la UFC en el que los luchadores le rindieron pleitesía",
    body: "En Idiocracia (2006), sátira salvaje que imagina la vida en Estados Unidos en 2505, tras siglos de disgenesia y estupidificación colectiva, el presidente del país es una estrella retirada de lucha libre profesional, que entra en el Congreso a dar el discurso sobre el Estado de la Unión a ritmo de machacón rock duro y al final preside una versión sádica e idiota de una lucha en un circo romano. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-15/la-casa-blanca-vestuario-de-una-pelea-de-artes-marciales-mixtas-trump-celebra-sus-80-anos-con-un-show-sin-precedentes.html",
    time: "29 min fa",
    pub_ts: 1781498342,
    tags: [],
  },
  {
    id: 10,
    cat: "geopolitica",
    title: "La FIFA rectifica y permite el español en todas las ruedas de prensa",
    summary: "La polémica se había iniciado en las conferencias de Vinicius y Hakimi en Estados Unidos, donde se impidió a los periodistas hispanohablantes hacer preguntas en su idioma",
    body: "El español ya está permitido en todo el Mundial. La FIFA dio marcha atrás y desde este domingo permite preguntas y respuestas en castellano durante las ruedas de prensa de los partidos que se jueguen en Estados Unidos, aunque no participen selecciones hispanohablantes. La polémica había comenzado en las comparecencias de Vinicius y Achraf Hakimi, a quienes la FIFA no había autorizado a recibir consultas ni contestarlas en español durante la antesala del duelo de Brasil con Marruecos en Nueva Jersey —y había sumado un tercer capítulo con Frankie De Jong en la previa del cruce de Países Bajos ante Japón en Dallas—.\n\nEso ya es parte del pasado. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/us/2026-06-15/la-fifa-rectifica-y-permite-el-espanol-en-todas-las-ruedas-de-prensa.html",
    time: "51 min fa",
    pub_ts: 1781496976,
    tags: [],
  },
  {
    id: 11,
    cat: "geopolitica",
    title: "Árboles contra el calor urbano: el 80% de los valencianos y el 60% de los madrileños no tienen zonas verdes cerca",
    summary: "Un estudio identifica las áreas prioritarias en las que habría que aumentar la vegetación en 10 ciudades españolas",
    body: "Hoy en día, existen pocas dudas de los beneficios para los ciudadanos de las zonas verdes en las ciudades , sobre todo cuando empieza a apretar el calor. Sin embargo, la cantidad de vegetación en las urbes depende mucho de cómo se mida. Un ejemplo: la información disponible muestra que Badajoz cuenta con una media de 24,8 metros de espacios verdes de importancia por cada habitante, una cifra alta.\n\nPero, cuando se analiza cómo se reparten realmente estas áreas, resulta que un 73% de los habitantes de esta localidad tan calurosa no tienen acceso a ninguna de estas zonas a menos de 300 metros de su casa. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/clima-y-medio-ambiente/2026-06-15/arboles-contra-el-calor-urbano-el-80-de-los-valencianos-y-el-60-de-los-madrilenos-no-tienen-zonas-verdes-cerca.html",
    time: "1 ora fa",
    pub_ts: 1781495101,
    tags: [],
  },
  {
    id: 12,
    cat: "geopolitica",
    title: "La víctima de Alessandro Pompeo, ante la fuga de su agresor sexual: “Quiero contarlo porque quiero que lo busquen y que se haga justicia”",
    summary: "Tamara Fernández Varela avisó a su abogado del riesgo de huida: “Él estaba vendiendo todo y se había despedido”",
    body: "Tamara Fernández Varela, de 43 años, siempre se ha definido como una persona valiente. Con solo 17 años se marchó sola a Suiza para trabajar cuidando niños y, en distintos momentos de su vida, llegó a compaginar hasta tres empleos. Disfrutaba paseando por el bosque y recolectando setas y flores. Es madre de una hija de 18 años. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/podcasts/hoy-en-el-pais/2026-06-15/la-victima-de-alessandro-pompeo-ante-la-fuga-de-su-agresor-sexual-quiero-contarlo-porque-quiero-que-lo-busquen-y-que-se-haga-justicia.html",
    time: "1 ora fa",
    pub_ts: 1781495100,
    tags: [],
  },
  {
    id: 13,
    cat: "geopolitica",
    title: "La frustración se instala en la sociedad israelí tras años de guerra permanente",
    summary: "La población sigue apoyando las campañas bélicas de Netanyahu, pese a los magros resultados en casi tres años y al impacto en sus vidas",
    body: "Todo aquel que aterriza en el aeropuerto israelí de Ben Gurión, cerca de Tel Aviv, se encuentra con una imagen inusual: decenas de aviones militares estadounidenses de repostaje y carga estacionados a plena vista. Aunque las autoridades hablan abiertamente de su presencia, el aeropuerto ha puesto un cartel que prohíbe fotografiarlos. Como Israel encadena guerras desde hace casi tres años , pero sufre un daño muy limitado en comparación con el que causa, la anormalidad de la situación (convertir el principal aeropuerto civil del país en potencial objetivo de los misiles iraníes) convive con el hecho de que sigue siendo la principal puerta de salida para irse de vacaciones.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-15/la-frustracion-se-instala-en-la-sociedad-israeli-tras-anos-de-guerra-permanente.html",
    time: "1 ora fa",
    pub_ts: 1781494800,
    tags: [],
  },
  {
    id: 14,
    cat: "geopolitica",
    title: "La cumbre del G-7 en Francia mide el cisma de Occidente",
    summary: "La reunión anual del grupo de potencias tomará el pulso del lazo transatlántico y abordará las guerras de Irán y Ucrania, así como la relación con China",
    body: "La cumbre del G-7, el grupo que reúne a siete de las democracias más industrializadas del mundo, medirá esta semana la profundidad del cisma de Occidente, la división entre Estados Unidos y sus tradicionales aliados. La cumbre se desarrolla desde este lunes hasta el miércoles en la localidad francesa de Évian-les-Bains, a orillas del lago de Lemán. La víspera ha estado marcada por una manifestación de protesta en Ginebra (Suiza) a la que asistieron miles de personas y en la cual se produjeron actos vandálicos y choques con la policía.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-15/la-cumbre-del-g-7-en-francia-mide-el-cisma-de-occidente.html",
    time: "1 ora fa",
    pub_ts: 1781494800,
    tags: [],
  },
  {
    id: 15,
    cat: "geopolitica",
    title: "La UDEF detectó cuatro viajes juntos a Caracas del presidente de Plus Ultra y Julio Martínez",
    summary: "La Policía registró vuelos entre Madrid y Venezuela de Julio Martínez Sola y el amigo del expresidente Zapatero entre 2023 y 2025",
    body: "La Unidad de Delincuencia Económica y Fiscal (UDEF) de la Policía Nacional detectó, al menos, cuatro viajes juntos entre Madrid y Caracas (Venezuela) del empresario alicantino Julio Martínez Martínez —amigo personal del expresidente José Luis Rodríguez Zapatero— y el actual presidente de Plus Ultra, Julio Martínez Sola, entre 2023 y 2025. El último, de hecho, se produjo un mes antes de que ambos fueran detenidos, acusados de una serie de presuntos delitos vinculados al rescate de 53 millones de euros que el Gobierno entregó a la compañía aérea en 2021.\n\nEl juez de la Audiencia Nacional José Luis Calama, que instruye el caso, escucha esta semana la versión de Zapatero, y lo previsible es que inmediatamente después cite a los altos cargos de la compañía y al propio empresario Martínez Martínez para conocer sus versiones de los hechos. A pesar de que la compañía lo había contratado como consultor, él hizo labores de “conseguidor” en el país que dirige Delcy Rodríguez, como aseguran fuentes del caso.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-15/la-udef-detecto-cuatro-viajes-juntos-a-caracas-del-presidente-de-plus-ultra-y-julio-martinez.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 16,
    cat: "geopolitica",
    title: "El retrato completo del Mundial de México",
    summary: "Una madre que busca a su hijo, arrodillada ante una muralla de policías, se hace viral en un país donde las familias luchan por encontrar a 134.000 desaparecidos",
    body: "Entre el caudal de imágenes en las redes sociales de preparativos del Mundial de fútbol, del que México es uno de los anfitriones, hay una que resulta desgarradora. En un vídeo se ve a una madre buscadora arrodillada ante una muralla de antidisturbios que le bloquea el paso a ella y a sus compañeras en su marcha pacífica hasta el Estadio Azteca. En uno de los fragmentos compartidos en Instagram la noche antes del encuentro deportivo, se le oye decir a los agentes, entre sollozos: “Déjennos pasar, por favor.\n\nVean el dolor de cada uno de nosotros. No estamos haciendo daño”. Y sigue: “Queremos el regreso de nuestros hijos. Tengan compasión. Extraño a mi hijo. Seis años que he luchado”. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-06-15/el-retrato-completo-del-mundial-de-mexico.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 17,
    cat: "geopolitica",
    title: "Begoña Gómez, citada de nuevo este lunes ante el juez Peinado",
    summary: "El magistrado prevé celebrar a las 18.00 una vista preliminar del caso que mantiene imputada a la esposa del presidente, paso necesario para poder abrir juicio oral contra ella",
    body: "Begoña Gómez tiene otra cita este lunes ante el juez Juan Carlos Peinado. El magistrado ha fijado a las 18.00 la celebración de la audiencia preliminar prevista en la legislación como paso necesario para la apertura de juicio oral en un proceso con jurado. Con este movimiento, el instructor deja más cerca del banquillo a la esposa de Pedro Sánchez. Peinado, que aceptó hace dos años una denuncia del pseudosindicato Manos Limpias para impulsar una polémica investigación contra la mujer del presidente del Gobierno, ya consideró el pasado abril que contaba con indicios suficientes contra ella para que fuese acusada por cuatro delitos (malversación, tráfico de influencias, corrupción en los negocios y apropiación indebida de marca).\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-15/begona-gomez-citada-de-nuevo-este-lunes-ante-el-juez-peinado.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 18,
    cat: "geopolitica",
    title: "Igualdad pone bajo la lupa las ayudas para actividades de conciliación de Ayuso, que logró una entidad vinculada a los Legionarios de Cristo",
    summary: "El Ministerio encarga un informe jurídico sobre el uso de fondos estatales mientras que Madrid defiende la transparencia y legalidad de las subvenciones y proyectos",
    body: "El Ministerio de Igualdad, que dirige Ana Redondo (PSOE), ha encargado un informe jurídico sobre el sistema de reparto que emplea la Comunidad de Madrid, presidida por Isabel Díaz Ayuso (PP), para los fondos del Plan Corresponsables . El Ejecutivo central considera “atípico, en relación al resto de comunidades”, que estas ayudas estatales gestionadas por las regiones para promover el reparto equitativo de los cuidados se repartan a través del IRPF.\n\nY tampoco le ha pasado desapercibido que una entidad vinculada a los Legionarios de Cristo haya estado entre las beneficiarias en Madrid. “Desde el Ministerio se revisarán todas las actividades que se hayan adscrito al plan y si no cumplen con los objetivos del mismo se pedirá que se retiren”, explican en Igualdad. El Ejecutivo autonómico, por su parte, defiende que su fórmula permite que se beneficien las entidades del tercer sector y argumenta que “la convocatoria es totalmente transparente y cumple plenamente los objetivos específicos del plan”.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/madrid/2026-06-15/igualdad-pone-bajo-la-lupa-las-ayudas-para-actividades-de-conciliacion-de-ayuso-que-logro-una-entidad-vinculada-a-los-legionarios-de-cristo.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 19,
    cat: "geopolitica",
    title: "La conspiración de los justos",
    summary: "El próximo ciclo político debe ser el de la concordia, y para ello no podemos confiar en el azar ni en las élites que se han lucrado de la polarización",
    body: "Las conspiraciones rara vez son ciertas. De hecho, ni siquiera quienes intentan difundirlas creen en ellas. Es improbable que Franco creyera sinceramente en la confabulación judeomasónica, y tampoco es plausible que Óscar López considerara que alguien en la Guardia Civil quisiera colocarle una bomba lapa al presidente Sánchez. Quienes exacerban la suspicacia sólo buscan inocular desconfianza, que es la antesala del miedo.\n\nY cuando todos entramos en pánico, es mucho más sencillo activar mecanismos de control y dominio. Nada que los clásicos no supieran, por cierto. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-06-15/la-conspiracion-de-los-justos.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 20,
    cat: "geopolitica",
    title: "La regularización de inmigrantes alcanza un récord de 900.000 solicitudes",
    summary: "A 15 días de que termine el plazo, ya se han admitido a trámite 360.000 expedientes en un proceso que con toda probabilidad superará las cifras de las regularizaciones anteriores",
    body: "El Gobierno ha recibido ya 900.000 solicitudes de extranjeros que quieren regularizar su situación en España, esto es, obtener un permiso de residencia y trabajo y contar con los derechos consecuentes. Se trata de una cifra récord, al superar el número de peticiones de procedimientos anteriores. Por el momento, se han admitido a trámite unos 360.000 expedientes. Estos son los datos a los que ha tenido acceso EL PAÍS cuando faltan 15 días para que se cierren las ventanillas de las solicitudes: el 30 de junio, quien no haya presentado la suya no podrá entrar en este proceso de regularización que pretende aflorar el trabajo irregular de estas personas y concederles sus derechos.\n\nLa Administración tiene tres meses para tramitar cada solicitud, pero ya hay resoluciones favorables por toda España y fuentes gubernamentales consideran que el proceso discurre con normalidad. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-15/la-regularizacion-de-inmigrantes-alcanza-un-record-de-900000-solicitudes.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 21,
    cat: "geopolitica",
    title: "Contra la corrupción, descubrir el engaño",
    summary: "La lucha contra estas prácticas es un problema democrático que debería ser objeto de un enorme consenso, pero no lo es",
    body: "El 12 de mayo, uno de los tres fiscales que representaron a la acusación durante los dos meses del juicio por el recurso de Nicolas Sarkozy tras su condena por el caso de la financiación libia —como lo denominan en Francia— dedicó las primeras palabras de la segunda jornada de alegatos a La República, de Platón. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-06-15/contra-la-corrupcion-descubrir-el-engano.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 22,
    cat: "geopolitica",
    title: "La velocidad de destrucción",
    summary: "Arrasar sistemáticamente todas las infraestructuras que permiten la vida es un genocidio, aunque Israel no vuelva a tirar una bomba ni a forzar un desplazamiento",
    body: "La definición jurídica de genocidio que da Naciones Unidas no incluye un criterio de duración temporal. Sin embargo, sólo reconocemos como genocidio aquello que implica la destrucción rápida y espectacular de un grupo nacional, étnico, racial o religioso, y no la destrucción gradual, acumulativa y consciente de una parte de la población. Tanto es así, que llamamos genocidio a episodios de violencia concentrada como el Holocausto o Ruanda; y genocidio lento o por desgaste al régimen de Pol Pot en Camboya, que tardó tres años en acabar con una cuarta parte de la población.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-06-15/la-velocidad-de-destruccion.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 23,
    cat: "geopolitica",
    title: "Los grados de Ciencias y Salud acaparan las notas de corte más altas de la PAU",
    summary: "Desde Física y Matemáticas hasta Odontología: 10 titulaciones donde un expediente casi perfecto no garantiza una plaza",
    body: "En España, la diferencia entre estudiar la carrera de tus sueños o quedarte en lista de espera puede ser tan mínima como un par de décimas. Las notas de la Prueba de Acceso a la Universidad (PAU) han comenzado a conocerse esta semana en el grueso de las comunidades autónomas y cunde el nerviosismo de no alcanzar la nota mínima para ingresar al grado deseado. Buscador: consulta la nota de corte de cada carrera en España Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/educacion/2026-06-15/los-grados-de-ciencias-y-salud-acaparan-las-notas-de-corte-mas-altas-de-la-pau-2026.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 24,
    cat: "geopolitica",
    title: "Si suena Shakira, empieza el Mundial: el amuleto de la FIFA para amplificar el alcance de la competición",
    summary: "La cantante se convierte en la primera artista en sumar tres canciones para la Copa. ‘Dai Dai’ enfila el camino del éxito con una fórmula de ritmos latinos y africanos en varios idiomas",
    body: "Circula estos días esta analogía en redes sociales que alcanza a las conversaciones de bar: “Cuando oyes a Mariah Carey sabes que llega la Navidad ; si suena Shakira, que empieza un mundial de fútbol”. La cantante colombiana se ha convertido en la única artista que ha firmado en tres ocasiones la canción de esta competición. En la memoria de los aficionados a este deporte y de aquellos que, quieran o no, acaban sepultados en las maquinarias de marketing que envuelven estos eventos, está fijado el tema Waka Waka, de la Copa de Sudáfrica en 2010 .\n\nDesde aquel momento, se produjo un punto de inflexión en la carrera de Shakira. Acostumbrada a sumar hits, amplificó su público potencial y se convirtió en el amuleto de la FIFA para contribuir al relato de que el Mundial es ese punto de encuentro para una celebración compartida, y en el que las diferencias (de todo tipo) se diluyen durante unas semanas. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/cultura/2026-06-15/si-suena-shakira-empieza-el-mundial-el-amuleto-de-la-fifa-para-amplificar-el-alcance-de-la-competicion.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 25,
    cat: "geopolitica",
    title: "Democracias amenazadas",
    summary: "Resulta muy peligrosa la estrategia que confunde el respeto a la justicia con la indiferencia ante el comportamiento de algunos jueces",
    body: "No me duelen los actos de la gente mala, me duele la indiferencia de la gente buena. Eso afirmó Martin Luther King en su lucha por la dignidad humana y eso recuerda Baltasar Garzón al analizar las situaciones de la justicia en España y en el panorama internacional. Resulta muy peligrosa la estrategia que confunde el respeto a la justicia con el silencio, la indiferencia y el cerrar los ojos ante el comportamiento de algunos jueces y de las administraciones judiciales que deberían velar por la ciudadanía, no por los intereses más turbios de los ámbitos de poder.\n\nLa literatura suele entrar en el interior de las vidas para preguntarse por los sentimientos de los seres humanos ante los hechos públicos. El nuevo libro de Baltasar Garzón, La democracia amenazada (Planeta, 2026), hace el camino contrario. Parte de las situaciones vividas por él, por Dolores Delgado o por Álvaro García Ortiz, para reflexionar con una detallada sabiduría profesional sobre los deterioros de la convivencia democrática y las responsabilidades de los poderes que manipulan la justicia.\n\nTenía mucha razón Eugenio Raúl Zaffaroni, exjuez de la Corte Interamericana de Derechos Humanos, cuando afirmaba que el poder punitivo no es un fenómeno exclusivamente jurídico, sino esencialmente político. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-06-15/democracias-amenazadas.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 26,
    cat: "geopolitica",
    title: "Bélgica y la crisis nacional que acompaña la trayectoria de Thibaut Courtois",
    summary: "El portero del Real Madrid, superviviente de aquella selección que fue tercera en Rusia 2018, lidera una escuadra adicta a la polémica",
    body: "“Buenos días, san Tibú. ¿Cómo desea su santidad el huevo?”, le lanzó la prensa belga a Thibaut Courtois hace tres años, mosqueada con el portero, que acababa de abandonar una concentración con su país y no se presentó a un viaje a Estonia porque, en ausencia de Kevin De Bruyne, el brazalete de capitán era para Romelu Lukaku y no para él. El episodio abrió una crisis entre el meta y Los Diablos Rojos.\n\nMientras en el Real Madrid ha sido ungido en este ciclo mundialista como el mejor guardameta del planeta —y para algunos de la historia—, en Bélgica ha estado en la diana y bajo sospecha. “Estamos decepcionados”, reaccionó en público su excompañero Yannick Carrasco cuando sucedió aquello, en junio de 2023. “Sería raro que volviera como si no hubiera pasado nada”, apuntaló Timothy Castagne. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-06-15/belgica-y-la-crisis-nacional-que-acompana-la-trayectoria-de-thibaut-courtois.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 27,
    cat: "geopolitica",
    title: "Un pase al loco de la banda: Marcelo Bielsa lidera a Uruguay en el Mundial",
    summary: "Los charrúas se presentan en la Copa del Mundo más mercantilizado liderado por el argentino, el último gran filósofo del fútbol honesto.",
    body: "Uruguay tiene un tesoro en el banquillo . Los charrúas, herederos de una de las tradiciones más nobles de la Copa del Mundo , presentan un equipo muy digno, de Fernando Muslera a Fede Valverde, pasando por Giorgian de Arrascaeta o Darwin Núñez, pero no van a poder alinear en esta ocasión a figuras totémicas del calibre de un Obdulio Varela, un Diego Roldán, un Enzo Francescoli, un mariscal Nasazzi o un Juan Alberto Schiaffino.\n\nPor suerte, al mando de la nave cuentan con un estratega curtido en mil batallas, además de rapsoda y profeta. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-06-15/un-pase-al-loco-de-la-banda.html",
    time: "1 ora fa",
    pub_ts: 1781494201,
    tags: [],
  },
  {
    id: 28,
    cat: "conflitti",
    title: "Lebanese remain sceptical despite US-Iran ceasefire announcement",
    summary: "The US-Iran ceasefire announcement has raised hopes in Lebanon.",
    body: "The US-Iran ceasefire announcement has raised hopes in Lebanon.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/15/lebanese-remain-sceptical-despite-us-iran-ceasefire-announcement?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1781490366,
    tags: [],
  },
  {
    id: 29,
    cat: "conflitti",
    title: "US-Iran to sign a ‘peace deal’ on Friday: What we know so far",
    summary: "Trump says a US-Iran deal will be signed this Friday, as Tehran confirms plans to end hostilities.",
    body: "Trump says a US-Iran deal will be signed this Friday, as Tehran confirms plans to end hostilities.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/15/us-iran-to-sign-a-peace-deal-on-friday-what-we-know-so-far?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1781487647,
    tags: [],
  },
  {
    id: 30,
    cat: "conflitti",
    title: "Trump allies cheer Iran ‘peace deal’ announcement as Democrats seek clarity",
    summary: "US and Iran say memorandum of understanding to be signed on Friday, but no official terms yet released.",
    body: "US and Iran say memorandum of understanding to be signed on Friday, but no official terms yet released.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/15/trump-allies-cheer-iran-deal-announcement-as-democrats-call-for-clarity?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1781486009,
    tags: [],
  },
  {
    id: 31,
    cat: "conflitti",
    title: "Iran’s Ghalenoei, Taremi decry US treatment before first World Cup game",
    summary: "Striker Mehdi Taremi says US travel policies are dampening the usual joy the football tournament ignites.",
    body: "Striker Mehdi Taremi says US travel policies are dampening the usual joy the football tournament ignites.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/sports/2026/6/15/irans-ghalenoei-taremi-decry-us-treatment-before-first-world-cup-game?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1781484128,
    tags: [],
  },
  {
    id: 32,
    cat: "conflitti",
    title: "Stock markets soar, oil falls as US, Iran confirm deal to end war",
    summary: "Asian stock markets surge as Washington and Tehran announce agreement to end hostilities and reopen Strait of Hormuz.",
    body: "Asian stock markets surge as Washington and Tehran announce agreement to end hostilities and reopen Strait of Hormuz.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/economy/2026/6/15/stock-markets-soar-oil-falls-as-us-iran-confirm-deal-to-end-war?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1781483827,
    tags: [],
  },
  {
    id: 33,
    cat: "conflitti",
    title: "Claims Israel’s Beirut strike pushed Trump on Iran announcement",
    summary: "US diplomat Alan Eyre says despite the US-Iran ceasefire announcement, there is no deal until it has been formalised.",
    body: "US diplomat Alan Eyre says despite the US-Iran ceasefire announcement, there is no deal until it has been formalised.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/15/claims-israels-beirut-strike-pushed-trump-on-iran-announcement?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1781482527,
    tags: [],
  },
  {
    id: 34,
    cat: "conflitti",
    title: "BREAKING: US, Iran announce ceasefire agreement",
    summary: "US President Donald Trump has announced a ceasefire agreement with Iran.",
    body: "US President Donald Trump has announced a ceasefire agreement with Iran.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/14/breaking-us-iran-announce-ceasefire-agreement?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1781477676,
    tags: [],
  },
  {
    id: 35,
    cat: "conflitti",
    title: "US-Iran ‘peace deal’ announced; Trump says Strait of Hormuz reopening",
    summary: "Trump announces that a ceasefire deal with Iran has been agreed, and that the Strait of Hormuz will reopen for shipping.",
    body: "Trump announces that a ceasefire deal with Iran has been agreed, and that the Strait of Hormuz will reopen for shipping.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/14/us-iran-ceasefire-deal-announced-trump-says-strait-of-hormuz-reopening?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1781476999,
    tags: [],
  },
  {
    id: 36,
    cat: "conflitti",
    title: "Gaza mourns four killed in Israeli strike",
    summary: "Cries of grief echoed through Gaza City for four Palestinians killed near the Jabalia refugee camp in northern Gaza.",
    body: "Cries of grief echoed through Gaza City for four Palestinians killed near the Jabalia refugee camp in northern Gaza.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/14/gaza-mourns-four-killed-in-israeli-strike?traffic_source=rss",
    time: "8 ore fa",
    pub_ts: 1781470632,
    tags: [],
  },
  {
    id: 37,
    cat: "ai",
    title: "Intervista a Aneesh Raman: “La fine del vecchio lavoro non è la fine del lavoro”",
    summary: "A The Big Interview, il chief economic opportunity officer di LinkedIn riflette sull’impatto dell’intelligenza artificiale sul mercato occupazionale: meno fatalismo, più capacità umane e nuove forme di imprenditorialità",
    body: "A The Big Interview, il chief economic opportunity officer di LinkedIn riflette sull’impatto dell’intelligenza artificiale sul mercato occupazionale: meno fatalismo, più capacità umane e nuove forme di imprenditorialità",
    source: "Wired IT",
    url: "https://www.wired.it/article/intervista-aneesh-raman-lavoro-linkedin/",
    time: "8 min fa",
    pub_ts: 1781499600,
    tags: [],
  },
  {
    id: 38,
    cat: "ai",
    title: "Cosa succede quando la pioggia diventa un'incognita in agricoltura",
    summary: "Siamo stati in Ghana per capire come i dati climatici possono aiutare agricoltori e pastori ad affrontare stagioni sempre più irregolari",
    body: "Siamo stati in Ghana per capire come i dati climatici possono aiutare agricoltori e pastori ad affrontare stagioni sempre più irregolari",
    source: "Wired IT",
    url: "https://www.wired.it/article/cosa-succede-quando-pioggia-diventa-incognita-agricoltura/",
    time: "18 min fa",
    pub_ts: 1781499000,
    tags: [],
  },
  {
    id: 39,
    cat: "ai",
    title: "Dan Greaney, l’autore dei Simpson che aveva previsto l'ascesa di Trump si è candidato alla presidenza degli Stati Uniti",
    summary: "La mente dietro Bart al futuro, l’episodio dei Simpson che immaginava Trump presidente, ha lanciato la sua campagna elettorale per il 2028",
    body: "La mente dietro Bart al futuro, l’episodio dei Simpson che immaginava Trump presidente, ha lanciato la sua campagna elettorale per il 2028",
    source: "Wired IT",
    url: "https://www.wired.it/article/dan-greaney-autore-simpson-candidato-presidenza-stati-uniti/",
    time: "28 min fa",
    pub_ts: 1781498400,
    tags: [],
  },
  {
    id: 40,
    cat: "ai",
    title: "Ma quando abbiamo davvero imparato a usare il fuoco? Nuove indagini ci dicono che è successo almeno 1,8 milioni di anni fa",
    summary: "Lo studio, pubblicato sulle pagine di Plos One, si è focalizzato su alcuni resti provenienti dalla grotta di Wonderwerk, in Sudafrica",
    body: "Lo studio, pubblicato sulle pagine di Plos One, si è focalizzato su alcuni resti provenienti dalla grotta di Wonderwerk, in Sudafrica",
    source: "Wired IT",
    url: "https://www.wired.it/article/nuove-indagini-ci-dicono-che-abbiamo-iniziato-ad-usare-il-fuoco-almeno-1-8-milioni-di-anni-fa/",
    time: "38 min fa",
    pub_ts: 1781497800,
    tags: [],
  },
  {
    id: 41,
    cat: "ai",
    title: "Atlantis - L'impero perduto compie 25 anni e continua ad essere il più grande enigma della Disney",
    summary: "Il 15 giugno del 2001 debuttava il film di Gary Trousdale e Kirk Wise, fiasco terrificante al botteghino ma diventato con il tempo un cult",
    body: "Il 15 giugno del 2001 debuttava il film di Gary Trousdale e Kirk Wise, fiasco terrificante al botteghino ma diventato con il tempo un cult",
    source: "Wired IT",
    url: "https://www.wired.it/article/atlantis-l-impero-perduto-piu-grande-enigma-disney-storia-dove-vederlo/",
    time: "48 min fa",
    pub_ts: 1781497200,
    tags: [],
  },
  {
    id: 42,
    cat: "ai",
    title: "Orbio raises $21 million to automate hiring and onboarding for frontline workers",
    summary: "Orbio announces $21 Million Series A in round led by Dawn Capital.",
    body: "Orbio announces $21 Million Series A in round led by Dawn Capital.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/14/orbio-raises-21-million-to-automate-hiring-and-onboarding-for-frontline-workers/",
    time: "1 ora fa",
    pub_ts: 1781496060,
    tags: [],
  },
  {
    id: 43,
    cat: "ai",
    title: "Startup CEO Charlie Javice is reportedly angling for a Trump pardon",
    summary: "JPMorgan can't be pleased by any of this.",
    body: "JPMorgan can't be pleased by any of this.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/14/startup-ceo-charlie-javice-is-reportedly-angling-for-a-trump-pardon/",
    time: "7 ore fa",
    pub_ts: 1781474134,
    tags: [],
  },
  {
    id: 44,
    cat: "ai",
    title: "The FBI built a small town to simulate cyberattacks",
    summary: "Last year, the FBI opened a Cyber Range in Huntsville, Alabama, for simulating cyberattacks. Think of it sort of like the famous Hogan's Alley, but for modern digital crime training. It's a massive 22,000 square-foot replica of an entire town, complete with a convenience store, gas station, hospital, and even fully furnished houses. It's a [&#8230;]",
    body: "There’s also a fake power company to jack up prices thanks to the fake data center. | Image: FBI Last year, the FBI opened a Cyber Range in Huntsville, Alabama, for simulating cyberattacks. Think of it sort of like the famous Hogan's Alley , but for modern digital crime training. It's a massive 22,000 square-foot replica of an entire town, complete with a convenience store, gas station, hospital, and even fully furnished houses.\n\nIt's a training facility where the bureau can recreate real-world scenarios for training and research purposes. All of the various buildings and facilities are hooked up the way they would be in a real town. There's even a small data center with over 200 servers that can be hacked, infected with malware, and stu …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/949648/fbi-fake-town-cyberattacks-kinetic-cyber-range",
    time: "8 ore fa",
    pub_ts: 1781469341,
    tags: [],
  },
  {
    id: 45,
    cat: "ai",
    title: "UK may ban social media for children under 16",
    summary: "The U.K. seems to be following Australia's lead in banning a wide swath of social media for teens.",
    body: "The U.K. seems to be following Australia's lead in banning a wide swath of social media for teens.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/14/uk-may-ban-social-media-for-children-under-16/",
    time: "8 ore fa",
    pub_ts: 1781468220,
    tags: [],
  },
  {
    id: 46,
    cat: "ai",
    title: "China may have accessed Mythos",
    summary: "According to a new report from Semafor, the White House's decision to impose export restrictions on Anthropic's Mythos was driven in part by fears that it had been accessed by a group linked to China. If the Chinese government actually had access to Mythos 5 or Fable 5, it would present a serious national security [&#8230;]",
    body: "According to a new report from Semafor , the White House's decision to impose export restrictions on Anthropic's Mythos was driven in part by fears that it had been accessed by a group linked to China. If the Chinese government actually had access to Mythos 5 or Fable 5, it would present a serious national security risk. The government could also attempt to reverse engineer the model through distillation , a method in which a \"student\" AI is trained on a more advanced model to replicate its behavior.\n\nThe White House has not confirmed this report, and a post on X by Trump advisor David Sacks did not mention China. Instead, Sacks focused on a r …",
    source: "The Verge",
    url: "https://www.theverge.com/ai-artificial-intelligence/949644/china-white-house-anthropic-mythos",
    time: "10 ore fa",
    pub_ts: 1781461675,
    tags: [],
  },
  {
    id: 47,
    cat: "ai",
    title: "As AI companies race to go public, who else is along for the ride?",
    summary: "Startups are trying to \"ride that SpaceX IPO wave.\"",
    body: "Startups are trying to \"ride that SpaceX IPO wave.\"",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/14/as-ai-companies-race-to-go-public-who-else-is-along-for-the-ride/",
    time: "12 ore fa",
    pub_ts: 1781455089,
    tags: [],
  },
  {
    id: 48,
    cat: "ai",
    title: "Conclave is the sound of a NYC summer block party",
    summary: "I have this vivid memory of walking to pick up my oldest from school in June of 2022. For a variety of reasons, I was in a very bad place mentally. And to make matters worse, it was brutally hot. I was depressed, angry with the world, sunburned, and soaked through with sweat. But as [&#8230;]",
    body: "Unlock a party. | Image: Conclave I have this vivid memory of walking to pick up my oldest from school in June of 2022. For a variety of reasons, I was in a very bad place mentally. And to make matters worse, it was brutally hot. I was depressed, angry with the world, sunburned, and soaked through with sweat. But as the second track on Conclave, \"Habla,\" settled into its groove, I found myself unconsciously strutting.\n\nNot walking, but moving through the streets in lockstep with the music, just as a much-needed cool breeze kicked up, and some scaffolding afforded me a full block's worth of shade. For a brief moment, I found myself smiling for the first time in what felt like …",
    source: "The Verge",
    url: "https://www.theverge.com/entertainment/949621/conclave-nyc-summer-block-party-album-review",
    time: "12 ore fa",
    pub_ts: 1781454600,
    tags: [],
  },
  {
    id: 49,
    cat: "ai",
    title: "TechCrunch Mobility: SpaceX rockets past Tesla",
    summary: "Welcome back to TechCrunch Mobility, your hub for the future of transportation and now, more than ever, how AI is playing a part.",
    body: "Welcome back to TechCrunch Mobility, your hub for the future of transportation and now, more than ever, how AI is playing a part.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/14/techcrunch-mobility-spacex-rockets-past-tesla/",
    time: "13 ore fa",
    pub_ts: 1781453100,
    tags: [],
  },
  {
    id: 50,
    cat: "ai",
    title: "How to watch most of the World Cup matches with free trials",
    summary: "Hoping to catch some World Cup matches while spending as little money as possible? You have a few options for finding a few days of free streaming, although you may choose to eventually pony up some money. That, or get creative by combining multiple offers to make it through the whole tournament. We found a [&#8230;]",
    body: "GUADALAJARA, MEXICO - JUNE 11: In-Beom Hwang #6 of Korea Republic scores his team's first goal past Matej Kovar #1 of Czechia during the FIFA World Cup 2026 Group A match between Korea Republic and Czechia at Guadalajara Stadium on June 11, 2026 in Guadalajara, Mexico. (Photo by Lars Baron/Getty Images) | Getty Images Hoping to catch some World Cup matches while spending as little money as possible? You have a few options for finding a few days of free streaming, although you may choose to eventually pony up some money.\n\nThat, or get creative by combining multiple offers to make it through the whole tournament. We found a handful of streaming services that are showing all of the World Cup matches. Most of these free trials require you to be a new subscriber, though you might just be able to use a different email address than before. FuboTV All FuboTV plans can stream every World Cup match, and each includes a five-day free trial for new members.\n\nThe least expensive plan is $9.99 for the first month after the trial period, then $19.99 per month after that. Paying for one month after the trial should cover you through all (or most) of the finals, and is likely the least expensive way to watch every match. My Best Buy Plus and Total members can claim an extended 30-day free trial , as long as they’re new to FuboTV. FuboTV Where to Buy: $19.99 at FuboTV (five-day free trial) Peacock There’s a Peacock Premium Plus trial offer if you sign up using your Amazon account that will grant you seven days of free access before you’re charged $15.99 per month.\n\nI was able to access the offer on an Amazon account without Prime, but your mileage may vary. We also found multiple ways to potentially claim free Peacock through other paid subscriptions. Some Xfinity Internet plans include Peacock Premium, which you can learn more about on the company’s support page . Walmart Plus members can claim either Peacock Premium or Paramount Plus Essential, but only one at a time, with a 90-day cooldown between switching.\n\nPeacock Premium Plus Where to Buy: $16.99 at Amazon (seven-day free trial) YouTube TV New YouTube TV subscribers can access a 10-day trial for the Sports plan , which includes Fox and 35 other networks. After the trial, the membership will renew for $54.99 per month for the first year, a $10 per month discount from the normal membership. YouTube TV Where to Buy: $64.99 at YouTube (10-day free trial) Fox One The Fox One streaming service includes World Cup matches, and new subscribers can access a three-day free trial when signing up.\n\nAfter that, the plan costs $19.99 per month to continue watching, and includes both live and on-demand content from Fox. Fox One Where to Buy: $19.99 at Fox One (three-day free trial)",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/948871/world-cup-streaming-free-trial-deal-sale",
    time: "13 ore fa",
    pub_ts: 1781452800,
    tags: [],
  },
  {
    id: 51,
    cat: "ai",
    title: "The new Sonos Play has become my go-to desk and kitchen speaker",
    summary: "The new Sonos Play can act as a portable speaker inside and outside your home.",
    body: "The new Sonos Play can act as a portable speaker inside and outside your home.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/14/the-new-sonos-play-has-become-my-go-to-desk-and-kitchen-speaker/",
    time: "15 ore fa",
    pub_ts: 1781445600,
    tags: [],
  },
  {
    id: 52,
    cat: "ai",
    title: "The impossible dream of the universal remote",
    summary: "You don't really ever have to explain why a universal remote is a good idea. You have a bunch of stuff that needs controlling; this thing controls them all. Many companies have set out to build a product worthy of this idea, and one product came much closer than most. It was called the Harmony, [&#8230;]",
    body: "You don't really ever have to explain why a universal remote is a good idea. You have a bunch of stuff that needs controlling; this thing controls them all. Many companies have set out to build a product worthy of this idea, and one product came much closer than most. It was called the Harmony, and for many years it was the best universal remote on the market. Maybe the only one that mattered. And still, even the Harmony couldn't make it work.\n\nOn this episode of Version History , we tell the story of the Harmony. The Verge 's David Pierce, Nilay Patel, and John Higgins are joined by Matt Rogers , the CEO of Mill and former co-founder of Nest, …",
    source: "The Verge",
    url: "https://www.theverge.com/podcast/949620/harmony-universal-remote-version-history",
    time: "15 ore fa",
    pub_ts: 1781444527,
    tags: [],
  },
  {
    id: 53,
    cat: "ai",
    title: "Solid-state batteries still aren’t ready, but gels are",
    summary: "This is The Stepback, a weekly newsletter breaking down one essential story from the tech world. For more on e-bikes, power stations, and how to work anywhere, follow Thomas Ricker. The Stepback arrives in our subscribers' inboxes at 8AM ET. Opt in for The Stepback here. How it started Lithium-ion batteries are everywhere as we [&#8230;]",
    body: "This is The Stepback , a weekly newsletter breaking down one essential story from the tech world. For more on e-bikes, power stations, and how to work anywhere , follow Thomas Ricker . The Stepback arrives in our subscribers' inboxes at 8AM ET. Opt in for The Stepback here . How it started Lithium-ion batteries are everywhere as we enter the second quarter of the 21st century, and that's a problem.\n\nFrom exploding e-bikes in stairwells to lithium-ion power banks combusting midflight , the volatile nature of traditional liquid electrolytes has become an undeniable public safety hazard. In 2025, the US Consumer Product Safety Commission (CPSC) i …",
    source: "The Verge",
    url: "https://www.theverge.com/column/948594/solid-state-batteries-semi-solid-state",
    time: "17 ore fa",
    pub_ts: 1781438400,
    tags: [],
  },
  {
    id: 54,
    cat: "ai",
    title: "Frigoriferi senza congelatore, i 10 migliori modelli monoporta per conservare la spesa",
    summary: "Ci sono i minibar da ufficio ma anche i modelli standard per la cucina, a libera installazione e da incasso: 10 frigoriferi pronti a offrirti tutto lo spazio di cui hai bisogno per drink e cibi freschi",
    body: "Ci sono i minibar da ufficio ma anche i modelli standard per la cucina, a libera installazione e da incasso: 10 frigoriferi pronti a offrirti tutto lo spazio di cui hai bisogno per drink e cibi freschi",
    source: "Wired IT",
    url: "https://www.wired.it/gallery/migliori-frigoriferi-senza-congelatore-monoporta/",
    time: "22 ore fa",
    pub_ts: 1781420400,
    tags: [],
  },
  {
    id: 55,
    cat: "ai",
    title: "Cosa succede quando torni ad avere il controllo dello smartphone",
    summary: "È successo durante tre giorni di digital detox retreat in Val di Fassa, sotto la guida di Alessio Carciofi. Per capire come si fa a rimettere lo smartphone al suo posto",
    body: "È successo durante tre giorni di digital detox retreat in Val di Fassa, sotto la guida di Alessio Carciofi. Per capire come si fa a rimettere lo smartphone al suo posto",
    source: "Wired IT",
    url: "https://www.wired.it/article/digital-detox-cosa-succede-quando-torni-avere-controllo-smartphone/",
    time: "1 giorno fa",
    pub_ts: 1781413200,
    tags: [],
  },
  {
    id: 56,
    cat: "ai",
    title: "In Europa sempre più aziende e istituzioni stanno abbandonando le tecnologie statunitensi",
    summary: "L'inizio del secondo mandato di Trump è coinciso con un'accelerazione dei piani per la sovranità digitale europea: ecco tutte le realtà che si allontanano dalle big tech",
    body: "L'inizio del secondo mandato di Trump è coinciso con un'accelerazione dei piani per la sovranità digitale europea: ecco tutte le realtà che si allontanano dalle big tech",
    source: "Wired IT",
    url: "https://www.wired.it/article/europa-abbandona-tecnologie-big-tech-americane/",
    time: "1 giorno fa",
    pub_ts: 1781412600,
    tags: [],
  },
  {
    id: 57,
    cat: "economia-tech",
    title: "Hong Kong Leader Says He’s Yet to Consider Possible Second Term",
    summary: "Hong Kong Chief Executive John Lee remained non-committal about seeking a second term, deflecting questions regarding his political future ahead of the city’s leadership selection next year.",
    body: "Hong Kong Chief Executive John Lee remained non-committal about seeking a second term, deflecting questions regarding his political future ahead of the city’s leadership selection next year.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-15/hong-kong-leader-says-he-s-yet-to-consider-possible-second-term",
    time: "41 min fa",
    pub_ts: 1781497606,
    tags: [],
  },
  {
    id: 58,
    cat: "economia-tech",
    title: "Anthropic Block Marks US Reversal, Warning to Silicon Valley",
    summary: "The extraordinary move by the US to bar foreign access to Anthropic PBC’s best AI models underscores the Trump administration’s newfound willingness to exert control over a pivotal industry. It also reminds Silicon Valley that it’s working with an imperfectly understood technology with uncertain impact.",
    body: "The extraordinary move by the US to bar foreign access to Anthropic PBC’s best AI models underscores the Trump administration’s newfound willingness to exert control over a pivotal industry. It also reminds Silicon Valley that it’s working with an imperfectly understood technology with uncertain impact.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-15/anthropic-block-marks-us-reversal-warning-to-silicon-valley",
    time: "42 min fa",
    pub_ts: 1781497520,
    tags: [],
  },
  {
    id: 59,
    cat: "economia-tech",
    title: "Macron’s G7 Legacy Hangs on Fickle AI Funding and Data Centers",
    summary: "With less than a year left in office, Emmanuel Macron wants to be remembered as the French president who put Europe back in the technology race.",
    body: "With less than a year left in office, Emmanuel Macron wants to be remembered as the French president who put Europe back in the technology race.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-15/macron-s-g7-legacy-hangs-on-fickle-ai-funding-and-data-centers",
    time: "53 min fa",
    pub_ts: 1781496900,
    tags: [],
  },
  {
    id: 60,
    cat: "economia-tech",
    title: "Lessons from Ireland’s Revolut revolution",
    summary: "The fintech’s model is proving more suitable for international scaling than the often outdated systems of legacy rivals",
    body: "The fintech’s model is proving more suitable for international scaling than the often outdated systems of legacy rivals",
    source: "Financial Times",
    url: "https://www.ft.com/content/d46d909c-f7b1-4f3a-b953-61ce1516096b",
    time: "1 ora fa",
    pub_ts: 1781496026,
    tags: [],
  },
  {
    id: 61,
    cat: "economia-tech",
    title: "Ukrainian drone campaign chokes Moscow’s lifeline to Crimea",
    summary: "Fuel shortages are plaguing Russian-occupied peninsula that is ‘very easy to capture and very hard to keep’",
    body: "Fuel shortages are plaguing Russian-occupied peninsula that is ‘very easy to capture and very hard to keep’",
    source: "Financial Times",
    url: "https://www.ft.com/content/0ea7f48c-172c-443f-9896-1e77c2a8d065",
    time: "1 ora fa",
    pub_ts: 1781496026,
    tags: [],
  },
  {
    id: 62,
    cat: "economia-tech",
    title: "Asian stocks soar with ‘risk on’ rally after US-Iran peace deal",
    summary: "Investor euphoria following Friday’s record SpaceX IPO helps propel Japanese and Korean markets",
    body: "Investor euphoria following Friday’s record SpaceX IPO helps propel Japanese and Korean markets",
    source: "Financial Times",
    url: "https://www.ft.com/content/8a6849de-b27c-4680-a80d-42b85b0e77eb",
    time: "1 ora fa",
    pub_ts: 1781496025,
    tags: [],
  },
  {
    id: 63,
    cat: "economia-tech",
    title: "The populist case for ending easy money now",
    summary: "Why Kevin Warsh’s first big act at the Fed should be a rate hike",
    body: "Why Kevin Warsh’s first big act at the Fed should be a rate hike",
    source: "Financial Times",
    url: "https://www.ft.com/content/285ea07c-9781-44c8-ae22-55c1fd93af55",
    time: "1 ora fa",
    pub_ts: 1781496017,
    tags: [],
  },
  {
    id: 64,
    cat: "economia-tech",
    title: "Oil falls on US-Iran deal but Hormuz backlog may last weeks",
    summary: "Prices slip even as analysts warn flows may be slow to recover and remain vulnerable to renewed disruption",
    body: "Prices slip even as analysts warn flows may be slow to recover and remain vulnerable to renewed disruption",
    source: "Financial Times",
    url: "https://www.ft.com/content/c2d4e116-c49a-4f6b-9b2e-d10d37e4c2e8",
    time: "1 ora fa",
    pub_ts: 1781495998,
    tags: [],
  },
  {
    id: 65,
    cat: "economia-tech",
    title: "Iran and US agree deal to open Strait of Hormuz and extend ceasefire",
    summary: "Leaders to sign agreement on Friday for reopening of waterway and end to US naval blockade of Iranian ports",
    body: "Leaders to sign agreement on Friday for reopening of waterway and end to US naval blockade of Iranian ports",
    source: "Financial Times",
    url: "https://www.ft.com/content/76bed6e5-ab1f-43ff-a6c0-ae5e7cdbf3c1",
    time: "1 ora fa",
    pub_ts: 1781495703,
    tags: [],
  },
  {
    id: 66,
    cat: "economia-tech",
    title: "新SiriはアップルAI危機を救えるか、実機を試して見えた7つの改善例－Power On",
    summary: "アップルの新Siriは2年遅れで登場したものの、実用性が十分な水準に達し、AI戦略立て直しの足掛かりとなりつつある。",
    body: "アップルの新Siriは2年遅れで登場したものの、実用性が十分な水準に達し、AI戦略立て直しの足掛かりとなりつつある。",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/jp/news/newsletters/2026-06-15/TGNKC0RKV2VT00",
    time: "2 ore fa",
    pub_ts: 1781492401,
    tags: [],
  },
  {
    id: 67,
    cat: "economia-tech",
    title: "Trump stages show of political domination with White House UFC bout",
    summary: "US president hosts Maga mixed martial arts spectacle on his 80th birthday",
    body: "US president hosts Maga mixed martial arts spectacle on his 80th birthday",
    source: "Financial Times",
    url: "https://www.ft.com/content/11f71770-5872-4769-9ea5-a21f12151e10",
    time: "2 ore fa",
    pub_ts: 1781492030,
    tags: [],
  },
  {
    id: 68,
    cat: "economia-tech",
    title: "Top Banks Rush to Fill Chief AI Roles as Talent Jumps to Rivals",
    summary: "Banks from Sydney to London are racing to fill the senior role of chief AI officer, a job that barely existed a year ago. Those in the position, however, say it might not be around for long.",
    body: "Banks from Sydney to London are racing to fill the senior role of chief AI officer, a job that barely existed a year ago. Those in the position, however, say it might not be around for long.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-15/top-banks-rush-to-fill-chief-ai-roles-as-talent-jumps-to-rivals",
    time: "2 ore fa",
    pub_ts: 1781491014,
    tags: [],
  },
  {
    id: 69,
    cat: "economia-tech",
    title: "Activist Palliser Urges Taiwan Firm WUS to Privatize, Lift Value",
    summary: "Activist hedge fund Palliser Capital is urging Taiwanese company WUS Printed Circuit Co. to enhance shareholder value, including through a potential privatization, according to documents viewed by Bloomberg News.",
    body: "Activist hedge fund Palliser Capital is urging Taiwanese company WUS Printed Circuit Co. to enhance shareholder value, including through a potential privatization, according to documents viewed by Bloomberg News.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-15/activist-palliser-urges-taiwan-firm-wus-to-privatize-lift-value",
    time: "3 ore fa",
    pub_ts: 1781488871,
    tags: [],
  },
  {
    id: 70,
    cat: "economia-tech",
    title: "Anthropic scrambles after Trump administration freezes its top AI models",
    summary: "Export controls on Fable and Mythos raise doubts over how US will police the most powerful AI systems",
    body: "Export controls on Fable and Mythos raise doubts over how US will police the most powerful AI systems",
    source: "Financial Times",
    url: "https://www.ft.com/content/f6940d59-28f4-4ae4-a569-c6fc421e52b9",
    time: "5 ore fa",
    pub_ts: 1781480608,
    tags: [],
  },
  {
    id: 71,
    cat: "economia-tech",
    title: "South Korea’s Floundering Movie Business Turns to AI for Help",
    summary: "Two films built largely with generative AI tools are on view in South Korean theaters",
    body: "A employee pours popcorn at a snack bar at the CJ CGV Co. Yeouido branch movie theater in Seoul, South Korea, on Wednesday, May 25, 2016. CJ CGV is considering selling stakes in some of its units, including one in China, to help fund its ambitions of turning into one of the world's biggest operators of movie theaters, according to an executive. Photographer: SeongJoon Cho/Bloomberg",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/newsletters/2026-06-14/south-korea-s-floundering-movie-business-turns-to-ai-for-help",
    time: "5 ore fa",
    pub_ts: 1781479801,
    tags: [],
  },
  {
    id: 72,
    cat: "economia-tech",
    title: "What is in the US-Iran deal?",
    summary: "Agreement will extend ceasefire by 60 days, reopen the Strait of Hormuz and begin nuclear negotiations",
    body: "Agreement will extend ceasefire by 60 days, reopen the Strait of Hormuz and begin nuclear negotiations",
    source: "Financial Times",
    url: "https://www.ft.com/content/3bc9f664-dcad-4c2e-b745-91bb4e0fa934",
    time: "5 ore fa",
    pub_ts: 1781479060,
    tags: [],
  },
  {
    id: 73,
    cat: "economia-tech",
    title: "Trump settles for a truce of convenience with Iran",
    summary: "The US president promised ‘unconditional surrender’, but the Islamic republic survived with its leverage enhanced",
    body: "The US president promised ‘unconditional surrender’, but the Islamic republic survived with its leverage enhanced",
    source: "Financial Times",
    url: "https://www.ft.com/content/e51b0af8-40ed-4828-969d-fc8827e37551",
    time: "5 ore fa",
    pub_ts: 1781478897,
    tags: [],
  },
  {
    id: 74,
    cat: "economia-tech",
    title: "Donald Trump has cut off access to the world’s best AI model",
    summary: "America’s closest allies have been blocked from Anthropic’s Mythos",
    body: "America’s closest allies have been blocked from Anthropic’s Mythos",
    source: "The Economist Ec",
    url: "https://www.economist.com/business/2026/06/14/donald-trump-has-cut-off-access-to-the-worlds-best-ai-model",
    time: "10 ore fa",
    pub_ts: 1781463394,
    tags: [],
  },
  {
    id: 75,
    cat: "economia-tech",
    title: "Companies are scrambling to curtail soaring AI costs",
    summary: "The rage for tokenmaxxing is coming to an end",
    body: "The rage for tokenmaxxing is coming to an end",
    source: "The Economist Ec",
    url: "https://www.economist.com/business/2026/06/14/companies-are-scrambling-to-curtail-soaring-ai-costs",
    time: "11 ore fa",
    pub_ts: 1781457587,
    tags: [],
  },
  {
    id: 76,
    cat: "economia-tech",
    title: "Carney Says Anthropic Ban Shows Risk of Relying on Big AI Models",
    summary: "Prime Minister Mark Carney said the US export ban blocking all foreign access to Anthropic PBC’s latest artificial intelligence models underscores the risk of depending on just a handful of powerful AI tools.",
    body: "Prime Minister Mark Carney said the US export ban blocking all foreign access to Anthropic PBC’s latest artificial intelligence models underscores the risk of depending on just a handful of powerful AI tools.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-14/carney-says-anthropic-ban-shows-risk-of-relying-on-big-ai-models",
    time: "12 ore fa",
    pub_ts: 1781456520,
    tags: [],
  },
];
