// Generato automaticamente il 2026-06-21 21:21 UTC da scripts/fetch_news.py
// NON modificare manualmente: viene sovrascritto ogni ora dalla GitHub Action.
var NEWS_TIMESTAMP = 1782076894;

const RSS_SOURCES = [
  {
    "name": "ANSA",
    "url": "https://www.ansa.it/sito/ansait_rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Corriere",
    "url": "https://xml2.corrieredellasera.it/rss/homepage.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Il Post",
    "url": "https://www.ilpost.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Sky TG24",
    "url": "https://tg24.sky.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "AGI",
    "url": "https://www.agi.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Pagella Politica",
    "url": "https://pagellapolitica.it/feed",
    "cat": "politica-italiana"
  },
  {
    "name": "Facta",
    "url": "https://facta.news/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Valigia Blu",
    "url": "https://www.valigiablu.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Limes",
    "url": "https://www.limesonline.com/feed",
    "cat": "geopolitica"
  },
  {
    "name": "Internazionale",
    "url": "https://www.internazionale.it/feed/tutto",
    "cat": "geopolitica"
  },
  {
    "name": "BBC World",
    "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "AP",
    "url": "https://apnews.com/hub/world-news?output=rss",
    "cat": "geopolitica"
  },
  {
    "name": "The Economist",
    "url": "https://www.economist.com/international/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "El Pais",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "cat": "geopolitica"
  },
  {
    "name": "Reuters",
    "url": "https://feeds.reuters.com/reuters/worldNews",
    "cat": "conflitti"
  },
  {
    "name": "Al Jazeera",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "cat": "conflitti"
  },
  {
    "name": "AP conflitti",
    "url": "https://apnews.com/hub/wars-and-conflicts?output=rss",
    "cat": "conflitti"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/rss/index.xml",
    "cat": "ai"
  },
  {
    "name": "Wired IT",
    "url": "https://www.wired.it/feed/rss",
    "cat": "ai"
  },
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Post Tech",
    "url": "https://www.ilpost.it/tecnologia/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Sole 24 Ore",
    "url": "https://www.ilsole24ore.com/rss/economia.xml",
    "cat": "economia-tech"
  },
  {
    "name": "Bloomberg Tech",
    "url": "https://feeds.bloomberg.com/technology/news.rss",
    "cat": "economia-tech"
  },
  {
    "name": "Financial Times",
    "url": "https://www.ft.com/rss/home",
    "cat": "economia-tech"
  },
  {
    "name": "The Economist Ec",
    "url": "https://www.economist.com/business/rss.xml",
    "cat": "economia-tech"
  }
];

const NEWS = [
  {
    id: 1,
    cat: "politica-italiana",
    title: "Trump insiste: 'Meloni non ci ha difeso'. Il silenzio della premier",
    summary: "In mattinata in visita gli alpini: 'Avevo bisogno di un po' di sano orgoglio nazionale'",
    body: "In mattinata in visita gli alpini: 'Avevo bisogno di un po' di sano orgoglio nazionale'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/politica/2026/06/21/trump-insiste-meloni-non-ci-ha-difeso.-il-silenzio-della-premier_73e89765-3cf3-454d-ad46-dcf8b60f5847.html",
    time: "58 min fa",
    pub_ts: 1782073380,
    tags: [],
  },
  {
    id: 2,
    cat: "politica-italiana",
    title: "Il Tribunale di Tripoli condanna Almasri a 7 anni e 4 mesi",
    summary: "'Ha violato i diritti dei detenuti'. Il generale è al centro dello scontro tra Italia e Corte penale internazionale",
    body: "'Ha violato i diritti dei detenuti'. Il generale è al centro dello scontro tra Italia e Corte penale internazionale",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/cronaca/2026/06/21/il-tribunale-di-tripoli-condanna-almasri-a-7-anni-e-4-mesi_cd54aefd-7b36-4802-bd94-a5f368fa2f31.html",
    time: "2 ore fa",
    pub_ts: 1782066494,
    tags: [],
  },
  {
    id: 3,
    cat: "politica-italiana",
    title: "Medio Oriente: i colloqui Usa-Iran a Lucerna, Trump: 'Aprite Hormuz o bombardiamo'. Furia di Teheran",
    summary: "Media: 'La delegazione iraniana lascia i colloqui in protesta'. Un diplomatico a Axios smentisce: 'I colloqui sono ancora in corso'.&nbsp; Ghalibaf: 'Trump stia attento a quello che dice, il nostro esercito è pronto'",
    body: "Media: 'La delegazione iraniana lascia i colloqui in protesta'. Un diplomatico a Axios smentisce: 'I colloqui sono ancora in corso'.&nbsp; Ghalibaf: 'Trump stia attento a quello che dice, il nostro esercito è pronto'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/06/21/medio-oriente-i-colloqui-usa-iran-a-lucerna-trump-aprite-hormuz-o-bombardiamo._b65bfcbe-56b2-4ff6-ba80-6bdb7da45174.html",
    time: "3 ore fa",
    pub_ts: 1782063707,
    tags: [],
  },
  {
    id: 4,
    cat: "politica-italiana",
    title: "Fuoco incrociato tra Cepeda e de la Espriella a poche ore dal ballottaggio in Colombia",
    summary: "Scintille tra i due nelle ultime interviste concesse alla stampa. I seggi chiudono alle 23 in Italia, i risultati preliminari attesi verso l'una di notte in Italia",
    body: "Scintille tra i due nelle ultime interviste concesse alla stampa. I seggi chiudono alle 23 in Italia, i risultati preliminari attesi verso l'una di notte in Italia",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/06/21/fuoco-incrociato-tra-cepeda-e-de-la-espriella-a-poche-ore-dal-ballottaggio-in-colombia_18224ebe-bf96-4dff-b469-7805f42e76fa.html",
    time: "7 ore fa",
    pub_ts: 1782050078,
    tags: [],
  },
  {
    id: 5,
    cat: "politica-italiana",
    title: "Gli incendi contro Starmer e la rete russa che punta a destabilizzare il Regno Unito",
    summary: "Nel maggio 2025 tre incendi hanno colpito proprietà collegate al primo ministro britannico Keir Starmer. Secondo due inchieste pubblicate da BBC e Financial Times, gli incendi facevano parte di una più ampia campagna russa di sabotaggio, provocazione e disinformazione.",
    body: "Nel maggio 2025 tre incendi hanno colpito proprietà collegate al primo ministro britannico Keir Starmer: una Toyota che gli era appartenuta, un’abitazione a Islington dove aveva vissuto anni prima e la sua casa di famiglia a Kentish Town, affittata alla cognata dopo il trasferimento a Downing Street. Per quegli incendi, lunedì 15 giugno, al termine di un processo all’Old Bailey, due persone sono state giudicate colpevoli di cospirazione per commettere incendi dolosi.\n\nSi tratta di Roman Lavrynovych, 22 anni, cittadino ucraino residente a Londra, e Stanislav Carpiuc, 27 anni, cittadino romeno nato in Ucraina. Lavrynovych è stato condannato anche per due capi di incendio doloso con condotta imprudente rispetto al rischio per la vita. Venerdì il tribunale ha deciso le pene per i due: sette anni per Lavrynovych e due per Carpiuc. Secondo due inchieste pubblicate da BBC e Financial Times , gli incendi contro le proprietà legate a Starmer facevano parte di una più ampia campagna russa di sabotaggio, provocazione e disinformazione.\n\nAl centro delle ricostruzioni c’è un contatto Telegram anonimo, indicato in aula come “El Money” perché così era salvato nel telefono di Lavrynovych, ma noto sull’app con le iniziali “EL”. Secondo quanto emerso al processo e ricostruito dalle due testate, EL ha reclutato Lavrynovych online, lo ha istruito e gli ha promesso un pagamento per compiere gli incendi e farli finire nelle notizie. La BBC ha ricostruito la possibile identità di EL, indicando elementi che portano a Evgeny Lyukshin.\n\nSi tratta di un giovane diplomatico russo di 23 anni, figlio di un alto funzionario, formato in ambienti legati alla guerra dell’informazione. La BBC precisa però di non poter dimostrare con certezza che Lyukshin sia EL. Il Financial Times, basandosi su archivi Telegram, portafogli di criptovalute, prove processuali e interviste a funzionari occidentali, ha invece scritto che EL si trovava in Russia ed era strettamente allineato a NoName057(16), un gruppo di attivisti hacker filocremlino definito dal Dipartimento di Giustizia degli Stati Uniti come un progetto “autorizzato dallo Stato”.&nbsp; Secondo la BBC, Lavrynovych è stato reclutato da EL in un gruppo Telegram frequentato da ucraini a Londra in cerca di lavoro.\n\nDa lì è stato spinto verso azioni sempre più gravi: prima affissioni di manifesti, poi graffiti, infine incendi. La polizia britannica ha detto di non aver trovato una motivazione ideologica negli imputati né prove che sapessero di colpire proprietà collegate al primo ministro. La comandante Helen Flanagan, responsabile della divisione antiterrorismo della polizia di Londra, ha inoltre detto alla BBC che la sua unità non è riuscita a provare l’identità di EL o per chi lavorasse.&nbsp; Uno dei tasselli centrali delle inchieste è Direct Action UK, un presunto gruppo di estrema destra britannico attivo su Telegram e sui social.\n\nSecondo l’organizzazione Hope Not Hate , il gruppo era coordinato dalla Russia e veniva usato per fomentare violenza e odio nel Regno Unito. L’organizzazione ha ricostruito la rete di canali e account Telegram collegati alla sigla “EL”, usati per offrire denaro a chi era disposto a incendiare auto della polizia, diffondere manuali per esplosivi e armi stampate in 3D e spingere gli utenti ad attaccare cittadini non bianchi e moschee.&nbsp; Anche BBC e Financial Times descrivono Direct Action UK come parte della stessa operazione: per la BBC era stato creato online da operatori russi per provocare divisione nel Regno Unito, mentre per il Financial Times era amministrato da persone in Russia che usavano VPN per nascondere posizione e identità.\n\nLa rete non è rimasta solo online. Secondo Hope Not Hate, Direct Action UK attirò l’attenzione nel gennaio 2025 dopo una serie di graffiti contro moschee e centri culturali islamici a Londra, con slogan come “Remigration or die” (“ remigrazione o morte ”) e “ Stop immigration ” (“stop immigrazione”). Prima degli incendi contro le proprietà legate a Starmer, Lavrynovych era stato pagato per affiggere manifesti di Direct Action e inviarne le foto a EL.\n\nTra quei materiali c’era anche un manifesto anti-musulmano costruito per sembrare di origine indù, che EL aveva chiesto di affiggere a Southall, area di Londra con grandi comunità indù, sikh e musulmane. Le immagini furono poi diffuse online da un account Facebook sotto pseudonimo in gruppi frequentati da musulmani britannici, nel tentativo di creare una reazione artificiale e alimentare tensioni tra comunità.\n\nLa stessa rete, secondo le inchieste, agiva anche nella direzione opposta. Con il nome fittizio di Takbir Foundation, account legati a EL cercavano di reclutare persone per dipingere graffiti islamici in luoghi pubblici nel Regno Unito e, in alcuni messaggi, provavano a sollecitare violenza jihadista. Non era un sostegno reale a una causa religiosa: era una strategia di provocazione. Gli stessi circuiti cercavano di usare, a seconda del contesto, identità di estrema destra, islamiste o anti-islamiche per produrre immagini, vandalismi e contenuti da rilanciare online.\n\nCome scrive Hope Not Hate, chi controllava questi account non era mosso da simpatia ideologica verso l’estrema destra britannica, ma vedeva l’estrema destra come uno strumento utile per indebolire la coesione sociale del Regno Unito.&nbsp; Hope Not Hate collega Direct Action UK anche a un ecosistema più ampio di propaganda russa rivolto al pubblico britannico. L’organizzazione afferma di aver individuato una rete di sette canali di propaganda attivi nel 2024 e riconducibili a Rybar , media filogovernativo russo finanziato in passato dal gruppo Wagner e sanzionato da Stati Uniti e Regno Unito per interferenze elettorali.\n\nSei di questi canali furono aperti nell’agosto 2024, nei giorni successivi alle rivolte razziste seguite all’omicidio di tre bambine a Southport, e rilanciavano la narrazione dell’estrema destra secondo cui il Regno Unito sarebbe uno Stato fallito, ostile ai “nativi” e dominato da una giustizia “a due livelli”. La campagna di disinformazione è proseguita anche dopo gli incendi contro Starmer. Secondo la BBC , account basati in Russia diffusero la falsa teoria secondo cui i tre sospettati ucraini sarebbero stati sex worker coinvolti in uno scandalo personale con il primo ministro.\n\nLa storia era falsa: gli imputati non conoscevano personalmente Starmer e non erano sex worker. Eppure fu rilanciata da Tommy Robinson, figura dell’estrema destra anti-islam britannica già promossa da Direct Action UK, di recente rientrato dalla Russia e attivo con i suoi account anche durante i pogrom razzisti di Belfast di inizio giugno. Belfast, l&#8217;internazionale della violenza razzista e la solidarietà come pratica di lotta Intervenendo al G7 di Évian-les-Bains, Starmer ha detto che il caso mostra come il Regno Unito sia preso di mira da “attori” che vogliono sfruttare le divisioni interne e destabilizzare la democrazia.\n\nIl primo ministro ha collegato l’attacco al contesto più ampio della guerra russa contro l’Ucraina e ha detto che Londra affronta “ogni giorno” attacchi per procura dalla Russia. Negli stessi giorni, il governo britannico ha annunciato nuove sanzioni contro reti finanziarie russe e contro la flotta ombra usata da Mosca per esportare petrolio e gas naturale liquefatto. (Immagine anteprima via Flickr ) &nbsp;",
    source: "Valigia Blu",
    url: "https://www.valigiablu.it/starmer-incendi-regno-unito-sabotaggio-russia/",
    time: "1 giorno fa",
    pub_ts: 1781921400,
    tags: [],
  },
  {
    id: 6,
    cat: "geopolitica",
    title: "Resultados elecciones Colombia 2026, en vivo | Cierran las urnas en Colombia y comienza el conteo de votos para definir al nuevo presidente",
    summary: "El candidato ultraderechista De la Espriella partía con ventaja en todas las encuestas tras ganar la primera vuelta al izquierdista Cepeda. Petro, tras votar: “Rechazo la injerencia de mandatarios extranjeros”",
    body: "Las urnas en Colombia han cerrado a las 4 de la tarde e inmediatamente ha comenzado el conteo de votos para definir al nuevo presidente de Colombia, entre el candidato de ultraderecha Abelardo de la Espriella y el senador de izquierda Iván Cepeda . El presidente Gustavo Petro hizo un llamado para que los ciudadanos voten a conciencia y pidió calma para recibir los resultados: “Después de votar, les solicito máxima tranquilidad y sabiduría”.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/america-colombia/elecciones-presidenciales/2026-06-21/resultados-elecciones-colombia-2026-en-vivo-la-segunda-vuelta-presidencial.html",
    time: "3 min fa",
    pub_ts: 1782076671,
    tags: [],
  },
  {
    id: 7,
    cat: "geopolitica",
    title: "Bélgica - Irán, el partido del Mundial 2026 en directo | Bélgica e Irán empatan y ambas están obligadas a ganar en la última jornada",
    summary: "La selección belga, que tuvo numerosas ocasiones y acabó con un futbolista menos, se estrelló contra el guardameta Beiranvand | Taremi marcó para la selección iraní, pero su tanto fue anulado por fuera de juego",
    body: "Bélgica e Irán están empatando este domingo en la segunda jornada del Grupo G del Mundial 2026 . Los primeros minutos fueron un asedio total del combinado europeo, pero una vez sacudida la presión, la selección iraní se acercó más al gol. Primero Courtois evitó un disparo a bocajarro y después Taremi vio cómo el VAR le anulaba un gol por un fuera de juego muy justo. La pausa de hidratación le vino muy bien a Bélgica, que acabó mucho mejor el primer acto, aunque no generó demasiado peligro.\n\nUn peligro que sí llegó constantemente en el inicio del segundo tiempo. La más clara fue un disparo de De Cuyper a escasos metros de la portería iraní que detuvo Beiranvand. Pero cuando mejor estaba Bélgica llegó la expulsión de Ngoy tras perder un balón siendo el último hombre y derribar a Taremi. Aún así los de Rudi García insistieron en ataque, pero Beiranvand fue demasiado. Las dos selecciones están obligadas a ganar en la última jornada para clasificar a dieciseisavos.",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-06-21/belgica-iran-en-directo-el-partido-del-grupo-g-del-mundial-2026-en-vivo.html",
    time: "14 min fa",
    pub_ts: 1782076009,
    tags: [],
  },
  {
    id: 8,
    cat: "geopolitica",
    title: "Trump and Iran's negotiator trade warnings as talks held in Switzerland",
    summary: "The US president, who is not at the talks, threatens to attack Iran if it does not restrain Hezbollah in Lebanon.",
    body: "The US president, who is not at the talks, threatens to attack Iran if it does not restrain Hezbollah in Lebanon.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cwy0q41v1lzo?at_medium=RSS&at_campaign=rss",
    time: "1 ora fa",
    pub_ts: 1782070389,
    tags: [],
  },
  {
    id: 9,
    cat: "geopolitica",
    title: "La crisis en Líbano y nuevas amenazas de Trump tensan la negociación entre EE UU e Irán en Suiza",
    summary: "Las delegaciones de ambos países se reúnen con los mediadores, Qatar y Pakistán, para intentar avanzar en un acuerdo de paz definitivo",
    body: "Las conversaciones entre Estados Unidos e Irán han entrado en una nueva fase en busca de un acuerdo de paz definitivo tras el memorándum de entendimiento suscrito por ambas partes esta semana. Las negociaciones que han arrancado este domingo en el complejo hotelero de Bürgenstock, en el centro de Suiza, corren el riesgo de descarrilar antes de comenzar por los sonoros ecos de las amenazas vertidas por Donald Trump, lo que refleja la fragilidad del alto el fuego entre los dos países.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-21/estados-unidos-e-iran-se-disponen-a-iniciar-la-negociacion-de-un-acuerdo-definitivo-en-suiza.html",
    time: "2 ore fa",
    pub_ts: 1782068323,
    tags: [],
  },
  {
    id: 10,
    cat: "geopolitica",
    title: "España despierta con Lamine y golea a Arabia Saudí",
    summary: "El azulgrana marca el primer gol de la Roja en el Mundial y reaviva a un equipo que estuvo lento y pesado en su estreno y que se reivindicó con un tono más vivo y un doblete de Oyarzabal",
    body: "España esperaba a Lamine. El Mundial esperaba a Lamine . Y ya está aquí. Le bastó el primer cuarto contra Arabia Saudí para despachar una función a la altura de las expectativas que le habían precedido en un torneo que vibra desde que aparece a calentar. Marcó, agitó, entretuvo y despertó a la Roja después del desconcertante chasco del estreno contra Cabo Verde. Vuelven a mirar el Mundial con los ojos de la ilusión.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-06-21/espana-despierta-con-lamine-y-golea-a-arabia-saudi.html",
    time: "2 ore fa",
    pub_ts: 1782066651,
    tags: [],
  },
  {
    id: 11,
    cat: "geopolitica",
    title: "El Gobierno alemán cierra un acuerdo con los talibanes para deportar a delincuentes convictos a Afganistán",
    summary: "El pacto permitirá fletar hasta tres vuelos de deportación cada mes y expulsar a un número ilimitado de inmigrantes",
    body: "El Gobierno alemán ha llegado a un acuerdo con el régimen de los talibanes para acelerar la deportación de delincuentes convictos a Afganistán, ha informado este domingo el diario germano Bild . Tras negociaciones “a nivel técnico”, puesto que Berlín no reconoce a los talibanes como Gobierno legítimo, se ha alcanzado un pacto que permitirá fletar hasta tres vuelos chárter de deportación cada mes, así como realizar un número ilimitado de deportaciones individuales en vuelos regulares.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-21/el-gobierno-aleman-cierra-un-acuerdo-con-los-talibanes-para-deportar-a-delincuentes-convictos-a-afganistan.html",
    time: "4 ore fa",
    pub_ts: 1782060874,
    tags: [],
  },
  {
    id: 12,
    cat: "geopolitica",
    title: "Half of France under red heat alert as alcohol banned at street music festival",
    summary: "Temperatures are forecast to peak on Monday, and authorities warn they could match historic highs.",
    body: "Temperatures are forecast to peak on Monday, and authorities warn they could match historic highs.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cgmdw4vn7y2o?at_medium=RSS&at_campaign=rss",
    time: "5 ore fa",
    pub_ts: 1782055334,
    tags: [],
  },
  {
    id: 13,
    cat: "geopolitica",
    title: "Starmer planea dimitir este mismo lunes y permitir que el exalcalde de Mánchester sea el nuevo primer ministro",
    summary: "El diario ‘The Observer’ ha adelantado la posible decisión del jefe de Gobierno. Donald Trump ha dado por sentada la renuncia en la red social Truth",
    body: "Keir Starmer ha decidido rendirse y planea anunciar su dimisión como primer ministro del Reino Unido este lunes, según ha adelantado el diario The Observer y da ya por sentado este domingo la mayoría de la prensa británica. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-06-21/starmer-planea-dimitir-este-mismo-lunes-y-permitir-que-el-exalcalde-de-manchester-sea-el-nuevo-primer-ministro.html",
    time: "6 ore fa",
    pub_ts: 1782054494,
    tags: [],
  },
  {
    id: 14,
    cat: "geopolitica",
    title: "El peligroso populismo judicial de Peinado",
    summary: "Si el juez cree realmente que Begoña Gómez puede convertirse en una prófuga de la justicia, el problema trasciende cualquier recurso ante la Audiencia de Madrid o queja ante el CGPJ",
    body: "Es peligroso que haya políticos que recurran a las teorías de la conspiración cuando se ven acosados por la justicia. Pero también lo es que haya jueces empeñados en darles la razón. El juez Juan Carlos Peinado entró en esa categoría hace ya demasiado tiempo , incurriendo en una suerte de populismo judicial: aquel que sustituye la prudencia exigible a un instructor por resoluciones concebidas para causar impacto público.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-21/el-peligroso-populismo-judicial-de-peinado.html",
    time: "7 ore fa",
    pub_ts: 1782049398,
    tags: [],
  },
  {
    id: 15,
    cat: "geopolitica",
    title: "Low-key funeral held for giant of the art world David Hockney",
    summary: "The artist, who passed away at his home in London earlier this month, requested just his partner and great-nephew attend.",
    body: "The artist, who passed away at his home in London earlier this month, requested just his partner and great-nephew attend.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/cn8q6wxy706o?at_medium=RSS&at_campaign=rss",
    time: "8 ore fa",
    pub_ts: 1782047329,
    tags: [],
  },
  {
    id: 16,
    cat: "geopolitica",
    title: "Marc Márquez logra su segundo triunfo de la temporada en el Gran Premio de la República Checa",
    summary: "El defensor de la corona se exprime al máximo para superar al ‘poleman’ Ai Ogura y su compañero Pecco Bagnaia y se sitúa de nuevo en la pomada por el título",
    body: "Con los líderes de Aprilia lamiéndose todavía las heridas, Marc Márquez volvió a presumir de su tremendo instinto competitivo para dar otro golpe al Mundial de MotoGP, cuando todavía está lejos de encontrarse en plenas facultades físicas. El heptacampeón de la categoría reina, tirando de veteranía y mucha sangre fría, se exhibió en el GP de la República Checa para conseguir su segunda victoria del año por delante de Ai Ogura y Pecco Bagnaia y reengancharse definitivamente a la batalla por el título.\n\nAntes de estrenarse en la cita anterior en Hungría semanas después de su enésima intervención quirúrgica en el brazo derecho, el piloto catalán llegó a verse a más de 100 puntos del líder Marco Bezzecchi, que este domingo tuvo que morderse las uñas dentro del garaje, castigado sin competir tras su cruce de cables en la víspera con un comisario de pista . Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/motociclismo/2026-06-21/marc-marquez-lograr-su-segundo-triunfo-de-la-temporada-en-el-gran-premio-de-la-republica-checa.html",
    time: "8 ore fa",
    pub_ts: 1782045986,
    tags: [],
  },
  {
    id: 17,
    cat: "geopolitica",
    title: "Zetak, apoteosis musical en San Mamés: nunca habíamos visto una cosa igual",
    summary: "El suyo es un discurso de amor a las enseñanzas de nuestros mayores, respeto al medioambiente, solidaridad con la inmigración, reivindicación de lo autóctono y amor militante por las lenguas minoritarias",
    body: "Pello Reparaz no necesita ninguna casita en su lenguaje escenográfico, porque lo suyo no son cuatro paredes y un parterre, sino un universo entero. El día que los exégetas del conejo malote y la beata de Sant Esteve Sesrovires descubran la existencia de Zetak no van a tener, a poco que apliquemos el criterio de proporcionalidad, ni papel suficiente ni límites para el dichoso scroll . Lo que ha sido capaz de concebir y materializar este navarro de 36 años, proveniente de una familia sin atisbo de tradición artística y que sigue viviendo en el mismo pueblito de 1.100 habitantes (Arbizu) que le vio crecer, no conoce parangón con cualquiera de los grandes espectáculos de la música popular que nos puedan venir a la cabeza, ni siquiera quienes acreditamos algún que otro trienio de antigüedad en ese hábito irrenunciable.\n\nNos referimos a todo lo que tiene que ver con el concepto escénico, el desarrollo, la emoción sin descanso, esa inventiva para volarnos la cabeza y abocarnos a una pregunta de respuesta siempre inverosímil: cómo pueden estar aconteciendo, durante dos horas y 45 minutos, hasta entradísima la madrugada, toda esa avalancha de episodios asombrosos. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/cultura/2026-06-21/zetak-apoteosis-musical-en-san-mames-nunca-habiamos-visto-una-cosa-igual.html",
    time: "9 ore fa",
    pub_ts: 1782041095,
    tags: [],
  },
  {
    id: 18,
    cat: "geopolitica",
    title: "Indian cricketer, 15, hits record-breaking 50 in just 11 balls",
    summary: "Vaibhav Sooryavanshi breaks the record for the fastest 50-over List A half-century in history on the same day he was not included in India's one-day international squad.",
    body: "Vaibhav Sooryavanshi breaks the record for the fastest 50-over List A half-century in history on the same day he was not included in India's one-day international squad.",
    source: "BBC World",
    url: "https://www.bbc.com/sport/cricket/articles/czdev6lp8p9o?at_medium=RSS&at_campaign=rss",
    time: "10 ore fa",
    pub_ts: 1782040221,
    tags: [],
  },
  {
    id: 19,
    cat: "geopolitica",
    title: "Fuel sales halted in occupied Crimea as Ukraine targets oil facilities",
    summary: "Fuel had already been rationed due to shortages caused by Kyiv's attacks against supply routes in Russian-occupied territories.",
    body: "Fuel had already been rationed due to shortages caused by Kyiv's attacks against supply routes in Russian-occupied territories.",
    source: "BBC World",
    url: "https://www.bbc.com/news/articles/clyx2lk9d15o?at_medium=RSS&at_campaign=rss",
    time: "10 ore fa",
    pub_ts: 1782039305,
    tags: [],
  },
  {
    id: 20,
    cat: "geopolitica",
    title: "Alejandro Sanz cautiva con la nostalgia en su concierto en Madrid",
    summary: "El cantautor español congrega a 55.000 personas en el estadio Metropolitano en una noche marcada por sus grandes éxitos, que resisten en el presente",
    body: "Minutos antes de las 21.00 apareció, guitarra en brazo, vestido de negro, cadenita al cuello y gafas de sol, en lo alto de una escalera. El rugido que salió de las 55.000 almas que abarrotaban el estadio Metropolitano de Madrid es el que consiguen despertar solo las grandes estrellas. Y Alejandro Sanz (Madrid, 57 años) lo conoce perfectamente. Su historia con la capital española es una historia de idilio.\n\nFue ahí donde se disparó su carrera en 2001 con un concierto en el estadio Vicente Calderón abarrotado de público, algo hasta entonces solo al alcance de los Rolling Stones. Y ahí también, en el mismo escenario 16 años después, despidió la historia musical del emblemático campo antes de ser demolido , con un homenaje a su álbum Más , el disco español más vendido de la historia —2,2 millones de copias en España—.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/cultura/2026-06-21/alejandro-sanz-cautiva-con-la-nostalgia-en-su-concierto-en-madrid.html",
    time: "11 ore fa",
    pub_ts: 1782037140,
    tags: [],
  },
  {
    id: 21,
    cat: "geopolitica",
    title: "El Poder Judicial estudia abrir un expediente disciplinario al juez Peinado por afirmar que la Policía puede ayudar a huir a Begoña Gómez",
    summary: "El Consejo se reunirá el lunes para debatir la propuesta de la presidenta de actuar contra el magistrado. La defensa de la esposa de Pedro Sánchez denuncia al juez ante el CGPJ por no notificarle la apertura de juicio oral y la retirada del pasaporte",
    body: "La imposición de severas medidas cautelares sobre la esposa del presidente del Gobierno, Begoña Gómez, causó este sábado estupefacción entre el Ejecutivo, el PSOE y algunos sectores de los operadores jurídicos; pero uno de los argumentos empleados por el juez Juan Carlos Peinado para justificar esa decisión -que los policías que ejercen de escolta de Gómez podrían ayudarla a fugarse de España - ha sembrado perplejidad incluso en el Consejo General del Poder Judicial (CGPJ), habitualmente poco proclive a poner en cuestión actuaciones judiciales.\n\nSu presidenta, Isabel Perelló, ha propuesto debatir si se ordena a la autoridad disciplinaria del Consejo que abra un expediente al magistrado por esas afirmaciones, incorporadas en el auto con el que comunicó la apertura de juicio oral a Gómez y la retirada del pasaporte, la prohibición de salir de España y la obligación de comparecer cada 14 días en el juzgado. Fuentes del CGPJ han señalado que Perelló había convocado a la comisión permanente, el principal órgano dedecisión tras el el pleno, a una reunión online para este domingo a las 10.00 pero, finalmente, decidió aplazarla para hacerla el lunes a las 9.00 de forma presencial con el fin de facilitar el debate.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-06-21/el-cgpj-estudia-abrir-un-expediente-disciplinario-al-juez-peinado-por-afirmar-que-la-policia-puede-ayudar-a-huir-a-begona-gomez.html",
    time: "12 ore fa",
    pub_ts: 1782032652,
    tags: [],
  },
  {
    id: 22,
    cat: "geopolitica",
    title: "El segundo ‘round’ del ‘caso Andic’",
    summary: "Un año y medio después, el fallecimiento del fundador de Mango sigue bajo investigación, con la defensa de su hijo Jonathan peleando por el relato y una posible implicación de terceras personas",
    body: "Jonathan Andic (45 años) cruzó el umbral de acceso a los juzgados de Martorell el 19 de mayo cabizbajo, esposado y escoltado por cinco policías. En el patio interior de los bloques de pisos que cobijan la sede del tribunal, las lamas de plástico de las ventanas y la persiana metálica de los bajos blindaban la escena frente al enjambre de periodistas que intentaban captar lo que ocurría dentro. Andic salió libre pero con una fianza de un millón de euros para evitar la cárcel, como sospechoso de l homicidio de su padre: el fundador de Mango, Isak Andic.\n\nAhora comienza el turno de la defensa, decidida a desmontar una investigación construida por indicios, contradicciones y periciales técnicas, sin una prueba directa de lo que ocurrió. Arranca así el segundo round del caso Andic, que se libra tanto en los juzgados como fuera de ellos. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/catalunya/2026-06-21/el-segundo-round-del-caso-andic.html",
    time: "13 ore fa",
    pub_ts: 1782027451,
    tags: [],
  },
  {
    id: 23,
    cat: "geopolitica",
    title: "El “paso importante” que sella el deshielo entre España y México",
    summary: "La reunión del próximo jueves en el Palacio Nacional entre Sheinbaum y Felipe VI supone el broche definitivo a la normalización de relaciones diplomáticas tras siete años",
    body: "La reunión del próximo jueves en el Palacio Nacional supone el broche definitivo a la normalización de relaciones diplomáticas entre México y España. Será un encuentro breve, pero envuelto en todos los códigos de una visita de Estado. La presidenta mexicana, Claudia Sheinbaum, invitó en marzo al rey Felipe VI a asistir al primer partido de la selección española en suelo mexicano, en la ciudad de Guadalajara.\n\nEn ese contexto llegó esta semana una segunda invitación, esta vez a un encuentro bilateral. Ha sido una secuencia de pasos diplomáticos, muy volcada en los gestos dentro de la esfera cultural, que cierra la etapa de ruptura iniciada en 2019 por la polémica carta del expresidente Andrés Manuel López Obrador pidiendo un gesto de perdón al rey por la Conquista y el rechazo de la carta por parte del Gobierno español.\n\nEl Mundial de fútbol, del que México es coorganizador, será el escenario final de unas paces que llevan fraguándose casi desde la victoria electoral de Sheinbaum hace dos años. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/mexico/2026-06-21/el-paso-importante-que-sella-el-deshielo-entre-espana-y-mexico.html",
    time: "17 ore fa",
    pub_ts: 1782014820,
    tags: [],
  },
  {
    id: 24,
    cat: "geopolitica",
    title: "Las claves de la elección en Colombia: la fuerza real de la ultraderecha, el apoyo a las reformas o el peso de las regiones",
    summary: "Además de definir el presidente, la votación de este domingo marcará un nuevo panorama político en Colombia",
    body: "Con la definición de quién será el próximo presidente de Colombia, la votación presidencial de este domingo definirá varios elementos clave del sistema político colombiano, en su transición de un bipartidismo estable durante el siglo XX a un futuro incierto. Estas son las principales. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/america-colombia/elecciones-presidenciales/2026-06-21/las-claves-de-la-eleccion-en-colombia-la-fuerza-real-de-la-ultraderecha-el-apoyo-a-las-reformas-o-el-peso-de-las-regiones.html",
    time: "17 ore fa",
    pub_ts: 1782014400,
    tags: [],
  },
  {
    id: 25,
    cat: "geopolitica",
    title: "Viaje a la economía más disparatada de Europa",
    summary: "Un puñado de multinacionales ha hundido un 12% el PIB de Irlanda y ha arrastrado a la zona euro a terreno negativo, pero no se lo crean demasiado: esta isla es el paradigma del abismo entre las cifras macro y la realidad",
    body: "Si un periodista llega a Dublín para escribir un reportaje sobre la recesión, es mala suerte toparse con Agustín López, un sumiller argentino de Mendoza que se mudó a la ciudad cuatro meses atrás y encontró trabajo exactamente a los tres días de llegar, sin hablar inglés ni tener experiencia previa detrás de una barra, en uno de los locales con más solera de Temple Bar, la mítica zona de pubs de la capital irlandesa.\n\nLópez, de 25 años, se formó en el mundo del vino y trabajó en bodegas en su tierra natal, pero quería aprender de whisky y por eso hizo las maletas. Ahora estudia las revistas especializadas en los ratos muertos, que son muy pocos, porque en esa casa llena de recovecos y referencias literarias se bebe sin tregua, desde la mañana hasta la noche. Nativos y extranjeros. Cero quejas, las cuentas le salen: “Son 2.200 euros en sueldo, pero las propinas pueden ser 100 más un día cualquiera, tal vez 200 uno muy bueno”, explica.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/economia/2026-06-21/viaje-a-la-economia-mas-disparatada-de-europa.html",
    time: "17 ore fa",
    pub_ts: 1782013501,
    tags: [],
  },
  {
    id: 26,
    cat: "conflitti",
    title: "What are the end goals of Iran-US negotiations?",
    summary: "Professor and political analyst Mahjoub Zweiri breaks down what intentions behind US-Iran talks will result in.",
    body: "Professor and political analyst Mahjoub Zweiri breaks down what intentions behind US-Iran talks will result in.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/what-are-the-end-goals-of-iran-us-negotiations?traffic_source=rss",
    time: "22 min fa",
    pub_ts: 1782075562,
    tags: [],
  },
  {
    id: 27,
    cat: "conflitti",
    title: "Mourners gather to remember Lebanese conservationist killed by Israel",
    summary: "People gathered in Beirut in memory of beloved turtle conservationist Mona Khalil, killed in Israeli attack.",
    body: "People gathered in Beirut in memory of beloved turtle conservationist Mona Khalil, killed in Israeli attack.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/21/mourners-gather-to-remember-lebanese-conservationist-killed-by-israel?traffic_source=rss",
    time: "59 min fa",
    pub_ts: 1782073319,
    tags: [],
  },
  {
    id: 28,
    cat: "conflitti",
    title: "Remembering Al Jazeera cameraman Ahmed Wishah’s life’s work",
    summary: "Al Jazeera cameraman Ahmed Wishah dedicated his life to documenting life in Gaza before he was killed by Israel.",
    body: "Al Jazeera cameraman Ahmed Wishah dedicated his life to documenting life in Gaza before he was killed by Israel.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/remembering-al-jazeera-cameraman-ahmed-wishahs-lifes-work?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1782072708,
    tags: [],
  },
  {
    id: 29,
    cat: "conflitti",
    title: "Displaced Lebanese inspect shattered Nabatieh after Israel halts attacks",
    summary: "Displaced residents returned to Nabatieh after Israel ordered a halt to fighting in southern Lebanon.",
    body: "Displaced residents returned to Nabatieh after Israel ordered a halt to fighting in southern Lebanon.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/displaced-lebanese-inspect-shattered-nabatieh-after-israel-halts-attacks?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1782072280,
    tags: [],
  },
  {
    id: 30,
    cat: "conflitti",
    title: "Colombia elections take place as Abelardo de la Espriella leads polls",
    summary: "Colombians are voting in an election where senator Ivan Cepeda is racing against Abelardo de la Espriella.",
    body: "Colombians are voting in an election where senator Ivan Cepeda is racing against Abelardo de la Espriella.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/colombia-elections-take-place-as-abelardo-de-la-espriella-leads-polls?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1782071880,
    tags: [],
  },
  {
    id: 31,
    cat: "conflitti",
    title: "What’s next in the Strait of Hormuz crisis?",
    summary: "Iranian armed forces say they&#039;ve closed the vital waterway after Israeli attacks on Lebanon.",
    body: "Iranian armed forces say they&#039;ve closed the vital waterway after Israeli attacks on Lebanon.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/inside-story/2026/6/21/whats-next-in-the-strait-of-hormuz-crisis?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1782063387,
    tags: [],
  },
  {
    id: 32,
    cat: "conflitti",
    title: "Ethiopian prime minister’s party easily wins parliamentary election",
    summary: "Nobel Peace Prize winner PM Abiy Ahmed will stay in power, as analysts warn of renewed conflicts in Ethiopia.",
    body: "Nobel Peace Prize winner PM Abiy Ahmed will stay in power, as analysts warn of renewed conflicts in Ethiopia.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/21/ethiopian-prime-ministers-party-easily-wins-parliamentary-election?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1782061672,
    tags: [],
  },
  {
    id: 33,
    cat: "conflitti",
    title: "Khamenei’s MoU stance stirs debate as Iran and US meet in Switzerland",
    summary: "Supreme leader has expressed reservations about interim deal with US, but most top decision-makers back it.",
    body: "Supreme leader has expressed reservations about interim deal with US, but most top decision-makers back it.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/21/khameneis-mou-stance-stirs-debate-as-iran-and-us-meet-in-switzerland?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1782061310,
    tags: [],
  },
  {
    id: 34,
    cat: "conflitti",
    title: "Iran, US, Israel: Memorandum of misunderstanding?",
    summary: "Chances are slim for progress between Iran and the US, argues Drop Site News co-founder Jeremy Scahill.",
    body: "Chances are slim for progress between Iran and the US, argues Drop Site News co-founder Jeremy Scahill.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/the-bottom-line/2026/6/21/iran-us-israel-memorandum-of-misunderstanding?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1782060571,
    tags: [],
  },
  {
    id: 35,
    cat: "conflitti",
    title: "Syria frees activist Hassan Akkad days after he was detained",
    summary: "His release comes after journalist Mousa al-Omar reportedly withdrew a complaint against Akkad over online criticism.",
    body: "His release comes after journalist Mousa al-Omar reportedly withdrew a complaint against Akkad over online criticism.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/21/syria-frees-activist-hassan-akkad-days-after-he-was-detained?traffic_source=rss",
    time: "5 ore fa",
    pub_ts: 1782057364,
    tags: [],
  },
  {
    id: 36,
    cat: "conflitti",
    title: "Mbappe, France play Iraq in World Cup match: prediction, team news, lineups",
    summary: "Star forward Kylian Mbappe and France face Iraq with Les Bleus focused on securing a place in knockout phase.",
    body: "Star forward Kylian Mbappe and France face Iraq with Les Bleus focused on securing a place in knockout phase.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/sports/2026/6/21/mbappe-france-play-iraq-in-world-cup-match-prediction-team-news-lineups?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1782055064,
    tags: [],
  },
  {
    id: 37,
    cat: "conflitti",
    title: "US-Iran negotiations in Switzerland kick off",
    summary: "US-Iran talks opened in Switzerland with mediators Qatar and Pakistan hailing a ‘historic’ opportunity for stability.",
    body: "US-Iran talks opened in Switzerland with mediators Qatar and Pakistan hailing a ‘historic’ opportunity for stability.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/us-iran-negotiations-in-switzerland-kick-off?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1782055004,
    tags: [],
  },
  {
    id: 38,
    cat: "conflitti",
    title: "Iran-US launch historic peace talks with 60-day roadmap",
    summary: "Iran-US launch historic peace talks with 60-day roadmap",
    body: "Iran-US launch historic peace talks with 60-day roadmap",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/iran-u-s-launch-historic-peace-talks-with-60-day-roadmap?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1782053696,
    tags: [],
  },
  {
    id: 39,
    cat: "conflitti",
    title: "Bolivian authorities say no active blockades after state of emergency decree",
    summary: "State of emergency permits deployment of military to support police amid five weeks of anti-government protests.",
    body: "State of emergency permits deployment of military to support police amid five weeks of anti-government protests.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/21/bolivian-authorities-say-no-active-blockades-after-state-of-emergency-decree?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1782052070,
    tags: [],
  },
  {
    id: 40,
    cat: "conflitti",
    title: "Gaza bids farewell to slain journalist Ahmed Wishah",
    summary: "Gaza bids farewell to slain journalist Ahmed Wishah.",
    body: "Gaza bids farewell to slain journalist Ahmed Wishah.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/6/21/gaza-bids-farewell-to-slain-journalist-ahmed-wishah?traffic_source=rss",
    time: "7 ore fa",
    pub_ts: 1782051169,
    tags: [],
  },
  {
    id: 41,
    cat: "conflitti",
    title: "Police charge man after suspected anti-Muslim attacks in Edinburgh",
    summary: "UK Prime Minister Keir Starmer says &#039;the suspect appears to be motivated by anti-Muslim hatred&#039;.",
    body: "UK Prime Minister Keir Starmer says &#039;the suspect appears to be motivated by anti-Muslim hatred&#039;.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/6/21/police-charge-man-after-suspected-anti-muslim-attacks-in-edinburgh?traffic_source=rss",
    time: "7 ore fa",
    pub_ts: 1782049977,
    tags: [],
  },
  {
    id: 42,
    cat: "ai",
    title: "Bose thinks it can be a media company for some reason",
    summary: "The history books are littered with the corpses of corporate record labels started by companies that had no business being in the music industry. Bose thinks it can be the exception to the rule. It thinks it can be Red Bull. And, while Bose has more of a right to dip its toes into the [&#8230;]",
    body: "The history books are littered with the corpses of corporate record labels started by companies that had no business being in the music industry. Bose thinks it can be the exception to the rule. It thinks it can be Red Bull. And, while Bose has more of a right to dip its toes into the media world than Build-a-Bear , there's little reason to believe it can succeed where so many others have failed.\n\nIn an interview with Business Insider , Bose CMO Jim Mollica said the company had created Bose Studios as part of a move away from traditional \"campaign-driven marketing.\" A big element of that is going to be Bose Records, a new label the company has …",
    source: "The Verge",
    url: "https://www.theverge.com/entertainment/953324/bose-studios-record-label-media-company",
    time: "2 ore fa",
    pub_ts: 1782068030,
    tags: [],
  },
  {
    id: 43,
    cat: "ai",
    title: "Ubisoft co-founder Claude Guillemot dies in plane crash",
    summary: "Claude Guillemot, who founded Ubisoft with his four brothers, has died at the age of 69.",
    body: "Claude Guillemot, who founded Ubisoft with his four brothers, has died at the age of 69.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/21/ubisoft-co-founder-claude-guillemot-dies-in-plane-crash/",
    time: "2 ore fa",
    pub_ts: 1782066871,
    tags: [],
  },
  {
    id: 44,
    cat: "ai",
    title: "Cold Court’s debut EP is an infectious, glitchy genre mashup",
    summary: "Cold Court is a brother-sister duo from Philly that seems to love nothing more than shoving all of their influences together in a messy soup that at least superficially resembles the hyperpop you've come to expect from acts like 100 Gecs. But, where songs like \"Dumbest Girl Alive\" goofily wink at pop punk and emo, [&#8230;]",
    body: "Cold Court is a brother-sister duo from Philly that seems to love nothing more than shoving all of their influences together in a messy soup that at least superficially resembles the hyperpop you've come to expect from acts like 100 Gecs. But, where songs like \"Dumbest Girl Alive\" goofily wink at pop punk and emo, Cold Court are a bit more self-serious, and that's not necessarily a bad thing. The opening track on the band's debut EP \\ (^_^) / (aka Hands Up ), \"Nina\", starts off sounding not unlike the dance punk bands that stormed the scene in the mid aughts like Franz Ferdinand or Test Icicles.\n\nBut that all starts to change about a minute …",
    source: "The Verge",
    url: "https://www.theverge.com/entertainment/953303/cold-court-hands-up-ep-music-review",
    time: "4 ore fa",
    pub_ts: 1782061233,
    tags: [],
  },
  {
    id: 45,
    cat: "ai",
    title: "Polymarket reportedly paid creators to post deceptive videos about fake bets",
    summary: "Many of those videos were reportedly filmed on “near-perfect copies” of the Polymarket website, while featuring trades and winnings that were not real.",
    body: "Many of those videos were reportedly filmed on “near-perfect copies” of the Polymarket website, while featuring trades and winnings that were not real.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/21/polymarket-reportedly-paid-creators-to-post-deceptive-videos-about-fake-bets/",
    time: "4 ore fa",
    pub_ts: 1782059700,
    tags: [],
  },
  {
    id: 46,
    cat: "ai",
    title: "TechCrunch Mobility: A new robotaxi scorecard shows China’s dominance",
    summary: "Welcome back to TechCrunch Mobility — your central hub for news and insights on the future of transportation.",
    body: "Welcome back to TechCrunch Mobility — your central hub for news and insights on the future of transportation.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/21/techcrunch-mobility-a-new-robotaxi-scorecard-shows-chinas-dominance/",
    time: "5 ore fa",
    pub_ts: 1782057900,
    tags: [],
  },
  {
    id: 47,
    cat: "ai",
    title: "When the Trump administration cracks down on Anthropic, who benefits?",
    summary: "On the new episode of Equity, we discussed what actually prompted the administration's latest moves against Anthropic, and what this might mean for the AI ecosystem.",
    body: "On the new episode of Equity, we discussed what actually prompted the administration's latest moves against Anthropic, and what this might mean for the AI ecosystem.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/21/when-the-trump-administration-cracks-down-on-anthropic-who-benefits/",
    time: "5 ore fa",
    pub_ts: 1782055697,
    tags: [],
  },
  {
    id: 48,
    cat: "ai",
    title: "Beyond Siri: Here are the practical AI features coming to your iPhone in iOS 27",
    summary: "Siri’s AI overhaul may have grabbed the headlines at WWDC, but some of Apple’s most useful AI features are arriving elsewhere in iOS 27.",
    body: "Siri’s AI overhaul may have grabbed the headlines at WWDC, but some of Apple’s most useful AI features are arriving elsewhere in iOS 27.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/21/beyond-siri-here-are-the-practical-ai-features-coming-to-your-iphone-in-ios-27/",
    time: "6 ore fa",
    pub_ts: 1782052828,
    tags: [],
  },
  {
    id: 49,
    cat: "ai",
    title: "Polymarket reportedly paid people to post fake videos of themselves placing bets",
    summary: "According to a Wall Street Journal investigation, Polymarket has been paying people to film themselves placing fake bets and celebrating fake wins on social media. WSJ identified over 1,100 deceptive clips and talked to creators who, despite not stating as such in their videos, confirmed the company paid them to create the clips. The videos [&#8230;]",
    body: "According to a Wall Street Journal investigation, Polymarket has been paying people to film themselves placing fake bets and celebrating fake wins on social media. WSJ identified over 1,100 deceptive clips and talked to creators who, despite not stating as such in their videos, confirmed the company paid them to create the clips . The videos posted on social media look legit at first, but there are subtle clues that betray them as fraudulent.\n\nFor instance, when examined closely, one clip shows someone visiting \"poiymarket.com\" rather than polymarket.com. According to the Journal's investigation, none of the bets placed in the over 1,100 vide …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/953285/polymarket-fake-viral-video-bets",
    time: "7 ore fa",
    pub_ts: 1782051586,
    tags: [],
  },
  {
    id: 50,
    cat: "ai",
    title: "How Roomba started a robot revolution",
    summary: "If you had a Roomba, especially in the early days of the robot vacuum, it was in many ways a fairly unsophisticated machine. It would just bump around your house, looking for something to suck up, until its battery died or its (way too small) tank filled up. Not that it mattered, though. You probably [&#8230;]",
    body: "If you had a Roomba, especially in the early days of the robot vacuum, it was in many ways a fairly unsophisticated machine. It would just bump around your house, looking for something to suck up, until its battery died or its (way too small) tank filled up. Not that it mattered, though. You probably loved your Roomba. You probably gave it a name. On this episode of Version History , we tell the story of the Roomba, and how it made vacuums lovable.\n\nThe Verge 's David Pierce and Jennifer Pattison Tuohy are joined by iRobot's co-founder and former CEO Colin Angle to trace the robovac revolution back to its origins, with a group of engineers try …",
    source: "The Verge",
    url: "https://www.theverge.com/podcast/953275/roomba-robot-vacuum-version-history",
    time: "8 ore fa",
    pub_ts: 1782044941,
    tags: [],
  },
  {
    id: 51,
    cat: "ai",
    title: "Electric air taxis are stuck in the courtroom",
    summary: "This is The Stepback, a weekly newsletter breaking down one essential story from the tech world. For more on aviation, air taxis, and Wi-Fi speeds at 30,000 feet, follow Andrew J. Hawkins. The Stepback arrives in our subscribers' inboxes on Sunday at 8AM ET. Opt in for The Stepback here. How it started Last year, [&#8230;]",
    body: "Joby flight at JFK airport. | Image: The Verge This is The Stepback , a weekly newsletter breaking down one essential story from the tech world. For more on aviation, air taxis, and Wi-Fi speeds at 30,000 feet, follow Andrew J. Hawkins . The Stepback arrives in our subscribers' inboxes on Sunday at 8AM ET. Opt in for The Stepback here . How it started Last year, two of the leading air taxi companies in the US, Joby Aviation and Archer Aviation, sued each other , with Joby accusing Archer of corporate espionage and Archer claiming that Joby was concealing its ties to China.\n\nThen, in February of this year, Archer filed a patent infringement suit against a different air taxi rival, Vertical A …",
    source: "The Verge",
    url: "https://www.theverge.com/column/950975/electric-air-taxis-lawsuits",
    time: "9 ore fa",
    pub_ts: 1782043200,
    tags: [],
  },
  {
    id: 52,
    cat: "ai",
    title: "Sony’s Xperia 1 VIII is still a phone for the fans",
    summary: "The Xperia 1 VIII marks an attempt at a step change for Sony's flagship phone line. Not only has it had an aesthetic overhaul, but Sony has also revamped the camera system, dropping the continuous optical zoom telephoto that's defined the last four generations of Xperia phone. It's not all different. Sony staples like a [&#8230;]",
    body: "The 1 VIII doesn’t look much like any Xperia that’s come before. The Xperia 1 VIII marks an attempt at a step change for Sony's flagship phone line. Not only has it had an aesthetic overhaul, but Sony has also revamped the camera system, dropping the continuous optical zoom telephoto that's defined the last four generations of Xperia phone . It's not all different. Sony staples like a 3.5mm headphone jack and microSD card slot remain, and a few specific design touches, like a thick front bezel that fits stereo speakers, have stayed intact.\n\nSony's ambitious pricing hasn't changed either: The Xperia 1 VIII isn't launching in the US, but in the UK and Europe, it starts from &pound;1,399 / &euro;1,499 (about $1,850), r …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/952245/sony-xperia-1-viii-review",
    time: "10 ore fa",
    pub_ts: 1782039600,
    tags: [],
  },
  {
    id: 53,
    cat: "ai",
    title: "Traiettorie convergenti. Intervista a Comellini di Thales e Patassa pilota collaudatore dell’Aeronautica militare italiana",
    summary: "Anthea Comellini e Andrea Patassa sono i due astronauti di riserva italiani della classe 2022 dell’Agenzia spaziale europea. Lei ingegnera, lui pilota collaudatore. Li abbiamo intervistati tra i nostri leader del futuro",
    body: "Anthea Comellini e Andrea Patassa sono i due astronauti di riserva italiani della classe 2022 dell’Agenzia spaziale europea. Lei ingegnera, lui pilota collaudatore. Li abbiamo intervistati tra i nostri leader del futuro",
    source: "Wired IT",
    url: "https://www.wired.it/article/intervista-anthea-comellini-thales-andrea-patassa-aeronautica-esa/",
    time: "16 ore fa",
    pub_ts: 1782018000,
    tags: [],
  },
  {
    id: 54,
    cat: "ai",
    title: "Per gli atleti dell’Iran, separare lo sport dalla politica è impossibile",
    summary: "Dalle pressioni politiche alle fughe all’estero, il Mondiale 2026 ha riportato al centro il rapporto tra identità, potere e libertà nella Repubblica islamica",
    body: "Dalle pressioni politiche alle fughe all’estero, il Mondiale 2026 ha riportato al centro il rapporto tra identità, potere e libertà nella Repubblica islamica",
    source: "Wired IT",
    url: "https://www.wired.it/article/iran-sport-politica-atleti-mondiali-2026/",
    time: "16 ore fa",
    pub_ts: 1782017400,
    tags: [],
  },
  {
    id: 55,
    cat: "ai",
    title: "Perché Titano, la luna più grande di Saturno, è il miglior avamposto per l’esplorazione umana dello Spazio",
    summary: "Il satellite ha un potenziale enorme. Ricco di idrocarburi e acqua ghiacciata, può aprirci la strada verso Urano e Nettuno. Ma la distanza si supera solo col nucleare",
    body: "Il satellite ha un potenziale enorme. Ricco di idrocarburi e acqua ghiacciata, può aprirci la strada verso Urano e Nettuno. Ma la distanza si supera solo col nucleare",
    source: "Wired IT",
    url: "https://www.wired.it/article/perche-titano-luna-piu-grande-saturno-miglior-avamposto-per-esplorazione-umana-spazio/",
    time: "16 ore fa",
    pub_ts: 1782016800,
    tags: [],
  },
  {
    id: 56,
    cat: "ai",
    title: "Le cellule staminali sono davvero la medicina del futuro?",
    summary: "Roberto Gramignoli e Gianvito Martino raccontano come le terapie cellulari stiano trasformando la medicina rigenerativa, dalla sclerosi multipla alla placenta, puntando a potenziare i processi di rigenerazione del corpo",
    body: "Roberto Gramignoli e Gianvito Martino raccontano come le terapie cellulari stiano trasformando la medicina rigenerativa, dalla sclerosi multipla alla placenta, puntando a potenziare i processi di rigenerazione del corpo",
    source: "Wired IT",
    url: "https://www.wired.it/article/cellule-staminali-medicina-del-futuro/",
    time: "16 ore fa",
    pub_ts: 1782016200,
    tags: [],
  },
  {
    id: 57,
    cat: "ai",
    title: "Ci sono film che anche dopo tanti anni sono in grado di insegnarci moltissimo e Il gobbo di Notre Dame è uno di questi",
    summary: "Trent'anni fa, il 21 giugno 1996, usciva nelle sale uno dei Classici simbolo del Rinascimento Disney, capace di affrontare tematiche profondissime con grande sensibilità",
    body: "Trent'anni fa, il 21 giugno 1996, usciva nelle sale uno dei Classici simbolo del Rinascimento Disney, capace di affrontare tematiche profondissime con grande sensibilità",
    source: "Wired IT",
    url: "https://www.wired.it/article/film-dopo-tanti-anni-sono-in-grado-di-insegnarci-moltissimo-gobbo-notre-dame-uno-di-questi/",
    time: "16 ore fa",
    pub_ts: 1782016200,
    tags: [],
  },
  {
    id: 58,
    cat: "ai",
    title: "Signal’s Meredith Whittaker wants you to remember that AI chatbots ‘are not your friends’",
    summary: "\"These are not your friends. These are not conscious beings. These are not sentient interlocutors.”",
    body: "\"These are not your friends. These are not conscious beings. These are not sentient interlocutors.”",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/20/signals-meredith-whittaker-wants-you-to-remember-that-ai-chatbots-are-not-your-friends/",
    time: "1 giorno fa",
    pub_ts: 1781987549,
    tags: [],
  },
  {
    id: 59,
    cat: "ai",
    title: "In the Weights is your new AI-centric vanity search",
    summary: "So ... what's your In the Weights score?",
    body: "So ... what's your In the Weights score?",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/20/in-the-weights-is-your-new-ai-centric-vanity-search/",
    time: "1 giorno fa",
    pub_ts: 1781984471,
    tags: [],
  },
  {
    id: 60,
    cat: "ai",
    title: "The Atlantic created a searchable database of the music used to train AI",
    summary: "Atlantic reporter Alex Reisner recently uncovered four datasets of music being used to train AI models and made them fully searchable for the public. Two of the sets are absolutely enormous at 12 million and 9 million tracks. The other two are much smaller, but still represent a significant amount of training data at over [&#8230;]",
    body: "Atlantic reporter Alex Reisner recently uncovered four datasets of music being used to train AI models and made them fully searchable for the public. Two of the sets are absolutely enormous at 12 million and 9 million tracks. The other two are much smaller, but still represent a significant amount of training data at over 100,000 songs each. According to Reisner, the sets have been downloaded thousands of times and, while it's impossible to know exactly who has used them, Google and Stability have both confirmed they have in research papers.\n\nSome of the sources, like the Free Music Archive dataset, are free to stream for personal use but re …",
    source: "The Verge",
    url: "https://www.theverge.com/ai-artificial-intelligence/953183/the-atlantic-searchable-database-music-ai-training-data",
    time: "1 giorno fa",
    pub_ts: 1781981208,
    tags: [],
  },
  {
    id: 61,
    cat: "ai",
    title: "Founders Fund’s outlier bet on humanely killed fish",
    summary: "Shinkei makes a refrigerator-sized robot called Poseidon to kill fish quickly and humanely.",
    body: "Shinkei makes a refrigerator-sized robot called Poseidon to kill fish quickly and humanely.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/06/20/founders-funds-outlier-bet-on-humanely-killed-fish/",
    time: "1 giorno fa",
    pub_ts: 1781979962,
    tags: [],
  },
  {
    id: 62,
    cat: "economia-tech",
    title: "Philippines fears China may move to seize full control of disputed atoll",
    summary: "Defence secretary warns of heightened Chinese military activity around Scarborough Shoal",
    body: "Defence secretary warns of heightened Chinese military activity around Scarborough Shoal",
    source: "Financial Times",
    url: "https://www.ft.com/content/d5191b00-dccb-465e-8afb-e61cc8260f93",
    time: "1 ora fa",
    pub_ts: 1782073170,
    tags: [],
  },
  {
    id: 63,
    cat: "economia-tech",
    title: "US and Iran hold crunch talks in Switzerland",
    summary: "Negotiations to permanently end the war focus on Israeli-Hizbollah conflict in Lebanon",
    body: "Negotiations to permanently end the war focus on Israeli-Hizbollah conflict in Lebanon",
    source: "Financial Times",
    url: "https://www.ft.com/content/c1014643-940c-4874-998a-0a52eb517c49",
    time: "1 ora fa",
    pub_ts: 1782070870,
    tags: [],
  },
  {
    id: 64,
    cat: "economia-tech",
    title: "Building materials group CRH nears its biggest-ever deal to buy Arcosa",
    summary: "Irish company closes in on purchase of Dallas-based construction firm with market capitalisation of almost $7bn",
    body: "Irish company closes in on purchase of Dallas-based construction firm with market capitalisation of almost $7bn",
    source: "Financial Times",
    url: "https://www.ft.com/content/6c95c41b-7bf1-4adf-84e9-08356f8a4981",
    time: "1 ora fa",
    pub_ts: 1782070289,
    tags: [],
  },
  {
    id: 65,
    cat: "economia-tech",
    title: "Warsh’s push to axe Fed guidance may lift US borrowing costs, investors warn",
    summary: "Traders see more volatility ahead as new central bank chair declines to give dot plot on future path of interest rates",
    body: "Traders see more volatility ahead as new central bank chair declines to give dot plot on future path of interest rates",
    source: "Financial Times",
    url: "https://www.ft.com/content/6a9330ad-a2db-494b-bf61-7dd417ab9c9a",
    time: "3 ore fa",
    pub_ts: 1782064801,
    tags: [],
  },
  {
    id: 66,
    cat: "economia-tech",
    title: "Wars trigger $12bn venture capital rush into defence tech",
    summary: "Funding this year has already surpassed 2025 total as soaring valuations fuel fears of a hype cycle",
    body: "Funding this year has already surpassed 2025 total as soaring valuations fuel fears of a hype cycle",
    source: "Financial Times",
    url: "https://www.ft.com/content/cb535f43-d2b7-4d14-82fe-abdd14765dfe",
    time: "3 ore fa",
    pub_ts: 1782064801,
    tags: [],
  },
  {
    id: 67,
    cat: "economia-tech",
    title: "Zombie unicorns are haunting Silicon Valley",
    summary: "Years of frothy valuations have created a nightmare",
    body: "Years of frothy valuations have created a nightmare",
    source: "The Economist Ec",
    url: "https://www.economist.com/business/2026/06/21/zombie-unicorns-are-haunting-silicon-valley",
    time: "3 ore fa",
    pub_ts: 1782062683,
    tags: [],
  },
  {
    id: 68,
    cat: "economia-tech",
    title: "Back-stabbing myths are driving the US and Europe further apart",
    summary: "Competing narratives of abandonment — from Iran to Greenland — could lead to Nato’s permanent unravelling",
    body: "Competing narratives of abandonment — from Iran to Greenland — could lead to Nato’s permanent unravelling",
    source: "Financial Times",
    url: "https://www.ft.com/content/4a9be9b8-4cac-49d5-8e08-cb750007b2db",
    time: "6 ore fa",
    pub_ts: 1782054008,
    tags: [],
  },
  {
    id: 69,
    cat: "economia-tech",
    title: "UK to Ban Social Media for Under-16s Starting Next Year",
    summary: "Big tech companies design their products to maximize user attention, often without regard to whether the content is beneficial, especially for children. Beeban Kidron, author of 'Users,' joins Bloomberg This Weekend to discuss with hosts David Gura and Christina Ruffini the need for government intervention to regulate product design, parental responsibility in managing usage, and consumer…",
    body: "Big tech companies design their products to maximize user attention, often without regard to whether the content is beneficial, especially for children. Beeban Kidron, author of 'Users,' joins Bloomberg This Weekend to discuss with hosts David Gura and Christina Ruffini the need for government intervention to regulate product design, parental responsibility in managing usage, and consumer awareness to make informed choices in the attention economy.\n\n(Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-06-21/uk-to-ban-social-media-for-under-16s-starting-next-year-video",
    time: "6 ore fa",
    pub_ts: 1782052751,
    tags: [],
  },
  {
    id: 70,
    cat: "economia-tech",
    title: "Apple’s New CEO Must Rebuild a Design Team That Lost Its Way",
    summary: "Also: The 2027 iPhone and AirPods plans.",
    body: "Apple Inc. iPhone 17 Pro series smartphones displayed at one of the company's stores during the first day of sales of the smartphones in Mumbai, India, on Friday, Sept. 19, 2025. For the past four years, some Apple Inc. customers have been waiting for a fresh design before buying a new iPhone. The time has come for those consumers, with the iPhone 17 Pro, iPhone 17 Pro Max and iPhone Air going on sale Friday.\n\nPhotographer: Dhiraj Singh/Bloomberg",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/newsletters/2026-06-21/apple-s-new-ceo-ternus-needs-to-shake-up-design-apple-s-2027-iphone-road-map-mqnust26",
    time: "7 ore fa",
    pub_ts: 1782050401,
    tags: [],
  },
  {
    id: 71,
    cat: "economia-tech",
    title: "Amazon Advances Prime Day by One Month Amid AI Shift",
    summary: "Amazon has moved its annual Prime Day sales event up by one month. The event is strategically important for Amazon as it aims to capture consumer spending, especially in a market where discretionary dollars are tightening and AI is increasingly influencing shopping behavior. Senior E-commerce and retail analyst for Bloomberg Intelligence Poonam Goyal explains the importance of Prime Day for…",
    body: "Amazon has moved its annual Prime Day sales event up by one month. The event is strategically important for Amazon as it aims to capture consumer spending, especially in a market where discretionary dollars are tightening and AI is increasingly influencing shopping behavior. Senior E-commerce and retail analyst for Bloomberg Intelligence Poonam Goyal explains the importance of Prime Day for Amazon to David Gura and Christina Ruffini on Bloomberg This Weekend.\n\n(Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-06-21/amazon-advances-prime-day-by-one-month-amid-ai-shift-video",
    time: "8 ore fa",
    pub_ts: 1782047283,
    tags: [],
  },
  {
    id: 72,
    cat: "economia-tech",
    title: "Why Giorgia Meloni turned on Donald Trump",
    summary: "Italian premier’s fallout with US president comes as she gears up for re-election battle",
    body: "Italian premier’s fallout with US president comes as she gears up for re-election battle",
    source: "Financial Times",
    url: "https://www.ft.com/content/1adcac1d-d2d3-4a62-855d-7dd56319edbf",
    time: "8 ore fa",
    pub_ts: 1782046112,
    tags: [],
  },
  {
    id: 73,
    cat: "economia-tech",
    title: "Yoga e Pilates, la sfida tra benessere ed economia sportiva",
    summary: "Più che rivali, sono cugini. Non in concorrenza ma discipline complementari. Una, lo yoga, ha una storia millenaria , l’altra, il pilates, giusto un secolo, ma riescono ad accomunare...",
    body: "Più che rivali, sono cugini. Non in concorrenza ma discipline complementari. Una, lo yoga, ha una storia millenaria , l’altra, il pilates, giusto un secolo, ma riescono ad accomunare...",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/yoga-e-pilates-benessere-ed-economia-sportiva-AIu8rhnD",
    time: "10 ore fa",
    pub_ts: 1782038340,
    tags: [],
  },
  {
    id: 74,
    cat: "economia-tech",
    title: "Pmi e innovazione: solo una su dieci investe in ricerca e sviluppo",
    summary: "Ma gli investimenti sono cresciuti del 17% in quattro anni, secondo una ricerca della Polimi School of management",
    body: "Ma gli investimenti sono cresciuti del 17% in quattro anni, secondo una ricerca della Polimi School of management",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/pmi-e-innovazione-solo-su-dieci-investe-ricerca-e-sviluppo-AIBzMwhD",
    time: "13 ore fa",
    pub_ts: 1782029052,
    tags: [],
  },
  {
    id: 75,
    cat: "economia-tech",
    title: "Miniere, i turisti tornano in galleria sui trenini della Valente",
    summary: "Turisti e minerali. Si torna in miniera con i trenini costruiti in Italia e in grado di trasportare le materie prime estratte nelle gallerie e nei pozzi, e con i...",
    body: "Turisti e minerali. Si torna in miniera con i trenini costruiti in Italia e in grado di trasportare le materie prime estratte nelle gallerie e nei pozzi, e con i...",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/miniere-turisti-tornano-galleria-trenini-valente-AIKj6QmD",
    time: "14 ore fa",
    pub_ts: 1782025452,
    tags: [],
  },
  {
    id: 76,
    cat: "economia-tech",
    title: "Sorry, Elon, the far right is still the far right",
    summary: "And on some issues, it’s further to the right than before",
    body: "And on some issues, it’s further to the right than before",
    source: "Financial Times",
    url: "https://www.ft.com/content/313f78c7-8959-4188-a3d2-dc9132ef0ba3",
    time: "17 ore fa",
    pub_ts: 1782014417,
    tags: [],
  },
  {
    id: 77,
    cat: "economia-tech",
    title: "Millions in Brazil Get Fake Government Mobile Alert After Hack",
    summary: "Brazil’s Integration and Regional Development Ministry and federal police are investigating an intrusion into the civil defense alert system that sent messages containing the word “misanthropy” to the mobile phones of millions of Brazilians.",
    body: "Brazil’s Integration and Regional Development Ministry and federal police are investigating an intrusion into the civil defense alert system that sent messages containing the word “misanthropy” to the mobile phones of millions of Brazilians.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-20/millions-in-brazil-get-fake-government-mobile-alert-after-hack",
    time: "1 giorno fa",
    pub_ts: 1781973945,
    tags: [],
  },
  {
    id: 78,
    cat: "economia-tech",
    title: "Jio Platforms Plans $3 Billion Debt Reduction from IPO Proceeds",
    summary: "Jio Platforms Ltd. plans to use part of the proceeds from its proposed initial share sale to repay its telecom unit’s external commercial borrowings of almost $3 billion, a draft IPO document showed.",
    body: "Signage for Jio Platforms Ltd., a subsidiary of Reliance Industries Ltd., displayed along a road in Mumbai, India, on Wednesday, June 17, 2026. The long-running saga over the listing of Reliance Industries Ltd.’s digital unit comes to the fore this week, as investors watch whether its billionaire chairman Mukesh Ambani can walk the talk from last year.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-20/jio-platforms-plans-3-billion-debt-reduction-from-ipo-proceeds",
    time: "1 giorno fa",
    pub_ts: 1781952571,
    tags: [],
  },
  {
    id: 79,
    cat: "economia-tech",
    title: "BYD Rejects Claims It Violated Hungary’s Environmental Rules",
    summary: "Chinese electric vehicle maker BYD Co. said it rejected allegations it breached environmental rules in Hungary during the construction of its first plant in the European Union.",
    body: "Chinese electric vehicle maker BYD Co. said it rejected allegations it breached environmental rules in Hungary during the construction of its first plant in the European Union.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-06-20/byd-rejects-claims-it-violated-hungary-s-environmental-rules",
    time: "1 giorno fa",
    pub_ts: 1781941653,
    tags: [],
  },
  {
    id: 80,
    cat: "economia-tech",
    title: "Brasile e Argentina, per l’export crescita potenziale di 6 miliardi",
    summary: "A settembre la missione B2B di Confindustria, in collaborazione con Ice. Cimmino: «L’accordo tra Ue e Mercosur apre una nuova stagione per le imprese»",
    body: "A settembre la missione B2B di Confindustria, in collaborazione con Ice. Cimmino: «L’accordo tra Ue e Mercosur apre una nuova stagione per le imprese»",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/brasile-e-argentina-l-export-crescita-potenziale-6-miliardi-AImyY0lD",
    time: "1 giorno fa",
    pub_ts: 1781935453,
    tags: [],
  },
  {
    id: 81,
    cat: "economia-tech",
    title: "Notte Rosa in Romagna, gli show e appuntamenti da non perdere",
    summary: "Quasi 150 eventi diffusi sul territorio per festeggiare il solstizio d’estate. Domenica l’Air show delle Frecce Tricolori",
    body: "Quasi 150 eventi diffusi sul territorio per festeggiare il solstizio d’estate. Domenica l’Air show delle Frecce Tricolori",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/notte-rosa-romagna-show-e-appuntamenti-non-perdere-AIP6MklD",
    time: "1 giorno fa",
    pub_ts: 1781933521,
    tags: [],
  },
];
